local config = {
	[MsgDefines.ShowStatusItem] = "Net.Msgs.ShowStatusItemMessage",
	[MsgDefines.TaskRewardGet] = "Net.Msgs.TaskRewardGetMessage",
	[MsgDefines.ChapterTask] = "Net.Msgs.ChapterTaskMessage",
	[MsgDefines.PushTaskChapterTask] = "Net.Msgs.PushTaskChapterTaskMessage",
	[MsgDefines.Init] = "Net.Msgs.InitMessage",
	[MsgDefines.ClientLog] = "Net.Msgs.ClientLogMessage",
	[MsgDefines.ItemUse] = "Net.Msgs.ItemUseMessage",
	[MsgDefines.UseResItemMulti] = "Net.Msgs.UseResItemMultiMessage",
	[MsgDefines.PushItemUpdate] = "Net.Msgs.PushItemUpdateMessage",
	[MsgDefines.PushItemAdd] = "Net.Msgs.PushItemAddMessage",
	[MsgDefines.UIShopBuy] = "Net.Msgs.UIShopBuyMessage",
	[MsgDefines.ScienceResearchNew] = "Net.Msgs.ScienceResearchNewMessage",
	[MsgDefines.PushScienceChange] = "Net.Msgs.PushScienceChangeMessage",
	[MsgDefines.PushPlayerAllianceRank] = "Net.Msgs.PushPlayerAllianceRankMessage",
	[MsgDefines.LoginOther] = "Net.Msgs.LoginOtherMessage",
	[MsgDefines.SaveFormationTempHero] = "Net.Msgs.SaveFormationTempHeroMessage",
	[MsgDefines.ArmyAdd] = "Net.Msgs.ArmyAddMessage",
	[MsgDefines.PushArmyChange] = "Net.Msgs.PushArmyChangeMessage",
	[MsgDefines.SoldierUp] = "Net.Msgs.SoldierUpMessage",
	[MsgDefines.FindMonster] = "Net.Msgs.FindMonsterMessage",
	[MsgDefines.WorldGetDetail] = "Net.Msgs.WorldGetDetailMessage",
	[MsgDefines.PushFightReward] = "Net.Msgs.PushFightRewardMessage",

	[MsgDefines.FormationName] = "Net.Msgs.FormationNameMessage",
	[MsgDefines.FormationSave] = "Net.Msgs.FormationSaveMessage",
	[MsgDefines.PushArmyFormationUpdate] = "Net.Msgs.PushArmyFormationUpdateMessage",
	[MsgDefines.QueueCcdMNew] = "Net.Msgs.QueueCcdMNewMessage",
	[MsgDefines.HospitalCure] = "Net.Msgs.HospitalCureMessage",
	[MsgDefines.QueueFinish] = "Net.Msgs.QueueFinishMessage",
	[MsgDefines.QueueFinishBatch] = "Net.Msgs.QueueFinishBatchMessage",
	[MsgDefines.PushHospitalChange] = "Net.Msgs.PushHospitalChangeMessage",
	[MsgDefines.BuildCcdMNew] = "Net.Msgs.BuildCcdMNewMessage",
	[MsgDefines.ItemBuyAndUse] = "Net.Msgs.ItemBuyAndUseMessage",
	[MsgDefines.GetNewUserInfo] = "Net.Msgs.GetNewUserInfoMessage",
	[MsgDefines.NickNameChange] = "Net.Msgs.NickNameChangeMessage",
	[MsgDefines.NickNameCheck] = "Net.Msgs.NickNameCheckMessage",
	[MsgDefines.PlayerRankList] = "Net.Msgs.PlayerRankListMessage",
	[MsgDefines.PlayerKillRankList] = "Net.Msgs.PlayerKillRankListMessage",
	[MsgDefines.PlayerBaseRankList] = "Net.Msgs.PlayerBaseRankListMessage",

	[MsgDefines.PushTaskNew] = "Net.Msgs.PushTaskNewMessage",
	[MsgDefines.PushTaskComplete] = "Net.Msgs.PushTaskCompleteMessage",
	[MsgDefines.DailyQuestLs] = "Net.Msgs.DailyQuestLsMessage",
	--[MsgDefines.PushNewDailyTask] = "Net.Msgs.PushNewDailyTaskMessage",
	[MsgDefines.DailyQuestReward] = "Net.Msgs.DailyQuestRewardMessage",
	[MsgDefines.DailyQuestRewardMulti] = "Net.Msgs.DailyQuestRewardMultiMessage",
	[MsgDefines.DailyQuestGetAllReward] = "Net.Msgs.DailyQuestGetAllRewardMessage",
	[MsgDefines.ParsePushSet] = "Net.Msgs.ParsePushSetMessage",
	[MsgDefines.WorldFavoDel] = "Net.Msgs.WorldFavoDelMessage",
	[MsgDefines.WorldFavoGet] = "Net.Msgs.WorldFavoGetMessage",
	[MsgDefines.WorldFavoAdd] = "Net.Msgs.WorldFavoAddMessage",
	[MsgDefines.WorldGetAllianceMark] = "Net.Msgs.WorldGetAllianceMarkMessage",
	[MsgDefines.WorldAddAllianceMark] = "Net.Msgs.WorldAddAllianceMarkMessage",
	[MsgDefines.WorldDelAllianceMark] = "Net.Msgs.WorldDelAllianceMarkMessage",
	[MsgDefines.WorldAddAllianceMarkPush] = "Net.Msgs.WorldAddAllianceMarkPushMessage",
	[MsgDefines.WorldDelAllianceMarkPush] = "Net.Msgs.WorldDelAllianceMarkPushMessage",
	[MsgDefines.HeroStarUp] = "Net.Msgs.HeroStarUpMessage",
	[MsgDefines.PushAllianceTechRecommend] = "Net.Msgs.Alliance.PushAllianceTechRecommendMessage",
	[MsgDefines.AllianceLeaderElect] = "Net.Msgs.Alliance.AllianceLeaderElectMessage",
	[MsgDefines.AllianceInviteAccept] = "Net.Msgs.Alliance.AllianceInviteAcceptMessage",
	[MsgDefines.AllianceInviteRefuse] = "Net.Msgs.Alliance.AllianceInviteRefuseMessage",
	[MsgDefines.GetAlLeaderCandidates] = "Net.Msgs.Alliance.GetAlLeaderCandidatesMessage",
	[MsgDefines.AllianceLeaderVote] = "Net.Msgs.Alliance.AllianceLeaderVoteMessage",
	[MsgDefines.AllianceSysStateChange] = "Net.Msgs.Alliance.PushAlSysStateMessage",
	[MsgDefines.GetAlLeaderElectCandidates] = "Net.Msgs.Alliance.GetAlLeaderElectCandidatesMessage",
	[MsgDefines.AlLeaderElectSignUp] = "Net.Msgs.Alliance.AlLeaderElectSignUpMessage",
	[MsgDefines.AlLeaderElectChangeSlogan] = "Net.Msgs.Alliance.AlLeaderElectChangeSloganMessage",
	[MsgDefines.AlLeaderElectVote] = "Net.Msgs.Alliance.AlLeaderElectVoteMessage",
	[MsgDefines.AutoJoinAlliance] = "Net.Msgs.Alliance.AutoJoinAllianceMessage",
	[MsgDefines.BecomeAlLeader] = "Net.Msgs.Alliance.BecomeAlLeaderMessage",
	[MsgDefines.PushAlWaitMergeStatus] = "Net.Msgs.Alliance.PushAlWaitMergeMessage",
	[MsgDefines.PushRecommendAlMember] = "Net.Msgs.Alliance.PushRecommendAlMemberMessage",
	[MsgDefines.AlInviteRecommendUser] = "Net.Msgs.Alliance.AlInviteRecommendUserMessage",
	[MsgDefines.GetMineCaveInfo] = "Net.Msgs.GetMineCaveInfoMessage",
	[MsgDefines.RefreshMineCaveList] = "Net.Msgs.RefreshMineCaveListMessage",
	[MsgDefines.ClaimMineCaveReward] = "Net.Msgs.ClaimMineCaveRewardMessage",
	[MsgDefines.GetMineCavePlunderLog] = "Net.Msgs.GetMineCavePlunderLogMessage",
	[MsgDefines.PushNewMineCavePlunderLog] = "Net.Msgs.PushMineCavePlunderLogMessage",
	[MsgDefines.GetJigsawActivityInfo] = "Net.Msgs.GetJigsawInfoMessage",
	[MsgDefines.BeginJigsawChallenge] = "Net.Msgs.BeginJigsawChallengeMessage",
	[MsgDefines.FinishJigsawPuzzle] = "Net.Msgs.FinishJigsawPuzzleMessage",
	[MsgDefines.GetJigsawRankInfo] = "Net.Msgs.GetJigsawRankInfoMessage",
	
	[MsgDefines.GetDigActivityInfo] = "Net.Msgs.GetDigActivityInfoMessage",
	[MsgDefines.DigOneBlock] = "Net.Msgs.DigOneBlockMessage",
	[MsgDefines.StartAutoDig] = "Net.Msgs.StartAutoDigMessage",
	[MsgDefines.SelectFinalDigReward] = "Net.Msgs.SelectFinalDigRewardMessage",
	[MsgDefines.BuyDigTool] = "Net.Msgs.BuyDigToolMessage",
	[MsgDefines.GetDigActivityRankInfo] = "Net.Msgs.GetDigActivityRankInfoMessage",
	
	[MsgDefines.GetSeasonPassInfo] = "Net.Msgs.Activity.SeasonPass.GetSeasonPassInfoMessage",
	[MsgDefines.ClaimSeasonPassTaskReward] = "Net.Msgs.Activity.SeasonPass.ClaimSeasonPassTaskRewardMessage",
	[MsgDefines.ClaimSeasonPassLevelReward] = "Net.Msgs.Activity.SeasonPass.ClaimSeasonPassLevelRewardMessage",
	[MsgDefines.ClaimSeasonPassExtraReward] = "Net.Msgs.Activity.SeasonPass.ClaimSeasonPassExtraRewardMessage",
	[MsgDefines.PushSeasonPassInfoUpdate] = "Net.Msgs.Activity.SeasonPass.PushSeasonPassInfoUpdateMessage",
	[MsgDefines.PushSeasonPassTaskUpdate] = "Net.Msgs.Activity.SeasonPass.PushSeasonPassTaskUpdateMessage",
	[MsgDefines.ClaimAllSeasonPassReward] = "Net.Msgs.Activity.SeasonPass.ClaimAllSeasonPassRewardMessage",

	-- 账号相关设置消息
	[MsgDefines.AccountBind] = "Net.Msgs.Account.AccountBindMessage",
	[MsgDefines.AccountChangeMail] = "Net.Msgs.Account.AccountChangeMailMessage",
	[MsgDefines.AccountVerify] = "Net.Msgs.Account.AccountVerifyMessage",
	[MsgDefines.AccountChangePassword] = "Net.Msgs.Account.AccountChangePasswordMessage",
	[MsgDefines.AccountForgetPassword] = "Net.Msgs.Account.AccountForgetPasswordMessage",
	[MsgDefines.CheckAccountMailVerifyCode] = "Net.Msgs.Account.CheckAccountMailVerifyCodeMessage",
	[MsgDefines.CheckAccountPassword] = "Net.Msgs.Account.CheckAccountPasswordMessage",
	[MsgDefines.AccountResetPassword] = "Net.Msgs.Account.AccountResetPasswordMessage",
	[MsgDefines.AccountLogin] = "Net.Msgs.Account.AccountLoginMessage",				--***新的登陆规则，旧登陆弃用***
	[MsgDefines.AccountLoginSendVerifyCode] = "Net.Msgs.Account.AccountLoginSendVerifyCodeMessage",
	[MsgDefines.AccountVerifyDevice] = "Net.Msgs.Account.AccountVerifyDeviceMessage",
	[MsgDefines.AccountDeleteVerifyDevice] = "Net.Msgs.Account.AccountDeleteVerifyDeviceMessage",
	[MsgDefines.AccountLoginNew] = "Net.Msgs.Account.AccountLoginNewMessage",
	[MsgDefines.AccountGetAllServer] = "Net.Msgs.Account.AccountGetAllServerMessage",
	[MsgDefines.AccountResendMail] = "Net.Msgs.Account.AccountResendMailMessage",
	[MsgDefines.NewAccount] = "Net.Msgs.Account.NewAccountMessage",
	[MsgDefines.PinOldPwdCheck] = "Net.Msgs.Account.PinOldPwdCheckMessage",
	[MsgDefines.PinPwdCheckFrequency] = "Net.Msgs.Account.PinPwdCheckFrequencyMessage",
	[MsgDefines.PinPwdCheck] = "Net.Msgs.Account.PinPwdCheckMessage",
	[MsgDefines.PinPwdForget] = "Net.Msgs.Account.PinPwdForgetMessage",
	[MsgDefines.PinSetPwd] = "Net.Msgs.Account.PinSetPwdMessage",
	[MsgDefines.PushCheckPasswordStatus] = "Net.Msgs.Account.PushCheckPasswordStatusMessage",
	[MsgDefines.PushAccountChangePwd] = "Net.Msgs.Account.PushAccountChangePwdMessage",
	[MsgDefines.PushAccountFirmed] = "Net.Msgs.Account.PushAccountFirmedMessage",
	[MsgDefines.PushSetting] = "Net.Msgs.Account.PushSettingMessage",
	[MsgDefines.SetCountryFlag] = "Net.Msgs.Account.SetCountryFlagMessage",
	[MsgDefines.UserBindCancel] = "Net.Msgs.Account.UserBindCancelMessage",
	[MsgDefines.UserBind] = "Net.Msgs.Account.UserBindMessage",
	[MsgDefines.UserCleanPost] = "Net.Msgs.Account.UserCleanPostMessage",
	[MsgDefines.UpdatePic] = "Net.Msgs.Account.UpdatePicMessage",
	[MsgDefines.PushPicVerUpdate] = "Net.Msgs.Account.PushPicVerUpdateMessage",


	-- 活动相关，以后持续加的话都放到这里
	[MsgDefines.ActivityEventInfoGet] = "Net.Msgs.Activity.ActivityEventInfoGetMessage",
	[MsgDefines.ActivityEventRankReward] = "Net.Msgs.Activity.ActivityEventRankRewardMessage",
	[MsgDefines.ActivityTodayPersonalRank] = "Net.Msgs.Activity.ActivityTodayPersonalRankMessage",
	[MsgDefines.PushNewActivity] = "Net.Msgs.Activity.PushNewActivityMessage",
	[MsgDefines.PushActivityEvent] = "Net.Msgs.Activity.PushActivityEventMessage",
	[MsgDefines.ActivityPushMessage] = "Net.Msgs.Activity.ActivityPushMessage",
	[MsgDefines.BarterShopExchange] = "Net.Msgs.Activity.BarterShopExchangeMessage",
	[MsgDefines.GetThemeActivityInfo] = "Net.Msgs.Activity.GetThemeActivityInfoMessage",
	[MsgDefines.ClaimThemeActNoticeReward] = "Net.Msgs.Activity.ClaimThemeActNoticeRewardMessage",
	[MsgDefines.AcceptPersonalReward] = "Net.Msgs.Activity.AcceptPersonalReward",
	[MsgDefines.ActivityPanelInfo] = "Net.Msgs.Activity.ActivityPanelInfo",
	[MsgDefines.GetHeroEventCalendar] = "Net.Msgs.Activity.GetHeroEventCalendarMessage",
	[MsgDefines.ChooseHeroEvent] = "Net.Msgs.Activity.ChooseHeroEventMessage",
	[MsgDefines.UserDayActInfo] = "Net.Msgs.Activity.UserDayActInfoMessage",
	[MsgDefines.PushTaskDayAct] = "Net.Msgs.Activity.PushTaskDayAct",
	[MsgDefines.PushTaskDayActScore] = "Net.Msgs.Activity.PushTaskDayActScore",
	[MsgDefines.UserDayActReward] = "Net.Msgs.Activity.UserDayActReward",

	[MsgDefines.GetPuzzleActivityInfo] = "Net.Msgs.Activity.GetPuzzleActivityInfoMessage",
	[MsgDefines.ReceivePuzzleTaskReward] = "Net.Msgs.Activity.ReceivePuzzleTaskRewardMessage",
	[MsgDefines.ReceivePuzzleReward] = "Net.Msgs.Activity.ReceivePuzzleRewardMessage",
	[MsgDefines.PushPuzzleTaskFinish] = "Net.Msgs.Activity.PushPuzzleTaskFinish",

	[MsgDefines.CreatePuzzleBoss] = "Net.Msgs.Activity.CreatePuzzleBossMessage",
	[MsgDefines.GetPuzzleBossMarch] = "Net.Msgs.Activity.GetPuzzleBossMarchMessage",
	[MsgDefines.UserGetPuzzleBossRank] = "Net.Msgs.Activity.UserGetPuzzleBossRankMessage",
	[MsgDefines.GetPuzzleBossRankRewardInfo] = "Net.Msgs.Activity.GetPuzzleBossRankRewardInfoMessage",
	-- 付费礼包相关
	[MsgDefines.ExchangeInfo] = "Net.Msgs.Pay.ExchangeInfoMessage",
	[MsgDefines.PayAmazon] = "Net.Msgs.Pay.PayAmazonMessage",
	[MsgDefines.PayBeforeCheck] = "Net.Msgs.Pay.PayBeforeCheckMessage",
	[MsgDefines.PayIOS] = "Net.Msgs.Pay.PayIOSMessage",
	[MsgDefines.PaySteam] = "Net.Msgs.Pay.PaySteamMessage",
	[MsgDefines.Pay] = "Net.Msgs.Pay.PayMessage",
	[MsgDefines.PayPtGold] = "Net.Msgs.Pay.PayPtGoldMessage",
	[MsgDefines.PayRecord] = "Net.Msgs.Pay.PayRecordMessage",
	[MsgDefines.PayTest] = "Net.Msgs.Pay.PayTestMessage",
	[MsgDefines.PayTstore] = "Net.Msgs.Pay.PayTstoreMessage",
	[MsgDefines.PushExchangeNew] = "Net.Msgs.Pay.PushExchangeNewMessage",
	---------------------------------------------------------------------------

	[MsgDefines.AllianceCompeteWeekResult] = "Net.Msgs.Activity.AllianceCompeteWeekResultMessage",
	[MsgDefines.AllianceCompeteRankList] = "Net.Msgs.Activity.AllianceCompeteRankListMessage",
	[MsgDefines.AllianceCompeteWeeklySummary] = "Net.Msgs.Activity.AllianceCompeteWeeklySummaryMessage",
	[MsgDefines.GetMyLeagueMatchInfo] = "Net.Msgs.Activity.LeagueMatch.GetMyLeagueMatchInfoMessage",
	[MsgDefines.GetCurSeasonLeagueMatchGroupInfo] = "Net.Msgs.Activity.LeagueMatch.GetCurSeasonLeagueMatchGroupInfoMessage",
	[MsgDefines.GetLastSeasonLeagueMatchGroupInfo] = "Net.Msgs.Activity.LeagueMatch.GetLastSeasonLeagueMatchGroupInfoMessage",
	[MsgDefines.PushLeagueMatchBaseInfo] = "Net.Msgs.Activity.LeagueMatch.PushLeagueMatchBaseInfoMessage",
	[MsgDefines.LeagueMatchDrawLots] = "Net.Msgs.Activity.LeagueMatch.LeagueMatchDrawLotsMessage",
	[MsgDefines.GetLeagueMatchRewardInfo] = "Net.Msgs.Activity.LeagueMatch.GetLeagueMatchRewardInfoMessage",
	[MsgDefines.GetLeagueMatchWarmRewardInfo] = "Net.Msgs.Activity.LeagueMatch.GetLeagueMatchWarmRewardInfoMessage",

	-- 联盟相关
	[MsgDefines.AcceptAllianceApply] = "Net.Msgs.Alliance.AcceptAllianceApplyMessage",
	[MsgDefines.AlAbbr] = "Net.Msgs.Alliance.AlAbbrMessage",
	[MsgDefines.AlApplyList] = "Net.Msgs.Alliance.AlApplyListMessage",
	[MsgDefines.GetAllianceAutoInviteInfo] = "Net.Msgs.Alliance.GetAllianceAutoInviteInfoMessage",
	[MsgDefines.AcceptAllianceAutoInvite] = "Net.Msgs.Alliance.AcceptAllianceAutoInviteMessage",
	[MsgDefines.PushNewAllianceAutoInvite] = "Net.Msgs.Alliance.PushNewAllianceAutoInviteMessage",
	[MsgDefines.AlApply] = "Net.Msgs.Alliance.AlApplyMessage",
	[MsgDefines.AlBeLeaderCheck] = "Net.Msgs.Alliance.AlBeLeaderCheckMessage",
	[MsgDefines.AlCancelApply] = "Net.Msgs.Alliance.AlCancelApplyMessage",
	[MsgDefines.AlCreate] = "Net.Msgs.Alliance.AlCreateMessage",
	[MsgDefines.AlDismiss] = "Net.Msgs.Alliance.AlDismissMessage",
	[MsgDefines.AlHelpAll] = "Net.Msgs.Alliance.AlHelpAllMessage",
	[MsgDefines.AlLeave] = "Net.Msgs.Alliance.AlLeaveMessage",
	[MsgDefines.AllianceMoveCity] = "Net.Msgs.Alliance.AllianceMoveCityMessage",
	[MsgDefines.RefuseAllianceMoveInvite] = "Net.Msgs.Alliance.RefuseAllianceMoveInviteMessage",
	[MsgDefines.InviteMoveCity] = "Net.Msgs.Alliance.InviteMoveCityMessage",
	[MsgDefines.PushAllianceMoveInvite] = "Net.Msgs.Alliance.PushAllianceMoveInviteMessage",
	[MsgDefines.AllianceAllGiftRemove] = "Net.Msgs.Alliance.AllianceAllGiftRemoveMessage",
	[MsgDefines.AllianceCallHelp] = "Net.Msgs.Alliance.AllianceCallHelpMessage",
	[MsgDefines.AllianceChangeAttributes] = "Net.Msgs.Alliance.AllianceChangeAttributesMessage",
	[MsgDefines.AllianceDeleteOffical] = "Net.Msgs.Alliance.AllianceDeleteOfficalMessage",
	[MsgDefines.AllianceDonateRankAll] = "Net.Msgs.Alliance.AllianceDonateRankAllMessage",
	[MsgDefines.AllianceDonateRankDay] = "Net.Msgs.Alliance.AllianceDonateRankDayMessage",
	[MsgDefines.AllianceDonateRankWeek] = "Net.Msgs.Alliance.AllianceDonateRankWeekMessage",
	[MsgDefines.AllianceGiftGetReward] = "Net.Msgs.Alliance.AllianceGiftGetRewardMessage",
	[MsgDefines.GetAllianceStorageInfo] = "Net.Msgs.Alliance.GetAllianceStorageInfoMessage",
	[MsgDefines.AllianceGiftInfo] = "Net.Msgs.Alliance.AllianceGiftInfoMessage",
	[MsgDefines.AllianceGiftList] = "Net.Msgs.Alliance.AllianceGiftListMessage",
	[MsgDefines.AllianceGiftRemove] = "Net.Msgs.Alliance.AllianceGiftRemoveMessage",
	[MsgDefines.AllianceInvitePlayer] = "Net.Msgs.Alliance.AllianceInvitePlayerMessage",
	[MsgDefines.AllianceKickMember] = "Net.Msgs.Alliance.AllianceKickMemberMessage",
	[MsgDefines.AllianceKillRankList] = "Net.Msgs.Alliance.AllianceKillRankListMessage",
	[MsgDefines.AllianceLeaderReplace] = "Net.Msgs.Alliance.AllianceLeaderReplaceMessage",
	[MsgDefines.AllianceLeaderTrans] = "Net.Msgs.Alliance.AllianceLeaderTransMessage",
	[MsgDefines.AllianceRankList] = "Net.Msgs.Alliance.AllianceRankListMessage",
	[MsgDefines.AllianceReceiveAllGift] = "Net.Msgs.Alliance.AllianceReceiveAllGiftMessage",
	[MsgDefines.AllianceRenderHelp] = "Net.Msgs.Alliance.AllianceRenderHelpMessage",
	[MsgDefines.AllianceRewardHideName] = "Net.Msgs.Alliance.AllianceRewardHideNameMessage",
	[MsgDefines.AllianceSearchUser] = "Net.Msgs.Alliance.AllianceSearchUserMessage",
	[MsgDefines.AllianceSetRank] = "Net.Msgs.Alliance.AllianceSetRankMessage",
	[MsgDefines.AllianceShowHelp] = "Net.Msgs.Alliance.AllianceShowHelpMessage",
	[MsgDefines.AllianceWarCancel] = "Net.Msgs.Alliance.AllianceWarCancelMessage",
	[MsgDefines.AllianceWarRetreat] = "Net.Msgs.Alliance.AllianceWarRetreatMessage",
	[MsgDefines.AllScienceRefresh] = "Net.Msgs.Alliance.AllScienceRefreshMessage",
	[MsgDefines.AllianceTeamDirectMove] = "Net.Msgs.Alliance.AllianceTeamDirectMoveMessage",
	[MsgDefines.AlName] = "Net.Msgs.Alliance.AlNameMessage",
	[MsgDefines.AlPointFind] = "Net.Msgs.Alliance.AlPointFindMessage",
	[MsgDefines.AlRank] = "Net.Msgs.Alliance.AlRankMessage",
	[MsgDefines.SetAllianceOfficialPos] = "Net.Msgs.Alliance.SetAllianceOfficialPosMessage",
	[MsgDefines.PushAllianceOfficialPosChange] = "Net.Msgs.Alliance.PushAllianceOfficialPosChangeMessage",
	[MsgDefines.AlScienceDonate] = "Net.Msgs.Alliance.AlScienceDonateMessage",
	[MsgDefines.AlScienceFresh] = "Net.Msgs.Alliance.AlScienceFreshMessage",
	[MsgDefines.AlScienceGoldDonate] = "Net.Msgs.Alliance.AlScienceGoldDonateMessage",
	[MsgDefines.AlScienceNumFresh] = "Net.Msgs.Alliance.AlScienceNumFreshMessage",
	[MsgDefines.AlScienceRecommend] = "Net.Msgs.Alliance.AlScienceRecommendMessage",
	[MsgDefines.AlScienceResearch] = "Net.Msgs.Alliance.AlScienceResearchMessage",
	[MsgDefines.GetAlMemberRecommendList] = "Net.Msgs.Alliance.GetAlMemberRecommendListMessage",
	[MsgDefines.AlScienceResearch] = "Net.Msgs.Alliance.AlScienceResearchMessage",
	[MsgDefines.AlSearch] = "Net.Msgs.Alliance.AlSearchMessage",
	[MsgDefines.AlShopBuyAl] = "Net.Msgs.Alliance.AlShopBuyAlMessage",
	[MsgDefines.AlShopBuyUsr] = "Net.Msgs.Alliance.AlShopBuyUsrMessage",
	[MsgDefines.AlShopShow] = "Net.Msgs.Alliance.AlShopShowMessage",
	[MsgDefines.GetAllianceWarList] = "Net.Msgs.Alliance.GetAllianceWarListMessage",
	[MsgDefines.PushAlGiftNum] = "Net.Msgs.Alliance.PushAlGiftNumMessage",
	[MsgDefines.PushAlHelpNew] = "Net.Msgs.Alliance.PushAlHelpNewMessage",
	[MsgDefines.PushAlHelpUpdate] = "Net.Msgs.Alliance.PushAlHelpUpdateMessage",
	[MsgDefines.PushAlApply] = "Net.Msgs.Alliance.PushAlApplyMessage",
	[MsgDefines.PushAlJoin] = "Net.Msgs.Alliance.PushAlJoinMessage",
	[MsgDefines.PushAllianceLeaderTrans] = "Net.Msgs.Alliance.PushAllianceLeaderTransMessage",
	[MsgDefines.PushAllianceLeave] = "Net.Msgs.Alliance.PushAllianceLeaveMessage",
	[MsgDefines.PushAllianceBaseInfo] = "Net.Msgs.Alliance.PushAllianceBaseInfoMessage",
	[MsgDefines.PushAllianceMarchCreate] = "Net.Msgs.Alliance.PushAllianceMarchCreateMessage",
	[MsgDefines.PushAllianceMarchRefresh] = "Net.Msgs.Alliance.PushAllianceMarchRefreshMessage",
	[MsgDefines.PushAllianceMarchRemove] = "Net.Msgs.Alliance.PushAllianceMarchRemoveMessage",
	[MsgDefines.PushAlScienceUpdate] = "Net.Msgs.Alliance.PushAlScienceUpdateMessage",
	[MsgDefines.PushAlScienceUpdate1] = "Net.Msgs.Alliance.PushAlScienceUpdateMessage1",
	[MsgDefines.PushUserAllianceTeamRetreat] = "Net.Msgs.Alliance.PushUserAllianceTeamRetreat",
	[MsgDefines.RefuseAllianceApply] = "Net.Msgs.Alliance.RefuseAllianceApplyMessage",
	[MsgDefines.DailyTaskReward] = "Net.Msgs.Alliance.AllianceDailyTaskRewardMessage",
	[MsgDefines.PushDailyQuest] = "Net.Msgs.Alliance.PushDailyQuestMessage",
	[MsgDefines.PushAllianceLogMember] = "Net.Msgs.Alliance.PushAllianceLogMemberMessage",
	[MsgDefines.ViewAllianceLog] = "Net.Msgs.Alliance.ViewAllianceLogMessage",
	---------------------------------------------------------------------------------

	--新英雄相关
	[MsgDefines.HeroAdvance] = "Net.Msgs.HeroAbout.HeroAdvanceMessage",
	[MsgDefines.HeroAdvanceMulti] = "Net.Msgs.HeroAbout.HeroAdvanceMultiMessage",
	[MsgDefines.HeroReset] = "Net.Msgs.HeroAbout.HeroResetMessage",
	[MsgDefines.HeroLvUp] = "Net.Msgs.HeroAbout.HeroLvUpMessage",
	[MsgDefines.HeroLvBeyond] = "Net.Msgs.HeroAbout.HeroLvBeyondMessage",
	[MsgDefines.HeroRankUpgrade] = "Net.Msgs.HeroAbout.HeroRankUpgradeMessage",
	[MsgDefines.PushHeroLottery] = "Net.Msgs.HeroAbout.PushHeroLotteryMessage",
	[MsgDefines.PushHeroLotterySwitch] = "Net.Msgs.HeroAbout.PushHeroSwitchMessage",
	[MsgDefines.LotteryHeroCard] = "Net.Msgs.HeroAbout.LotteryHeroCardMessage",
	[MsgDefines.LotteryHeroSwitch] = "Net.Msgs.HeroAbout.LotteryHeroSwitchMessage",
	[MsgDefines.HeroSkillUpgrade] = "Net.Msgs.HeroAbout.HeroSkillUpgradeMessage",
	[MsgDefines.HeroMedalExchange] = "Net.Msgs.HeroAbout.HeroMedalExchangeMessage",
	[MsgDefines.HeroExchange] = "Net.Msgs.HeroAbout.HeroExchangeMessage",
	[MsgDefines.GetHeroLotteryInfo] = "Net.Msgs.HeroAbout.GetHeroLotteryInfoMessage",
	
	[MsgDefines.ClaimAlContributeBoxReward] = "Net.Msgs.Activity.AlContribute.ClaimAlContributeBoxRewardMessage",
	[MsgDefines.GetAlContributeRankList] = "Net.Msgs.Activity.AlContribute.GetAlContributeRankListMessage",
	[MsgDefines.GetAlContributeExploitReward] = "Net.Msgs.Activity.AlContribute.GetAlContributeExploitRewardMessage",
	[MsgDefines.AlContributeUpdateSelfExploit] = "Net.Msgs.Activity.AlContribute.AlContributeUpdateSelfExploitMessage",

	[MsgDefines.StrongestCommandTotalRank] = "Net.Msgs.StrongestCommandTotalRankMessage",
	[MsgDefines.StrongestCommandGetTodayReward] = "Net.Msgs.StrongestCommandGetTodayRewardMessage",

	[MsgDefines.HeroTalentPageReset] = "Net.Msgs.HeroTalentPageResetMessage",
	[MsgDefines.HeroTalentPageRename] = "Net.Msgs.HeroTalentPageRenameMessage",
	[MsgDefines.HeroTalentPageSwitch] = "Net.Msgs.HeroTalentPageSwitchMessage",
	[MsgDefines.HeroAddTalent] = "Net.Msgs.HeroAddTalentMessage",
	[MsgDefines.PushEditHero] = "Net.Msgs.PushEditHeroMessage",

	[MsgDefines.UserSyntheticHero] = "Net.Msgs.UserSyntheticHeroMessage",
	[MsgDefines.FreeBuildingFoldUpNew] = "Net.Msgs.FreeBuildingFoldUpNewMessage",
	[MsgDefines.PushDefendFormationUpdateNew] = "Net.Msgs.PushDefendFormationUpdateNewMessage",
	[MsgDefines.DefenseInfoSave] = "Net.Msgs.DefenseInfoSaveMessage",
	[MsgDefines.PushArmyReturn] = "Net.Msgs.PushArmyReturnMessage",

	--Vip相关
	[MsgDefines.VipInfo] = "Net.Msgs.Vip.VipInfoMessage",
	[MsgDefines.PushVipInfo] = "Net.Msgs.Vip.PushVipInfoMessage",
	[MsgDefines.VipGetRewardInfo] = "Net.Msgs.Vip.VipGetRewardInfoMessage",
	[MsgDefines.VipAddLoginScore] = "Net.Msgs.Vip.VipAddLoginScoreMessage",
	[MsgDefines.VipGetEveryDayReward] = "Net.Msgs.Vip.VipGetEveryDayRewardMessage",


	---- 邮件系统相关
	[MsgDefines.MailGet] = "Net.Msgs.Mail.MailGetMessage",
	[MsgDefines.MailGetShare] = "Net.Msgs.MailGetShareMessage",
	[MsgDefines.MailGetMuti] = "Net.Msgs.Mail.MailGetMutiMessage",
	[MsgDefines.PushMail] = "Net.Msgs.Mail.PushMailMessage",
	[MsgDefines.MailReadStatus] = "Net.Msgs.Mail.MailReadStatusMessage",
	[MsgDefines.MailReadStatusBatch] = "Net.Msgs.Mail.MailReadStatusBatchMessage",
	[MsgDefines.MailDelete] = "Net.Msgs.Mail.MailDeleteMessage",
	[MsgDefines.MailBatchDel] = "Net.Msgs.Mail.MailBatchDelMessage",
	[MsgDefines.MailReward] = "Net.Msgs.Mail.MailRewardMessage",
	[MsgDefines.MailRewardBatch] = "Net.Msgs.Mail.MailRewardBatchMessage",
	[MsgDefines.MailAddFavor] = "Net.Msgs.Mail.MailAddFavorMessage",
	[MsgDefines.MailCancelFavor] = "Net.Msgs.Mail.MailCancelFavorMessage",
	[MsgDefines.MailGetFightReportDetail] = "Net.Msgs.Mail.MailGetReportDetailMessage",
	[MsgDefines.MailSend] = "Net.Msgs.Mail.MailSendMessage",

	-----------------------------------------------------------------------------

	[MsgDefines.FreeBuildingUpNew] = "Net.Msgs.FreeBuildingUpNewMessage",
	[MsgDefines.FreeBuildingExpendDome] = "Net.Msgs.FreeBuildingExpendDomeMessage",

	[MsgDefines.PushInitBuild] = "Net.Msgs.PushInitBuildMessage",

	[MsgDefines.PushBuildUpgradeFinish] = "Net.Msgs.PushBuildUpgradeFinishMessage",
	[MsgDefines.PushQueueAdd] = "Net.Msgs.PushQueueAddMessage",
	[MsgDefines.PushQueueUpdate] = "Net.Msgs.PushQueueUpdateMessage",
	[MsgDefines.PushHeroData] = "Net.Msgs.PushHeroDataMessage",
	[MsgDefines.PushArmyInfo] = "Net.Msgs.PushArmyInfoMessage",
	[MsgDefines.PushCommonNotice] = "Net.Msgs.PushCommonNotice",
	[MsgDefines.PushBuildingInfo] = "Net.Msgs.PushBuildingInfoMessage",
	[MsgDefines.PushAddBuilding] = "Net.Msgs.PushAddBuildingMessage",
	[MsgDefines.UserResupplyBuilding] = "Net.Msgs.UserResupplyBuildingMessage",
	[MsgDefines.UserResSynNew] = "Net.Msgs.UserResSynNewMessage",
	[MsgDefines.PlayerMonthPayInfo] = "Net.Msgs.PlayerMonthPayInfoMessage",
	[MsgDefines.ClientNotifySetting] = "Net.Msgs.ClientNotifySetting",
	[MsgDefines.PushPlayerInfo] = "Net.Msgs.PushPlayerInfoMessage",
	[MsgDefines.CrossServerList] = "Net.Msgs.CrossServerListMessage",
	[MsgDefines.CityDefenceAdd] = "Net.Msgs.CityDefenceAddMessage",
	[MsgDefines.PushUserDefenceChange] = "Net.Msgs.PushUserDefenceChangeMessage",
	[MsgDefines.PushDefenceWallUpdate] = "Net.Msgs.PushDefenceWallUpdateMessage",
	[MsgDefines.PushResourceInfo] = "Net.Msgs.PushResourceInfo",
	[MsgDefines.UserChangePic]= "Net.Msgs.UserChangePicMessage",
	[MsgDefines.AllianceAssistanceInfo] = "Net.Msgs.AllianceAssistanceInfoMessage",
	[MsgDefines.AssistanceTeamRetreat] = "Net.Msgs.AssistanceTeamRetreatMessage",
	[MsgDefines.WorldMv]= "Net.Msgs.WorldMvMessage",
	[MsgDefines.WorldAlMove] = "Net.Msgs.WorldAlMoveMessage",
	[MsgDefines.AlMoveInviteGetPoints] = "Net.Msgs.AlMoveInviteGetPointsMessage",
	[MsgDefines.PushAlLeaderPointChange] = "Net.Msgs.PushAlLeaderPointChangeMessage",
	[MsgDefines.PushItemDel]= "Net.Msgs.PushItemDelMessage",
	[MsgDefines.PushFormationStaminaUpdate] = "Net.Msgs.PushFormationStaminaUpdateMessage",
	[MsgDefines.PushFormationStatusAdd] = "Net.Msgs.PushFormationStatusAddMessage",
	[MsgDefines.PushFormationStatusDel] = "Net.Msgs.PushFormationStatusDelMessage",
	[MsgDefines.PushBuildingStatusAdd] = "Net.Msgs.PushBuildingStatusAddMessage",
	[MsgDefines.PushBuildingStatusDel] = "Net.Msgs.PushBuildingStatusDelMessage",
	[MsgDefines.ReceiveBuildingGrowValReward]= "Net.Msgs.ReceiveBuildingGrowValRewardMessage",
	[MsgDefines.GetRankPreviewMessage]="Net.Msgs.GetRankPreviewMessage",
	[MsgDefines.GetRank]="Net.Msgs.GetRankMessage",
	[MsgDefines.GetAllianceSeasonScoreRank]="Net.Msgs.GetAllianceSeasonScoreRankMessage",
	[MsgDefines.GetAllianceSeasonScoreRankReward] = "Net.Msgs.GetAllianceSeasonScoreRankRewardMessage",
	[MsgDefines.UserRecoverBuildingStamina] = "Net.Msgs.UserRecoverBuildingStaminaMessage",
	[MsgDefines.PushUserBuildStaminaChange] = "Net.Msgs.PushUserBuildStaminaChangeMessage",
	[MsgDefines.UnlockBuildingQueue] = "Net.Msgs.UnlockBuildingQueueMessage",
	[MsgDefines.PushBuildUnlockAdd] =  "Net.Msgs.PushBuildUnlockAddMessage",
	[MsgDefines.DetectInfoGet] = "Net.Msgs.RadarCenter.DetectInfoGetMessage",
	[MsgDefines.DetectPowerUpgrade] = "Net.Msgs.RadarCenter.DetectPowerUpgradeMessage",
	[MsgDefines.DetectEventRewardReceive] = "Net.Msgs.RadarCenter.DetectEventRewardReceiveMessage",
	[MsgDefines.DetectEventCompletePush] = "Net.Msgs.RadarCenter.DetectEventCompletePushMessage",
	[MsgDefines.ResetDetectEvent] = "Net.Msgs.RadarCenter.ResetDetectEventMessage",
	[MsgDefines.PushDetectEvent] = "Net.Msgs.RadarCenter.PushDetectEventMessage",
	[MsgDefines.PushWorldMove] = "Net.Msgs.PushWorldMoveMessage",
	[MsgDefines.StatTT] = "Net.Msgs.StatTTMessage",
	[MsgDefines.SaveGuide] = "Net.Msgs.SaveGuideMessage",
	[MsgDefines.PushPickGarbageReward] = "Net.Msgs.PushPickGarbageRewardMessage",
	[MsgDefines.ChangeMoodStr] ="Net.Msgs.ChangeModStrMessage",
	[MsgDefines.FreeBuildingUpgradeFinish] ="Net.Msgs.FreeBuildingUpgradeFinishMessage",
	[MsgDefines.MoveCityToWorld] ="Net.Msgs.MoveCityToWorldMessage",
	[MsgDefines.PushServerToStop] = "Net.Msgs.PushServerToStopMessage",
	[MsgDefines.LoginInitCommand] = "Net.Msgs.LoginInitCommand",
	[MsgDefines.FreeBuildingPlaceMainBuilding] = "Net.Msgs.FreeBuildingPlaceMainBuildingMessage",
	[MsgDefines.FirstPayRewardStatePush] = "Net.Msgs.FirstPayRewardStatePushMessage",
	[MsgDefines.ClaimFirstPayReward] = "Net.Msgs.FirstPayClaimRewardMessage",
	[MsgDefines.DefenceFailPush] = "Net.Msgs.DefenceFailPushMessage",
	[MsgDefines.GarbageRewardInfo] = "Net.Msgs.GarbageRewardInfoMessage",
	[MsgDefines.FreeSpeedQueue] = "Net.Msgs.FreeSpeedQueueMessage",
	[MsgDefines.ReportChat] = "Net.Msgs.ChatReportMessage",
	[MsgDefines.ChatRoomCreate] = "Net.Msgs.ChatRoomCreateMessage",
	[MsgDefines.ChatRoomDismiss] = "Net.Msgs.ChatRoomDismissMessage",

	[MsgDefines.PushEffectChange] = "Net.Msgs.PushEffectChangeMessage",
	[MsgDefines.PushBatchEffectChange] = "Net.Msgs.PushBatchEffectChangeMessage",
	[MsgDefines.PushStatus] = "Net.Msgs.PushStatusMessage",
	[MsgDefines.FindMainBuildInitPosition] = "Net.Msgs.FindMainBuildInitPositionMessage",
	[MsgDefines.FreeBuildingPlaceNew] = "Net.Msgs.FreeBuildingPlaceNewMessage",
	[MsgDefines.FreeBuildingReplaceNew] = "Net.Msgs.FreeBuildingReplaceNewMessage",
	[MsgDefines.BuildWorldMoveNew] = "Net.Msgs.BuildWorldMoveNewMessage",
	[MsgDefines.PushMonthCard] = "Net.Msgs.PushMonthCardMessage",
	[MsgDefines.PushCollectExtraReward] = "Net.Msgs.PushCollectExtraRewardMessage",
	[MsgDefines.ClaimGolloesDailyReward] = "Net.Msgs.ClaimGolloesDailyRewardMessage",
	[MsgDefines.ClaimGolloesFreeReward] = "Net.Msgs.ClaimGolloesFreeRewardMessage",
	[MsgDefines.ClaimGolloesReward] = "Net.Msgs.ClaimGolloesRewardMessage",
	[MsgDefines.GetCommonShopInfo] = "Net.Msgs.GetCommonShopInfoMessage",
	[MsgDefines.BuyCommonShopGoods] = "Net.Msgs.BuyCommonShopGoodsMessage",
	[MsgDefines.RefreshCommonShop] = "Net.Msgs.RefreshCommonShopMessage",
	[MsgDefines.GolloesTradeCheckTarget] = "Net.Msgs.GolloesTradeCheckTargetMessage",
	[MsgDefines.GetGolloesCaravanRecord] = "Net.Msgs.GetGolloesCaravanRecordMessage",
	[MsgDefines.ActiveGolloesFunc] = "Net.Msgs.ActiveGolloesFuncMessage",
	[MsgDefines.PushGolloesData] = "Net.Msgs.PushGolloesDataChangeMessage",
	[MsgDefines.PushAllianceCityDefendChange] = "Net.Msgs.PushAllianceCityDefendChangeMessage",
	[MsgDefines.WorldGetAllianceCityDetail] = "Net.Msgs.WorldGetAllianceCityDetailMessage",
	[MsgDefines.GetPaidLotteryData] = "Net.Msgs.GiftPackage.GetPaidLotteryDataMessage",
	[MsgDefines.ClaimPaidLotteryTicket] = "Net.Msgs.GiftPackage.ClaimPaidLotteryTicketMessage",
	[MsgDefines.BeginPaidLotteryRoll] = "Net.Msgs.GiftPackage.BeginPaidLotteryRollMessage",
	[MsgDefines.PushPaidLotteryScoreChange] = "Net.Msgs.GiftPackage.PushPaidLotteryScoreChangeMessage",
	[MsgDefines.GetAllianceTaskInfo] = "Net.Msgs.GetAllianceTaskInfoMessage",
	[MsgDefines.ClaimAllianceTaskReward] = "Net.Msgs.ClaimAllianceTaskRewardMessage",
	[MsgDefines.SendAllianceRecruit] = "Net.Msgs.SendAllianceRecruitMessage",
	[MsgDefines.StartAllianceAutoRally] = "Net.Msgs.Alliance.StartAllianceAutoRallyMessage",
	[MsgDefines.StopAllianceAutoRally] = "Net.Msgs.Alliance.StopAllianceAutoRallyMessage",
	[MsgDefines.GetAllianceAutoJoinRallyInfo] = "Net.Msgs.Alliance.GetAllianceAutoRallyInfoMessage",
	[MsgDefines.PushAllNotice] = "Net.Msgs.PushAllNoticeMessage",
	[MsgDefines.GetWorldCityInfo] ="Net.Msgs.GetWorldCityInfoMessage",
	[MsgDefines.PushRobotEffectChange] = "Net.Msgs.PushRobotEffectChangeMessage",
	[MsgDefines.UserRobotOccupy] = "Net.Msgs.UserRobotOccupyMessage",
	[MsgDefines.UserRobotDismiss] = "Net.Msgs.UserRobotDismissMessage",
	[MsgDefines.PushUserCollectRewardCreate] = "Net.Msgs.PushUserCollectRewardCreateMessage",
	[MsgDefines.PushUserCollectRewardRemove] = "Net.Msgs.PushUserCollectRewardRemoveMessage",
	[MsgDefines.GatherCollectReward] = "Net.Msgs.GatherCollectRewardMessage",
	[MsgDefines.GetAllAlCityInfo] = "Net.Msgs.GetAllAlCityInfoMessage",
	[MsgDefines.GiveUpAlCity] = "Net.Msgs.GiveUpAlCityMessage",
	[MsgDefines.PushGiveUpAlCity] = "Net.Msgs.PushGiveUpAlCityMessage",
	[MsgDefines.PushGiveUpAlCityFail] = "Net.Msgs.PushGiveUpAlCityFailMessage",
	[MsgDefines.PushAlCityInfoUpdate] = "Net.Msgs.PushAlCityInfoUpdateMessage",
	[MsgDefines.GetArenaInfo] = "Net.Msgs.GetArenaInfoMessage",
	[MsgDefines.GetArenaBattleHistory] = "Net.Msgs.GetArenaBattleHistoryMessage",
	[MsgDefines.GetArenaUserEffect] = "Net.Msgs.GetArenaUserEffectMessage",
	[MsgDefines.SetArenaDefenseArmy] = "Net.Msgs.SetArenaDefenseArmyMessage",
	[MsgDefines.BuyArenaTicket] = "Net.Msgs.BuyArenaTicketMessage",
	[MsgDefines.StartArenaBattle] = "Net.Msgs.StartArenaBattleMessage",
	[MsgDefines.PushArenaHistoryTime] = "Net.Msgs.PushArenaHistoryTimeMessage",
	
	[MsgDefines.GetAllAllianceMineList] = "Net.Msgs.AllianceMine.GetAllAllianceMineListMessage",
	[MsgDefines.BuildAllianceMine] = "Net.Msgs.AllianceMine.BuildAllianceMineMessage",
	[MsgDefines.PushAllianceMineAdd] = "Net.Msgs.AllianceMine.PushAllianceMineAddMessage",
	[MsgDefines.PushAllianceMineDel] = "Net.Msgs.AllianceMine.PushAllianceMineDelMessage",
	[MsgDefines.GetAllMarchesOfAlMine] = "Net.Msgs.AllianceMine.GetAllMarchesOfAlMineMessage",
	[MsgDefines.PushAlMineScoreChange] = "Net.Msgs.AllianceMine.PushAlMineScoreChangeMessage",

	[MsgDefines.PushBuildFoldUp] = "Net.Msgs.PushBuildFoldUpMessage",
	[MsgDefines.WorldGetAllianceCityEffect] = "Net.Msgs.WorldGetAllianceCityEffectMessage",
	[MsgDefines.PushDragonServerEffectUpdate] = "Net.Msgs.PushDragonServerEffectUpdateMessage",
	[MsgDefines.GetDragonSeverEffect] = "Net.Msgs.GetDragonSeverEffectMessage",
	[MsgDefines.PushAllianceJoin] = "Net.Msgs.PushAllianceJoinMessage",
	[MsgDefines.PushAllianceGiftCd] = "Net.Msgs.PushAllianceGiftCdMessage",
	[MsgDefines.PushAllianceSign] = "Net.Msgs.PushAllianceSignMessage",
	[MsgDefines.PushUserRewardGet] = "Net.Msgs.PushUserRewardGetMessage",
	
	[MsgDefines.ShareCdCheck] = "Net.Msgs.ShareCDCheckMessage",
	[MsgDefines.PushUserRewardControl] = "Net.Msgs.PushUserRewardControlMessage",
	-- 英雄驻扎
	[MsgDefines.HeroStationSaveMessage] = "Net.Msgs.HeroStationSaveMessage",
	[MsgDefines.HeroStationUpdateMessage] = "Net.Msgs.HeroStationUpdateMessage",
	[MsgDefines.HeroStationUseSkillMessage] = "Net.Msgs.HeroStationUseSkillMessage",
	[MsgDefines.PushModifyPicAuthority] = "Net.Msgs.PushModifyPicAuthorityMessage",
	[MsgDefines.WorldChangeAllianceCityName] = "Net.Msgs.WorldChangeAllianceCityNameMessage",
	[MsgDefines.WorldCheckAllianceCityName] = "Net.Msgs.WorldCheckAllianceCityNameMessage",

	[MsgDefines.RadarRallyGetBossCount] = "Net.Msgs.RadarRallyGetBossCountMessage",

	[MsgDefines.PushDailyKillBossNumber] = "Net.Msgs.PushDailyKillBossNumberMessage",
	[MsgDefines.FiveStar] = "Net.Msgs.FiveStarMessage",

	--冠军对决
	[MsgDefines.ACT_CHAMPIONBATTLE_REDPOINT_PUSH] =  "Net.Msgs.ChampionBattleActivity.PushChampionBattleRedPointMessage",          --冠军对决入口红点推送显示协议
	[MsgDefines.ACT_CHAMPIONBATTLE_DATA_REFRESH_PUSH] = "Net.Msgs.ChampionBattleActivity.PushChampionBattleDataRefreshMessage", --冠军对决总数据推送

	[MsgDefines.ACT_CHAMPIONBATTLE_DATA_REFRESH] = "Net.Msgs.ChampionBattleActivity.ActChampBattleDataRefreshMessage",           --冠军对决总数据

	[MsgDefines.ACT_CHAMPIONBATTLE_REWARD_VIEW] = "Net.Msgs.ChampionBattleActivity.ActChampBattleRewardPreviewMessage",             --冠军对决奖励预览
	[MsgDefines.ACT_CHAMPIONBATTLE_REWARD] = "Net.Msgs.ChampionBattleActivity.ActChampionBattleRewardMessage",                       --冠军对决领取宝箱请求  
	[MsgDefines.ACT_CHAMPIONBATTLE_SINGUP] = "Net.Msgs.ChampionBattleActivity.ActChampionBattleSingUpMessage",                       --冠军对决请求报名

	[MsgDefines.ACT_CHAMPIONBATTLE_REPORT_LIST] = "Net.Msgs.ChampionBattleActivity.ActChampionBattleReportListMessage",              --冠军对决战报列表
	[MsgDefines.ACT_CHAMPIONBATTLE_REPORT_DESC] = "Net.Msgs.ChampionBattleActivity.ActChampionBattleReportDescMessage",               --冠军对决战报详细信息
	[MsgDefines.ACT_CHAMPIONSTRONGEST_REPORT_LIST] = "Net.Msgs.ChampionBattleActivity.ActChampionStrongestReportListMessage",      --冠军对决八強賽\四強賽\半決賽战报列表

	[MsgDefines.ACT_CHAMPIONBATTLE_BET_VIEW] = "Net.Msgs.ChampionBattleActivity.ChampionBattleBetViewMessage",               --冠军对决-押注数据请求
	[MsgDefines.ACT_CHAMPIONBATTLE_BET] = "Net.Msgs.ChampionBattleActivity.ChampionBattleBetMessage",                        --冠军对决-下注请求
	[MsgDefines.ACT_CHAMPIONBATTLE_BET_RECORD] = "Net.Msgs.ChampionBattleActivity.ChampionBattleBetRecordMessage",           --冠军对决-押注记录
	[MsgDefines.ACT_CHAMPIONBATTLE_SAVE_FORMATION] = "Net.Msgs.ChampionBattleActivity.ChampionBattleSaveFormationMessage",	 --冠军对决-保存队列
	[MsgDefines.ACT_CHAMPIONBATTLE_SAVE_FORMATION_PUSH] = "Net.Msgs.ChampionBattleActivity.ChampionBattleSaveFormationPushMessage",	 --冠军对决-队列push
	[MsgDefines.ACT_CHAMPIONBATTLE_GET_RANK_DATA] = "Net.Msgs.ChampionBattleActivity.ChampionBattleGetRankDataMessage",	 --冠军对决-队列push
	[MsgDefines.ACT_CHAMPIONBATTLE_GET_GROUP_DATA] = "Net.Msgs.ChampionBattleActivity.ChampionBattleGetGroupDataMessage",
	[MsgDefines.FindResourcePoint] = "Net.Msgs.FindResourcePointMessage",

	[MsgDefines.ServerTrendsInfo] = "Net.Msgs.WorldTrend.ServerTrendsInfoMessage",
	[MsgDefines.ServerTrendsReward] = "Net.Msgs.WorldTrend.ServerTrendsRewardMessage",
	[MsgDefines.PushTrendsRedNum] = "Net.Msgs.WorldTrend.PushTrendsRedNumMessage",
	[MsgDefines.ServerTrendsRank] = "Net.Msgs.WorldTrend.ServerTrendsRankMessage",

	[MsgDefines.PiggyBankUpdate] = "Net.Msgs.PiggyBankUpdateMessage",
	[MsgDefines.PushActScoreObtain] = "Net.Msgs.PushActScoreObtainMessage",

	[MsgDefines.GrowthPlanGetInfo] = "Net.Msgs.GrowthPlanGetInfoMessage",
	[MsgDefines.GrowthPlanGetReward] = "Net.Msgs.GrowthPlanGetRewardMessage",
	[MsgDefines.UserStartFixBuilding] = "Net.Msgs.UserStartFixBuildingMessage",
	[MsgDefines.UserFinishFixBuilding] = "Net.Msgs.UserFinishFixBuildingMessage",
	[MsgDefines.BuyFreeWeeklyPackage] = "Net.Msgs.BuyFreeWeeklyPackageMessage",
	
	[MsgDefines.GetWeekCardList] = "Net.Msgs.GiftPackage.GetWeekCardListMessage",
	[MsgDefines.ClaimWeekCardReward] = "Net.Msgs.GiftPackage.ClaimWeekCardRewardMessage",
	[MsgDefines.PushWeekCardInfoChange] = "Net.Msgs.GiftPackage.PushWeekCardInfoChangeMessage",
	[MsgDefines.ClaimWeekCardFreeReward] = "Net.Msgs.GiftPackage.ClaimWeekCardFreeRewardMessage",
	[MsgDefines.SetWeekCardCustomRewards] = "Net.Msgs.GiftPackage.SetWeekCardCustomRewardsMessage",

	[MsgDefines.GetRedPack] = "Net.Msgs.RedPacket.GetRedPackMessage",
	[MsgDefines.PushPrePareRedPacket] = "Net.Msgs.RedPacket.PushPrePareRedPacketMessage",
	[MsgDefines.PushNewSysRedPacket] = "Net.Msgs.RedPacket.PushNewSysRedPacketMessage",
	[MsgDefines.SendRedPack] = "Net.Msgs.RedPacket.SendRedPackMessage",
	[MsgDefines.RedPacketsRvdId] = "Net.Msgs.RedPacket.RedPacketsRvdIdMessage",
	[MsgDefines.GetAllianceRedPacket] = "Net.Msgs.RedPacket.GetAllianceRedPacketMessage",
	[MsgDefines.RedPacketStatus] = "Net.Msgs.RedPacket.RedPacketStatusMessage",

	[MsgDefines.FindEnemyPoint] = "Net.Msgs.FindEnemyPointMessage",

	[MsgDefines.GarageRefit] = "Net.Msgs.GarageRefitMessage",
	[MsgDefines.GarageRefitUpdate] = "Net.Msgs.GarageRefitUpdateMessage",

	[MsgDefines.GetUserGuardArmy] = "Net.Msgs.GetUserGuardArmyMessage",
	[MsgDefines.SetAllianceCareerPos] = "Net.Msgs.Alliance.SetAllianceCareerPosMessage",

	[MsgDefines.GetWorldNewInfo] = "Net.Msgs.GetWorldNewInfoMessage",
	[MsgDefines.PushBuildDelete] = "Net.Msgs.PushBuildDeleteMessage",
	[MsgDefines.PushQueueDelete] = "Net.Msgs.PushQueueDeleteMessage",
	[MsgDefines.LeaveWorld] = "Net.Msgs.LeaveWorldMessage",
	[MsgDefines.UserGetPVEStage] = "Net.Msgs.UserGetPVEStageMessage",
	[MsgDefines.UserFinishPVETrigger] = "Net.Msgs.UserFinishPVETriggerMessage",
	[MsgDefines.UserFinishPVELevel] = "Net.Msgs.UserFinishPVELevelMessage",
	[MsgDefines.UserStartPVELevel] = "Net.Msgs.UserStartPVELevelMessage",
	[MsgDefines.UserResetPVEHero] = "Net.Msgs.UserResetPVEHeroMessage",
	[MsgDefines.UserStartPVETest] = "Net.Msgs.UserStartPVETestMessage",

	[MsgDefines.GetAllianceAlertInfo] = "Net.Msgs.Alliance.GetAllianceAlertInfoMessage",
	[MsgDefines.GetAllianceAlertMarch] = "Net.Msgs.Alliance.GetAllianceAlertMarchMessage",
	[MsgDefines.PushAllianceAlertInfoCreate] = "Net.Msgs.Alliance.PushAllianceAlertInfoCreateMessage",
	[MsgDefines.PushAllianceAlertInfoRemove] = "Net.Msgs.Alliance.PushAllianceAlertInfoRemoveMessage",

	[MsgDefines.GetBindMailReward] = "Net.Msgs.Account.GetBindMailRewardMessage",

	[MsgDefines.GetUserFightPve] = "Net.Msgs.PveModule.PveBattleMessage",
	[MsgDefines.BeginPvpCaveFight] = "Net.Msgs.PveModule.PveCaveBattleMessage",
	[MsgDefines.PveDiffFight] = "Net.Msgs.PveModule.PveDiffFightMessage",
	[MsgDefines.SelectPveBuff] = "Net.Msgs.PveModule.SelectPveBuffMessage",
	[MsgDefines.ChoosePveBuff] = "Net.Msgs.PveModule.ChoosePveBuffMessage",

	[MsgDefines.GetHeroMonthCardInfo] = "Net.Msgs.GetHeroMonthCardInfoMessage",
	[MsgDefines.GetHeroMonthCardReward] = "Net.Msgs.GetHeroMonthCardRewardMessage",
	[MsgDefines.GetHeroMonthCardAllReward] = "Net.Msgs.GetHeroMonthCardAllRewardMessage",
	[MsgDefines.BuyHeroMonthCardPush] = "Net.Msgs.PushBuyHeroMonthCardMessage",

	[MsgDefines.PushActBossTransUpdate] = "Net.Msgs.PushActBossTransUpdateMessage",
	[MsgDefines.UserGetActBossRank] = "Net.Msgs.UserGetActBossRankMessage",
	[MsgDefines.UserGetActBossMarch] = "Net.Msgs.UserGetActBossMarchMessage",
	[MsgDefines.FinishSampling] = "Net.Msgs.RadarCenter.FinishSamplingMessage",
	[MsgDefines.StartDetectEventPve] = "Net.Msgs.RadarCenter.StartDetectEventPveMessage",
	[MsgDefines.FinishDetectEventPve] = "Net.Msgs.RadarCenter.FinishDetectEventPveMessage",
	[MsgDefines.StartPickGarbage] = "Net.Msgs.RadarCenter.StartPickGarbageMessage",
	[MsgDefines.FindMonsterBoss] = "Net.Msgs.RadarCenter.FindMonsterBossMessage",
	[MsgDefines.FinishTalkDetectEvent] = "Net.Msgs.RadarCenter.FinishTalkDetectEventMessage",

	[MsgDefines.GetRechargeInfo] = "Net.Msgs.CumulativeRecharge.GetRechargeInfoMessage",
	[MsgDefines.ReceiveRechargeReward] = "Net.Msgs.CumulativeRecharge.ReceiveRechargeRewardMessage",
	[MsgDefines.PushRechargeScore] = "Net.Msgs.CumulativeRecharge.PushRechargeScoreMessage",
	[MsgDefines.PushNewRecharge] = "Net.Msgs.CumulativeRecharge.PushNewRechargeMessage",

	[MsgDefines.AllianceDeclareWarCreate] = "Net.Msgs.Alliance.AllianceDeclareWarCreateMessage",
	[MsgDefines.AllianceDeclareWarGet] = "Net.Msgs.Alliance.AllianceDeclareWarGetMessage",
	[MsgDefines.AllianceDeclareWarCancel] = "Net.Msgs.Alliance.AllianceDeclareWarCancelMessage",
	[MsgDefines.PushNewAllianceDeclareWar] = "Net.Msgs.Alliance.PushNewAllianceDeclareWarMessage",
	[MsgDefines.AllianceGetCityDeclareTimes] = "Net.Msgs.Alliance.AllianceGetCityDeclareTimesMessage",

	[MsgDefines.PushHeroLevelUp] =  "Net.Msgs.PushHeroLevelUpMessage",

	[MsgDefines.GetLuckyRollInfo] = "Net.Msgs.Activity.GetLuckyRollInfoMessage",
	[MsgDefines.LuckyRollChooseItem] = "Net.Msgs.Activity.LuckyRollChooseItemMessage",
	[MsgDefines.LuckyRollLottery] = "Net.Msgs.Activity.LuckyRollLotteryMessage",
	[MsgDefines.ReceiveLuckyRollStageReward] = "Net.Msgs.Activity.ReceiveLuckyRollStageRewardMessage",
	[MsgDefines.GetLuckRollRank] = "Net.Msgs.Activity.GetLuckRollRankMessage",
	[MsgDefines.UserRecoverPlayerStamina] = "Net.Msgs.UserRecoverPlayerStaminaMessage",
	
	[MsgDefines.BuyItemAndResource] = "Net.Msgs.BuyItemAndResourceMessage",

	[MsgDefines.UseHeroEffectSkill] = "Net.Msgs.UseHeroEffectSkillMessage",
	[MsgDefines.PayForHeroEntrust] = "Net.Msgs.PayForHeroEntrustMessage",
	[MsgDefines.PushNewEntrust] = "Net.Msgs.PushNewEntrustMessage",
	[MsgDefines.UserChatStat] = "Net.Msgs.UserChatStatMessage",

	[MsgDefines.FirstJoinAlliance] = "Net.Msgs.FirstJoinAllianceMessage",
	[MsgDefines.UserGetArenaReport] = "Net.Msgs.UserGetArenaReportMessage",
	[MsgDefines.UserGetMineCaveReport] = "Net.Msgs.UserGetMineCaveReportMessage",
	
	[MsgDefines.GetBattlePassInfo] = "Net.Msgs.Activity.BattlePass.GetBattlePassInfoMessage",
	[MsgDefines.ReceiveBattlePassTaskReward] = "Net.Msgs.Activity.BattlePass.ReceiveBattlePassTaskRewardMessage",
	[MsgDefines.ReceiveBattlePassStageReward] = "Net.Msgs.Activity.BattlePass.ReceiveBattlePassStageRewardMessage",
	[MsgDefines.ReceiveBattlePassExtraReward] = "Net.Msgs.Activity.BattlePass.ReceiveBattlePassExtraRewardMessage",
	[MsgDefines.ReceiveBattlePassAllReward] = "Net.Msgs.Activity.BattlePass.ReceiveBattlePassAllRewardMessage",
	[MsgDefines.BuyBattlePassLevel] = "Net.Msgs.Activity.BattlePass.BuyBattlePassLevelMessage",
	[MsgDefines.PushBattlePassUpdate] = "Net.Msgs.Activity.BattlePass.PushBattlePassUpdateMessage",
	[MsgDefines.PushBattlePassTaskUpdate] = "Net.Msgs.Activity.BattlePass.PushBattlePassTaskUpdateMessage",
	[MsgDefines.PushAllBattlePassTask] = "Net.Msgs.Activity.BattlePass.PushAllBattlePassTaskMessage",

	[MsgDefines.ChooseBaseTalent] = "Net.Msgs.TalentChooseMessage",
	[MsgDefines.ResetBaseTalent] = "Net.Msgs.TalentResetMessage",
	[MsgDefines.PushBaseTalent] = "Net.Msgs.TalentPush",
	[MsgDefines.RefreshBaseTalent] = "Net.Msgs.RefreshBaseTalentMessage",

	[MsgDefines.SetHeroOfficial] = "Net.Msgs.SetHeroOfficialMessage",
	[MsgDefines.HeroIntensify] = "Net.Msgs.HeroIntensifyMessage",
	[MsgDefines.HeroIntensifyRandomEffect] = "Net.Msgs.HeroIntensifyRandomEffectMessage",
	[MsgDefines.UserGetQuestionnaireList] = "Net.Msgs.UserGetQuestionnaireListMessage",
	[MsgDefines.PushUserQuestionnaire] = "Net.Msgs.PushUserQuestionnaireMessage",
	[MsgDefines.UserGetServerEffect] = "Net.Msgs.UserGetServerEffectMessage",
	[MsgDefines.PushUserGMOff] = "Net.Msgs.PushUserGMOffMessage",
	[MsgDefines.GetHeroBountyInfo] = "Net.Msgs.GetHeroBountyInfoMessage",
	[MsgDefines.StartHeroBountyTask] = "Net.Msgs.StartHeroBountyTaskMessage",
	[MsgDefines.ReceiveHeroBountyTaskReward] = "Net.Msgs.ReceiveHeroBountyTaskRewardMessage",
	[MsgDefines.RefreshHeroBountyTask] = "Net.Msgs.RefreshHeroBountyTaskMessage",
	[MsgDefines.PushPveStaminaUpdate] = "Net.Msgs.PushPveStaminaUpdateMessage",
	[MsgDefines.SyncPveResource] = "Net.Msgs.SyncPveResourceMessage",

	[MsgDefines.GetCrossServerInfo] = "Net.Msgs.GetCrossServerInfoMessage",
	[MsgDefines.GetGolloesCardInfo] = "Net.Msgs.Activity.GolloesCard.GetGolloesCardInfoMessage",
	[MsgDefines.FlipGolloesCard] = "Net.Msgs.Activity.GolloesCard.FlipGolloesCardMessage",
	[MsgDefines.FlipAllGolloesCard] = "Net.Msgs.Activity.GolloesCard.FlipAllGolloesCardMessage",
	[MsgDefines.RefreshGolloesCard] = "Net.Msgs.Activity.GolloesCard.RefreshGolloesCardMessage",
	[MsgDefines.GetGolloesCardRank] = "Net.Msgs.Activity.GolloesCard.GetGolloesCardRankMessage",
	
	[MsgDefines.GetAllianceInfo] = "Net.Msgs.GetAllianceInfoMessage",
	[MsgDefines.PveTriggerCost] = "Net.Msgs.PveTriggerCostMessage",
	[MsgDefines.ReceivePVETriggerReward] = "Net.Msgs.ReceivePVETriggerRewardMessage",
	[MsgDefines.GetTriggerReward] = "Net.Msgs.GetTriggerRewardMessage",
	[MsgDefines.PushPveLevelFinish] = "Net.Msgs.PushPveLevelFinishMessage",
	[MsgDefines.IDCardAuthenticate] = "Net.Msgs.IDCardAuthenticateMessage",
	[MsgDefines.UpgradeTriggerBuilding] = "Net.Msgs.UpgradeTriggerBuildingMessage",
	[MsgDefines.PushFoldCrossWormTime] = "Net.Msgs.PushFoldCrossWormTimeMessage",
	[MsgDefines.PushFoldSubWormTime] = "Net.Msgs.PushFoldSubWormTimeMessage",
	[MsgDefines.PveActGetInfo] = "Net.Msgs.PveActGetInfoMessage",
	[MsgDefines.PveActTaskReward] = "Net.Msgs.PveActTaskRewardMessage",
	[MsgDefines.PveActStageReward] = "Net.Msgs.PveActStageRewardMessage",
	[MsgDefines.PveActUpdateTask] = "Net.Msgs.PveActUpdateTaskMessage",
	[MsgDefines.PveActGetRank] = "Net.Msgs.PveActGetRankMessage",
	[MsgDefines.PveActScoreUpdate] = "Net.Msgs.PveActScoreUpdateMessage",
	[MsgDefines.PveActRankUpdate] = "Net.Msgs.PveActRankUpdateMessage",
	
	[MsgDefines.PushWorldEffect] = "Net.Msgs.PushWorldEffectMessage",
	[MsgDefines.CrossGetAlliancePoint] = "Net.Msgs.CrossGetAlliancePointMessage",

	[MsgDefines.GetSevenDayActInfo] = "Net.Msgs.Activity.SevenDay.GetSevenDayActInfoMessage",
	[MsgDefines.PushSevenDayActScore] = "Net.Msgs.Activity.SevenDay.PushSevenDayActScoreMessage",
	[MsgDefines.ReceiveSevenDayActReward] = "Net.Msgs.Activity.SevenDay.ReceiveSevenDayActRewardMessage",

	[MsgDefines.PushDefendWallCompensate] = "Net.Msgs.PushDefendWallCompensateMessage",
	[MsgDefines.UserGetDefendWallCompensate] = "Net.Msgs.UserGetDefendWallCompensateMessage",
	[MsgDefines.ClearPVETriggerRewardCD] = "Net.Msgs.ClearPVETriggerRewardCDMessage",

	[MsgDefines.PushCrossAlert] = "Net.Msgs.PushCrossAlertMessage",
	[MsgDefines.WorldMarchFormationNew] = "Net.Msgs.WorldMarchFormationNewMessage",--
	[MsgDefines.WorldMarchChange] = "Net.Msgs.WorldMarchChangeMessage",--创建行军
	[MsgDefines.GetChallengeActInfo] = "Net.Msgs.Activity.MonsterTower.GetChallengeActInfoMessage",
	[MsgDefines.ChooseChallengeActDifficulty] = "Net.Msgs.Activity.MonsterTower.ChooseChallengeActDifficultyMessage",
	[MsgDefines.CallChallengeActBoss] = "Net.Msgs.Activity.MonsterTower.CallChallengeActBossMessage",
	[MsgDefines.CallChallengeActHelp] = "Net.Msgs.Activity.MonsterTower.CallChallengeActHelpMessage",
	[MsgDefines.PushCallChallengeActHelp] = "Net.Msgs.Activity.MonsterTower.PushCallChallengeActHelpMessage",
	[MsgDefines.GetChallengeActTaskInfo] = "Net.Msgs.Activity.MonsterTower.GetChallengeActTaskInfoMessage",
	[MsgDefines.ReceiveChallengeActTaskReward] = "Net.Msgs.Activity.MonsterTower.ReceiveChallengeActTaskRewardMessage",
	[MsgDefines.GetChallengeActLevelRewardInfo] = "Net.Msgs.Activity.MonsterTower.GetChallengeActLevelRewardInfoMessage",
	[MsgDefines.GetChallengeActMemberInfo] = "Net.Msgs.Activity.MonsterTower.GetChallengeActMemberInfoMessage",
	[MsgDefines.ReceivePveTriggerDropItem] = "Net.Msgs.ReceivePveTriggerDropItemMessage",
	[MsgDefines.PushChallengeBossKilled] = "Net.Msgs.Activity.MonsterTower.PushChallengeBossKilledMessage",
	[MsgDefines.WorldGetMarchInfos] = "Net.Msgs.WorldGetMarchInfosMessage",
	[MsgDefines.HeroDecomposePiece] = "Net.Msgs.HeroDecomposePieceMessage",
	[MsgDefines.GetGarbageInfo] = "Net.Msgs.GetGarbageInfoMessage",
	[MsgDefines.GetNoticeList] = "Net.Msgs.Notice.GetNoticeListMessage",
	[MsgDefines.PushNewNotice] = "Net.Msgs.Notice.PushNewNoticeMessage",
	[MsgDefines.ReadNotice] = "Net.Msgs.Notice.ReadNoticeMessage",
	[MsgDefines.ReceiceNoticeReward] = "Net.Msgs.Notice.ReceiceNoticeRewardMessage",
	[MsgDefines.PushDeleteNotice] = "Net.Msgs.Notice.PushDeleteNoticeMessage",
	[MsgDefines.BackBuildingCollectTime] = "Net.Msgs.BackBuildingCollectTimeMessage",

	[MsgDefines.UserGetAllDesert] = "Net.Msgs.UserGetAllDesertMessage",
	[MsgDefines.UserGiveUpDesert] = "Net.Msgs.UserGiveUpDesertMessage",
	[MsgDefines.UserCancelGiveUpDesert] = "Net.Msgs.UserCancelGiveUpDesertMessage",
	[MsgDefines.PushUserGetDesert] = "Net.Msgs.PushUserGetDesertMessage",
	[MsgDefines.PushUserLostDesert] = "Net.Msgs.PushUserLostDesertMessage",
	[MsgDefines.FormationMarchTime] = "Net.Msgs.FormationMarchTimeMessage",
	[MsgDefines.SeasonBalanceViewOpen] = "Net.Msgs.SeasonBalanceViewOpenMessage",
	[MsgDefines.PushSeasonBalanceRemind] = "Net.Msgs.PushSeasonBalanceRemindMessage",
	[MsgDefines.SeasonBalancePackageViewOpen] = "Net.Msgs.SeasonBalancePackageViewOpenMessage",
	[MsgDefines.SeasonBalanceGiveRecord] = "Net.Msgs.SeasonBalanceGiveRecordMessage",
	[MsgDefines.SeasonBalanceMemberList] = "Net.Msgs.SeasonBalanceMemberListMessage",
	[MsgDefines.SeasonBalanceGiveAlliesPackages] = "Net.Msgs.SeasonBalanceGiveAlliesPackagesMessage",
	[MsgDefines.SeasonBalanceReceivePackage] = "Net.Msgs.SeasonBalanceReceivePackageMessage",
	[MsgDefines.HeroPosterExchange] = "Net.Msgs.HeroPosterExchangeMessage",

	[MsgDefines.CoverSkin] = "Net.Msgs.CoverSkinMessage",
	[MsgDefines.WearSkin] = "Net.Msgs.WearSkinMessage",
	[MsgDefines.TakeOffSkin] = "Net.Msgs.TakeOffSkinMessage",
	[MsgDefines.UserCollectDesertRes] = "Net.Msgs.UserCollectDesertResMessage",
	[MsgDefines.HeroPosterExchange] = "Net.Msgs.HeroPosterExchangeMessage",
	[MsgDefines.PushSkinUpdate] = "Net.Msgs.PushSkinUpdate",
	[MsgDefines.CheckAttackBoss] = "Net.Msgs.CheckAttackBossMessage",
	[MsgDefines.PushWorldDesertFirstOccupyUpdate] = "Net.Msgs.PushWorldDesertFirstOccupyUpdateMessage",
	
	[MsgDefines.ChainPayGetInfo] = "Net.Msgs.ChainPayGetInfoMessage",
	[MsgDefines.ChainPayReceiveReward] = "Net.Msgs.ChainPayReceiveRewardMessage",
	[MsgDefines.ChainPayUpdateState] = "Net.Msgs.ChainPayUpdateStateMessage",
	[MsgDefines.ChainPayRefresh] = "Net.Msgs.ChainPayRefreshMessage",
	
	[MsgDefines.GetDiscountShopInfo] = "Net.Msgs.GetDiscountShopInfoMessage",
	[MsgDefines.RefreshDisCountShop] = "Net.Msgs.RefreshDisCountShopMessage",
	[MsgDefines.BuyInDiscountShop] = "Net.Msgs.BuyInDiscountShopMessage",

	[MsgDefines.GetSevenDayLoginInfo] = "Net.Msgs.Activity.SevenLogin.GetSevenDayLoginInfoMessage",
	[MsgDefines.ReceiveSevenDayLoginReward] = "Net.Msgs.Activity.SevenLogin.ReceiveSevenDayLoginRewardMessage",
	[MsgDefines.UserModifySex] = "Net.Msgs.UserModifySexMessage",
	[MsgDefines.GetActivityGiftBoxInfo] = "Net.Msgs.Activity.GiftBox.GetActivityGiftBoxInfoMessage",
	[MsgDefines.OpenActivityGiftBox] = "Net.Msgs.Activity.GiftBox.OpenActivityGiftBoxMessage",
	[MsgDefines.ActivityGiftBoxLottery] = "Net.Msgs.Activity.GiftBox.ActivityGiftBoxLotteryMessage",
	[MsgDefines.GetActivityGiftBoxLotteryCount] = "Net.Msgs.Activity.GiftBox.GetActivityGiftBoxLotteryCountMessage",
	[MsgDefines.GetGiftBoxRank] = "Net.Msgs.Activity.GiftBox.GetGiftBoxRankMessage",
	
	[MsgDefines.DesertForceServerRank] = "Net.Msgs.DesertForceServerRankMessage",

	[MsgDefines.PushExtraDesertNum] = "Net.Msgs.PushExtraDesertNumMessage",
	[MsgDefines.SeasonForceReward] = "Net.Msgs.SeasonForceRewardMessage",
	[MsgDefines.SeasonForceBattlePassReward] = "Net.Msgs.SeasonForceBattlePassRewardMessage",
	[MsgDefines.SeasonForceGetAllReward] = "Net.Msgs.SeasonForceGetAllRewardMessage",
	[MsgDefines.SeasonForceGetReward] = "Net.Msgs.SeasonForceGetRewardMessage",
	[MsgDefines.PushSeasonForceRewardAdd] = "Net.Msgs.PushSeasonForceRewardAddMessage",
	[MsgDefines.SeasonForceGetBattlePassReward] = "Net.Msgs.SeasonForceGetBattlePassRewardMessage",

	[MsgDefines.GetSeasonWeekCardInfo] = "Net.Msgs.Activity.SeasonWeekCard.GetSeasonWeekCardInfoMessage",
	[MsgDefines.ReceiveSeasonWeekCardReward] = "Net.Msgs.Activity.SeasonWeekCard.ReceiveSeasonWeekCardRewardMessage",
	[MsgDefines.PushSeasonWeekCardUpdate] = "Net.Msgs.Activity.SeasonWeekCard.PushSeasonWeekCardUpdateMessage",
	[MsgDefines.GetDeadArmyRecord] = "Net.Msgs.GetDeadArmyRecordMessage",
	[MsgDefines.PushDesertCollectTimeUpdate] = "Net.Msgs.PushDesertCollectTimeUpdateMessage",
	[MsgDefines.DesertForceSelfRank] = "Net.Msgs.DesertForceSelfRankMessage",

	[MsgDefines.SeasonWeekBuffGetInfo] = "Net.Msgs.SeasonWeekBuffGetInfoMessage",
	[MsgDefines.SeasonWeekBuffReceiveReward] = "Net.Msgs.SeasonWeekBuffReceiveRewardMessage",
	[MsgDefines.SeasonWeekBuffUpdate] = "Net.Msgs.SeasonWeekBuffUpdateMessage",
	
	[MsgDefines.MasteryLearn] = "Net.Msgs.Mastery.MasteryLearnMessage",
	[MsgDefines.MasteryChangePlan] = "Net.Msgs.Mastery.MasteryChangePlanMessage",
	[MsgDefines.MasteryUseSkill] = "Net.Msgs.Mastery.MasteryUseSkillMessage",
	[MsgDefines.MasteryUpdate] = "Net.Msgs.Mastery.MasteryUpdateMessage",
	[MsgDefines.ResetDesertTalentOtherPage] = "Net.Msgs.Mastery.ResetDesertTalentOtherPageMessage",
	[MsgDefines.ChangeDesertTalentPageName] = "Net.Msgs.Mastery.ChangeDesertTalentPageNameMessage",
	[MsgDefines.DesertTalentPageNameCheck] = "Net.Msgs.Mastery.DesertTalentPageNameCheckMessage",
	[MsgDefines.PushDesertTalentExtraPageNum] = "Net.Msgs.Mastery.PushDesertTalentExtraPageNumMessage",
	
	[MsgDefines.GetDeclareWarInfo] = "Net.Msgs.Glory.GetDeclareWarInfoMessage",
	[MsgDefines.DomainAlWarPanel] = "Net.Msgs.Glory.DomainAlWarPanelMessage",
	[MsgDefines.DomainAlDeclareWar] = "Net.Msgs.Glory.DomainAlDeclareWarMessage",
	[MsgDefines.PushAlDomainFightOpen] = "Net.Msgs.Glory.PushAlDomainFightOpenMessage",
	[MsgDefines.DomainAlMatchVs] = "Net.Msgs.Glory.DomainAlMatchVsMessage",
	[MsgDefines.DomainAlSetAvoidTime] = "Net.Msgs.Glory.DomainAlSetAvoidTimeMessage",
	[MsgDefines.DomainAlHis] = "Net.Msgs.Glory.DomainAlHisMessage",
	[MsgDefines.DomainAlWarMemberScoreHis] = "Net.Msgs.Glory.DomainAlWarMemberScoreHisMessage",
	[MsgDefines.DomainAlWarResult] = "Net.Msgs.Glory.DomainAlWarResultMessage",
	[MsgDefines.AlBattleEvent] = "Net.Msgs.Glory.AlBattleEventMessage",
	[MsgDefines.AlFightActInfo] = "Net.Msgs.Glory.AlFightActInfoMessage",
	[MsgDefines.AlFightActInfoRecord] = "Net.Msgs.Glory.AlFightActInfoRecordMessage",
	[MsgDefines.AlFightActMemberScore] = "Net.Msgs.Glory.AlFightActMemberScoreMessage",
	[MsgDefines.SeasonContributionInfo] = "Net.Msgs.Glory.SeasonContributionInfoMessage",
	[MsgDefines.GetDeclareTargetAlliancePosition] = "Net.Msgs.Glory.GetDeclareTargetAlliancePositionMessage",
	
	[MsgDefines.GetAllianceSeasonRank] = "Net.Msgs.GetAllianceSeasonRankMessage",
	[MsgDefines.GetLastSeasonHeroRecordInfo] = "Net.Msgs.Activity.GetLastSeasonHeroRecordInfoMessage",
	[MsgDefines.GetSkinActivityInfo] = "Net.Msgs.Activity.Decoration.GetSkinActivityInfoMessage",
	[MsgDefines.ReceiveSkinActivityReward] = "Net.Msgs.Activity.Decoration.ReceiveSkinActivityRewardMessage",
	[MsgDefines.SkinActivityRewardStatePush] = "Net.Msgs.Activity.Decoration.SkinActivityRewardStatePush",
	[MsgDefines.SendContactGiftSearch] = "Net.Msgs.Activity.Decoration.SendContactGiftSearchMessage",
	[MsgDefines.SendGiftByActivity] = "Net.Msgs.Activity.Decoration.SendGiftByActivityMessage",
	[MsgDefines.GetDeadArmyRecord] = "Net.Msgs.GetDeadArmyRecordMessage",
	[MsgDefines.PushFoldAlFlagTime] = "Net.Msgs.PushFoldAlFlagTimeMessage",
	[MsgDefines.GetAlFlagDestroyTime] = "Net.Msgs.GetAlFlagDestroyTimeMessage",
	[MsgDefines.PushAllianceBuildDefendChange] = "Net.Msgs.PushAllianceBuildDefendChangeMessage",

	[MsgDefines.WorldFoldUpAllianceBuilding] = "Net.Msgs.WorldFoldUpAllianceBuildingMessage",
	[MsgDefines.WorldFixAllianceBuilding] = "Net.Msgs.WorldFixAllianceBuildingMessage",

	[MsgDefines.UserSaveCrossDefendHero] = "Net.Msgs.UserSaveCrossDefendHeroMessage",
	[MsgDefines.UserFillCrossWormArmy] = "Net.Msgs.UserFillCrossWormArmyMessage",
	[MsgDefines.PushCrossFillArmyTimes] = "Net.Msgs.PushCrossFillArmyTimesMessage",
	[MsgDefines.UserGetCrossWormRes] = "Net.Msgs.UserGetCrossWormResMessage",
	[MsgDefines.PushCrossWormRes] = "Net.Msgs.PushCrossWormResMessage",
	[MsgDefines.PushCrossResSync] = "Net.Msgs.PushCrossResSyncMessage",

	[MsgDefines.PushAreaHotNewAdd] = "Net.Msgs.PushAreaHotNewAddMessage",
	[MsgDefines.PushFoldAlFortressTime] = "Net.Msgs.PushFoldAlFortressTimeMessage",
	[MsgDefines.MonsterSiegeActivityInfo] = "Net.Msgs.Activity.BlackKnight.MonsterSiegeActivityInfoMessage",
	[MsgDefines.MonsterSiegeStart] = "Net.Msgs.Activity.BlackKnight.MonsterSiegeStartMessage",
	[MsgDefines.MonsterSiegeRewardInfo] = "Net.Msgs.Activity.BlackKnight.MonsterSiegeRewardInfoMessage",
	[MsgDefines.PushMonsterAttack] = "Net.Msgs.Activity.BlackKnight.PushMonsterAttackMessage", 

	[MsgDefines.PushAllianceAttackerAdd] = "Net.Msgs.PushAllianceAttackerAddMessage",
	[MsgDefines.GetWorldAttackerInfo] = "Net.Msgs.GetWorldAttackerInfoMessage",

	[MsgDefines.CarEquipExp] = "Net.Msgs.Equipment.CarEquipExpMessage",
	[MsgDefines.EquipUpQuality] = "Net.Msgs.Equipment.EquipUpQualityMessage",
	[MsgDefines.WearCarEquip] = "Net.Msgs.Equipment.WearCarEquipMessage",
	[MsgDefines.TakeOffEquip] = "Net.Msgs.Equipment.TakeOffEquipMessage",
	[MsgDefines.NewCarEquipPush] = "Net.Msgs.Equipment.NewCarEquipPush",
	[MsgDefines.EquipEffectChangePush] = "Net.Msgs.Equipment.EquipEffectChangePush",
	[MsgDefines.PushAreaHotNewAdd] = "Net.Msgs.PushAreaHotNewAddMessage",
	[MsgDefines.PushFoldAlFortressTime] = "Net.Msgs.PushFoldAlFortressTimeMessage",
	[MsgDefines.MonsterSiegeActivityInfo] = "Net.Msgs.Activity.BlackKnight.MonsterSiegeActivityInfoMessage",
	[MsgDefines.MonsterSiegeStart] = "Net.Msgs.Activity.BlackKnight.MonsterSiegeStartMessage",
	[MsgDefines.MonsterSiegeRewardInfo] = "Net.Msgs.Activity.BlackKnight.MonsterSiegeRewardInfoMessage",
	[MsgDefines.PushMonsterAttack] = "Net.Msgs.Activity.BlackKnight.PushMonsterAttackMessage",
	[MsgDefines.PushAllianceAttackerAdd] = "Net.Msgs.PushAllianceAttackerAddMessage",
	[MsgDefines.GetWorldAttackerInfo] = "Net.Msgs.GetWorldAttackerInfoMessage",
	[MsgDefines.GetDonateArmyActivityInfo] = "Net.Msgs.GetDonateArmyActivityInfoMessage",
	[MsgDefines.GetDonateArmyScoreInfo] = "Net.Msgs.GetDonateArmyScoreInfoMessage",
	[MsgDefines.ReceiveDonateArmyTaskReward] = "Net.Msgs.ReceiveDonateArmyTaskRewardMessage",
	[MsgDefines.DonateArmy] = "Net.Msgs.DonateArmyMessage",
	[MsgDefines.ReceiveDonateArmyStageReward] = "Net.Msgs.ReceiveDonateArmyStageRewardMessage",
	[MsgDefines.PushDonateArmyTaskUpdate] = "Net.Msgs.PushDonateArmyTaskUpdateMessage",
	[MsgDefines.GetDonateArmyInfoMessage] = "Net.Msgs.GetDonateArmyInfoMessage",
	[MsgDefines.GetDonateArmyRankMessage] = "Net.Msgs.GetDonateArmyRankMessage",
	[MsgDefines.PirateSiegeOpen] = "Net.Msgs.PirateSiegeOpenMessage",
	[MsgDefines.PushPirateSiegeBattleStart] = "Net.Msgs.PushPirateSiegeBattleStartMessage",

	[MsgDefines.GetKingdomPositions] = "Net.Msgs.Government.GetKingdomPositionsMessage",
	[MsgDefines.KingdomPositionAppoint] = "Net.Msgs.Government.KingdomPositionAppointMessage",
	[MsgDefines.ChooseKing] = "Net.Msgs.Government.ChooseKingMessage",
	[MsgDefines.GetKingInfo] = "Net.Msgs.Government.GetKingInfoMessage",
	[MsgDefines.ModifyKingDeclaration] = "Net.Msgs.Government.ModifyKingDeclarationMessage",
	[MsgDefines.GetKingdomPresentInfo] = "Net.Msgs.Government.GetKingdomPresentInfoMessage",
	[MsgDefines.GetKingdomPresentRecord] = "Net.Msgs.Government.GetKingdomPresentRecordMessage",
	[MsgDefines.KingSendPresent] = "Net.Msgs.Government.KingSendPresentMessage",
	[MsgDefines.GetKingHistory] = "Net.Msgs.Government.GetKingHistoryMessage",
	[MsgDefines.PushUserKingdomPositionUpdate] = "Net.Msgs.Government.PushUserKingdomPositionUpdate",
	[MsgDefines.TransferKing] = "Net.Msgs.Government.TransferKingMessage",

	[MsgDefines.HeroEvolveActivityInfo] = "Net.Msgs.Activity.HeroEvolveActivity.HeroEvolveActivityInfoMessage",
	[MsgDefines.HeroEvolveActivityChooseHero] = "Net.Msgs.Activity.HeroEvolveActivity.HeroEvolveActivityChooseHeroMessage",
	[MsgDefines.HeroEvolveActivityHeroEvolve] = "Net.Msgs.Activity.HeroEvolveActivity.HeroEvolveActivityHeroEvolveMessage",
	
	[MsgDefines.GetHeroMedalShopInfoCmd] = "Net.msgs.GetHeroMedalShopInfoMessage",
	[MsgDefines.UserHeroMedalShopBuy] = "Net.msgs.UserHeroMedalShopBuy",
	[MsgDefines.ReceiveHeroMedalShopDailyReward] = "Net.msgs.ReceiveHeroMedalShopDailyReward",
	[MsgDefines.GetHeroMedalShopInfoCmd] = "Net.Msgs.GetHeroMedalShopInfoMessage",
	[MsgDefines.UserHeroMedalShopBuy] = "Net.Msgs.UserHeroMedalShopBuy",
	[MsgDefines.ReceiveHeroMedalShopDailyReward] = "Net.Msgs.ReceiveHeroMedalShopDailyReward",
	
	[MsgDefines.GetDesertForceGroupRank] = "Net.Msgs.GetDesertForceGroupRankMessage",

	[MsgDefines.GetRefreshDesertActivityInfo] = "Net.Msgs.Activity.KingRefreshDesert.GetRefreshDesertActivityInfoMessage",
	[MsgDefines.KingRefreshDesert] = "Net.Msgs.Activity.KingRefreshDesert.KingRefreshDesertMessage",
	[MsgDefines.KingRefreshDesertPush] = "Net.Msgs.Activity.KingRefreshDesert.KingRefreshDesertPush",
	-- 新捐兵活动相关请求 
	[MsgDefines.GetALVSDonateArmyActivityInfo] = "Net.Msgs.GetALVSDonateArmyActivityInfoMessage",
	[MsgDefines.ReceiveALVSDonateArmyTaskReward] = "Net.Msgs.ReceiveALVSDonateArmyTaskRewardMessage",
	[MsgDefines.ALVSDonateArmy] = "Net.Msgs.ALVSDonateArmyMessage",
	[MsgDefines.ReceiveALVSDonateArmyStageReward] = "Net.Msgs.ReceiveALVSDonateArmyStageRewardMessage",
	[MsgDefines.PushALVSDonateArmyTaskUpdate] = "Net.Msgs.PushALVSDonateArmyTaskUpdateMessage",
	[MsgDefines.GetALVSDonateArmyDeclareWarList] = "Net.Msgs.GetALVSDonateArmyDeclareWarListMessage",
	[MsgDefines.ALVSDonateArmyRandomMatchEnemy] = "Net.Msgs.ALVSDonateArmyRandomMatchEnemyMessage",
	[MsgDefines.ALVSDonateArmyDeclareWar] = "Net.Msgs.ALVSDonateArmyDeclareWarMessage",
	[MsgDefines.PushALVSDonateArmyMatchSuccess] = "Net.Msgs.PushALVSDonateArmyMatchSuccess",
	[MsgDefines.PushALVSDonateArmyBattleStart] = "Net.Msgs.PushALVSDonateArmyBattleStart",
	[MsgDefines.GetALVSDonateArmyBattleInfo] = "Net.Msgs.GetALVSDonateArmyBattleInfoMessage",
	[MsgDefines.ALVSDonateArmyOpenAttack] = "Net.Msgs.ALVSDonateArmyOpenAttackMessage",

	[MsgDefines.PushDonateArmyDefenceResult] = "Net.Msgs.PushDonateArmyDefenceResultMessage",
	[MsgDefines.MissileInfoGet] = "Net.Msgs.Activity.Missile.MissileInfoGetMessage",
	[MsgDefines.MissileInfoPush] = "Net.Msgs.Activity.Missile.MissileInfoPush",
	[MsgDefines.MissileCreate] = "Net.Msgs.Activity.Missile.MissileCreateMessage",
	[MsgDefines.MissileAttackPush] = "Net.Msgs.Activity.Missile.MissileAttackPush",
	
	[MsgDefines.EdenMissileInfoGet] = "Net.Msgs.Activity.Missile.EdenMissileInfoGetMessage",
	[MsgDefines.BuyAndUseEdenMissile] = "Net.Msgs.Activity.Missile.BuyAndUseEdenMissileMessage",
	
	[MsgDefines.GetMigrateServers] = "Net.Msgs.GetMigrateServersMessage",
	[MsgDefines.MigrateToServer] = "Net.Msgs.MigrateToServerMessage",
	[MsgDefines.GetMigrateItem] = "Net.Msgs.GetMigrateItemMessage",
	[MsgDefines.MigrateApply] = "Net.Msgs.MigrateApplyMessage",
	[MsgDefines.MigrateApplyList] = "Net.Msgs.MigrateApplyListMessage",
	[MsgDefines.MigrateApprove] = "Net.Msgs.MigrateApproveMessage",
	[MsgDefines.MigrateSetPowerLimit] = "Net.Msgs.MigrateSetPowerLimitMessage",
	[MsgDefines.PushMigrateNewApply] = "Net.Msgs.PushMigrateNewApplyMessage",
	[MsgDefines.MissileInfoGet] = "Net.Msgs.Activity.Missile.MissileInfoGetMessage",
	[MsgDefines.MissileInfoPush] = "Net.Msgs.Activity.Missile.MissileInfoPush",
	[MsgDefines.MissileCreate] = "Net.Msgs.Activity.Missile.MissileCreateMessage",

	[MsgDefines.MigrateActivityInfo] = "Net.Msgs.MigrateActivityInfoMessage",

	[MsgDefines.PushDeclareWarExitAllianceRecord] = "Net.Msgs.PushDeclareWarExitAllianceRecordMessage",
	[MsgDefines.AllianceRankLimit] = "Net.Msgs.AllianceRankLimitMessage",
	[MsgDefines.PushPlayerNitrogen] = "Net.Msgs.PushPlayerNitrogenMessage",
	[MsgDefines.SpeedUpMarchNitrogen] = "Net.Msgs.SpeedUpMarchNitrogenMessage",
	[MsgDefines.GetAllianceActMineMember] = "Net.Msgs.GetAllianceActMineMemberMessage",
	[MsgDefines.GetActMinePlunderRes] = "Net.Msgs.GetActMinePlunderResMessage",
	[MsgDefines.GetAllianceBossActivityInfo] = "Net.Msgs.GetAllianceBossActivityInfoMessage",
	[MsgDefines.AllianceBossDonate] = "Net.Msgs.AllianceBossDonateMessage",
	[MsgDefines.CallAllianceBoss] = "Net.Msgs.CallAllianceBossMessage",
	[MsgDefines.PushAllianceBossCreate] = "Net.Msgs.PushAllianceBossCreateMessage",
	[MsgDefines.PushAllianceBossDamageUpdate] = "Net.Msgs.PushAllianceBossDamageUpdateMessage",
	[MsgDefines.ReceiveAllianceBossFreeReward] = "Net.Msgs.ReceiveAllianceBossFreeRewardMessage",
	[MsgDefines.GetAllianceBossDonateRank] = "Net.Msgs.GetAllianceBossDonateRankMessage",
	[MsgDefines.GetAllianceBossDamageRank] = "Net.Msgs.GetAllianceBossDamageRankMessage",
	[MsgDefines.GetMiningActParamInfo] = "Net.Msgs.Activity.Mining.GetMiningActParamInfoMessage",
	[MsgDefines.GetMiningLotteryResInfo] = "Net.Msgs.Activity.Mining.GetMiningLotteryResInfoMessage",
	[MsgDefines.GetMiningSpeedUpResInfo] = "Net.Msgs.Activity.Mining.GetMiningSpeedUpResInfoMessage",
	[MsgDefines.GetMiningCarRewardInfo] = "Net.Msgs.Activity.Mining.GetMiningCarRewardInfoMessage",
	[MsgDefines.GetMiningQueueUnlockResInfo] = "Net.Msgs.Activity.Mining.GetMiningQueueUnlockResInfoMessage",
	[MsgDefines.ReceiveActivityMineStageReward] = "Net.Msgs.Activity.Mining.ReceiveActivityMineStageRewardMessage",

	[MsgDefines.GetMysteriousActParamInfo] = "Net.Msgs.Activity.Mysterious.GetMysteriousActParamInfoMessage",
	[MsgDefines.GetMysteriousLotteryRes] = "Net.Msgs.Activity.Mysterious.GetMysteriousLotteryResMessage",
	[MsgDefines.GetMysteriousRewardRes] = "Net.Msgs.Activity.Mysterious.GetMysteriousRewardResMessage",
	[MsgDefines.GetMysteriousRankInfo] = "Net.Msgs.Activity.Mysterious.GetMysteriousRankInfoMessage",

	[MsgDefines.ReceiveStoryStageReward] = "Net.Msgs.Story.ReceiveStoryStageRewardMessage",
	[MsgDefines.PushStoryTimeUpdate] = "Net.Msgs.Story.PushStoryTimeUpdateMessage",
	[MsgDefines.GetStoryTimeReward] = "Net.Msgs.Story.GetStoryTimeRewardMessage",
	[MsgDefines.ReceiveStoryTimeReward] = "Net.Msgs.Story.ReceiveStoryTimeRewardMessage",
	[MsgDefines.GetStoryRank] = "Net.Msgs.Story.GetStoryRankMessage",
	[MsgDefines.FinishStoryPve] = "Net.Msgs.Story.FinishStoryPveMessage",
	[MsgDefines.PushStoryInfo] = "Net.Msgs.Story.PushStoryInfoMessage",
	
	[MsgDefines.TestPveLevel] = "Net.Msgs.TestPveLevelMessage",
	
	[MsgDefines.UserGetStaminaBubble] = "Net.Msgs.UserGetStaminaBubbleMessage",
	[MsgDefines.UserRewardStaminaBubble] = "Net.Msgs.UserRewardStaminaBubbleMessage",
	
	[MsgDefines.DragonActivityInfo] = "Net.Msgs.Activity.Dragon.DragonActivityInfoMessage",
	[MsgDefines.PushDragonScoreSync] = "Net.Msgs.Activity.Dragon.PushDragonScoreSyncMessage",
	[MsgDefines.DragonAssignPlayerInfo] = "Net.Msgs.Activity.Dragon.DragonAssignPlayerInfoMessage",
	[MsgDefines.DragonAutoAssignPlayer] = "Net.Msgs.Activity.Dragon.DragonAutoAssignPlayerMessage",
	[MsgDefines.DragonRevokeAllPlayer] = "Net.Msgs.Activity.Dragon.DragonRevokeAllPlayerMessage",
	[MsgDefines.DragonAssignPlayer] = "Net.Msgs.Activity.Dragon.DragonAssignPlayerMessage",
	[MsgDefines.DragonRevokePlayer] = "Net.Msgs.Activity.Dragon.DragonRevokePlayerMessage",
	[MsgDefines.DragonBattleSignUp] = "Net.Msgs.Activity.Dragon.DragonBattleSignUpMessage",
	[MsgDefines.DragonBattleModifyBattlePeriod] = "Net.Msgs.Activity.Dragon.DragonBattleModifyBattlePeriodMessage",
	[MsgDefines.GetDragonBattleTimes] = "Net.Msgs.Activity.Dragon.GetDragonBattleTimesMessage",
	[MsgDefines.DragonBattleInfo] = "Net.Msgs.Activity.Dragon.DragonBattleInfoMessage",
	[MsgDefines.DragonBattleScoreInfo] = "Net.Msgs.Activity.Dragon.DragonBattleScoreInfoMessage",
	[MsgDefines.DragonRewardInfo] = "Net.Msgs.Activity.Dragon.DragonRewardInfoMessage",
	[MsgDefines.DragonBattleHistory] = "Net.Msgs.Activity.Dragon.DragonBattleHistoryMessage",
	[MsgDefines.PushDragonResult] = "Net.Msgs.Activity.Dragon.PushDragonResultMessage",
	[MsgDefines.PushDragonBattlePeriodChange] = "Net.Msgs.Activity.Dragon.PushDragonBattlePeriodChangeMessage",
	[MsgDefines.ExitDragonServer] = "Net.Msgs.ExitDragonServerMessage",

	[MsgDefines.UserShareMail] = "Net.Msgs.UserShareMailMessage",

	[MsgDefines.UserGetServerActEffect] = "Net.Msgs.UserGetServerActEffectMessage",
	[MsgDefines.PushServerActEffect] = "Net.Msgs.PushServerActEffectMessage",

	[MsgDefines.GetScratchOffGameActivityInfo] = "Net.Msgs.Activity.ScratchOffGame.ScratchOffGameActivityInfoMessage",
	[MsgDefines.GetScratchOffGameLotteryRes] = "Net.Msgs.Activity.ScratchOffGame.ScratchOffGameLotteryMessage",
	[MsgDefines.GetScratchOffGameRewardRecord] = "Net.Msgs.Activity.ScratchOffGame.ScratchOffGameRewardRecordMessage",
	[MsgDefines.GetScratchOffGameRankInfo] = "Net.Msgs.Activity.ScratchOffGame.ScratchOffGameRankInfoMessage",
	[MsgDefines.GetScratchOffGameSwitchHero] = "Net.Msgs.Activity.ScratchOffGame.ScratchOffGameSwitchHeroMessage",

	[MsgDefines.UpgradeHeroPlugin] = "Net.Msgs.HeroPlugin.UpgradeHeroPluginMessage",
	[MsgDefines.RefineHeroPlugin] = "Net.Msgs.HeroPlugin.RefineHeroPluginMessage",
	[MsgDefines.SaveHeroPlugin] = "Net.Msgs.HeroPlugin.SaveHeroPluginMessage",
	[MsgDefines.LockHeroPlugin] = "Net.Msgs.HeroPlugin.LockHeroPluginMessage",
	[MsgDefines.UnlockHeroPlugin] = "Net.Msgs.HeroPlugin.UnlockHeroPluginMessage",
	[MsgDefines.ExchangeHeroPlugin] = "Net.Msgs.HeroPlugin.ExchangeHeroPluginMessage",
	[MsgDefines.PrepareFillArmy] = "Net.Msgs.PrepareFillArmyMessage",

	[MsgDefines.GetColonialWarAllianceRank] = "Net.Msgs.GetColonialWarAllianceRankMessage",
	[MsgDefines.GetColonialWarUserRank] = "Net.Msgs.GetColonialWarUserRankMessage",

	[MsgDefines.MoveCrossServer] = "Net.Msgs.Eden.MoveCrossServerMessage",
	[MsgDefines.GetEdenGroupInfo] = "Net.Msgs.Eden.GetEdenGroupInfoMessage",
	[MsgDefines.GetEdenGroupSimpleInfo] = "Net.Msgs.Eden.GetEdenGroupSimpleInfoMessage",
	[MsgDefines.GetEdenUserRank] = "Net.Msgs.Eden.GetEdenUserRankMessage",
	[MsgDefines.PushEdenLastProtectTime] = "Net.Msgs.Eden.PushEdenLastProtectTimeMessage",
	[MsgDefines.GetEdenCampScore] = "Net.Msgs.Eden.GetEdenCampScoreMessage",
	[MsgDefines.GetPluginRank] = "Net.Msgs.HeroPlugin.GetPluginRankMessage",
	[MsgDefines.HeroMedalExchangeToken] = "Net.Msgs.HeroPlugin.HeroMedalExchangeTokenMessage",
	[MsgDefines.HeroPosterExchangeToken] = "Net.Msgs.HeroPlugin.HeroPosterExchangeTokenMessage",
	
	[MsgDefines.PushMarchEmoji] = "Net.Msgs.PushMarchEmojiMessage",
	[MsgDefines.SendMarchEmoji] = "Net.Msgs.SendMarchEmojiMessage",
	[MsgDefines.GetEdenMarchSignalPoint] = "Net.Msgs.GetEdenMarchSignalPointMessage",
	[MsgDefines.GetEdenKillActivityRank] = "Net.Msgs.EdenKill.GetEdenKillActivityRankMessage",
	[MsgDefines.GetEdenKillActivityRankReward] = "Net.Msgs.EdenKill.GetEdenKillActivityRankRewardMessage",
	[MsgDefines.GetEdenOccupyThroneActivityInfo] = "Net.Msgs.EdenKill.GetEdenOccupyThroneActivityInfoMessage",
	[MsgDefines.GetEdenAllianceDuelServer] = "Net.Msgs.GetEdenAllianceDuelServerMessage",
	[MsgDefines.GetEdenMineMatchServer] = "Net.Msgs.GetEdenMineMatchServerMessage",
	[MsgDefines.CrossEdenMineServerRank] = "Net.Msgs.CrossEdenMineServerRankMessage",
	[MsgDefines.PushUserEdenQuit] = "Net.Msgs.PushUserEdenQuitMessage",
	
	[MsgDefines.UserAddDesertMine] = "Net.Msgs.UserAddDesertMineMessage",
	[MsgDefines.PushDesertTalentMineTime] = "Net.Msgs.PushDesertTalentMineTimeMessage",
	[MsgDefines.GetAllianceCityKillRank] = "Net.Msgs.GetAllianceCityKillRankMessage",
	[MsgDefines.GetAllianceCityRecordRedPoint] = "Net.Msgs.GetAllianceCityRecordRedPointMessage",
	[MsgDefines.GetAllianceCityKillReward] = "Net.Msgs.GetAllianceCityKillRewardMessage",
	[MsgDefines.UserStartGuidePve] = "Net.Msgs.UserStartGuidePveMessage",
	[MsgDefines.GetSteamCurrency] = "Net.Msgs.GetSteamCurrencyMessage",
	[MsgDefines.GetFirstChargeInfo] = "Net.Msgs.FirstCharge.GetFirstChargeInfoMessage",
	[MsgDefines.ReceiveFirstChargeDayReward] = "Net.Msgs.FirstCharge.ReceiveFirstChargeDayRewardMessage",
	[MsgDefines.PushFirstChargeUpdate] = "Net.Msgs.FirstCharge.PushFirstChargeUpdateMessage",
	[MsgDefines.HeroChooseCamp] = "Net.Msgs.HeroChooseCampMessage",
	[MsgDefines.CallRadarBoss] = "Net.Msgs.RadarBoss.CallRadarBossMessage",
	[MsgDefines.GetRadarBossMarch] = "Net.Msgs.RadarBoss.GetRadarBossMarchMessage",
	[MsgDefines.UserGetRadarBossRank] = "Net.Msgs.RadarBoss.UserGetRadarBossRankMessage",
	[MsgDefines.GetRadarBossRankRewardInfo] = "Net.Msgs.RadarBoss.GetRadarBossRankRewardInfoMessage",
	[MsgDefines.GetRadarBossRewardCount] = "Net.Msgs.RadarBoss.GetRadarBossRewardCountMessage",
	[MsgDefines.GetUploadPicActivityInfo] = "Net.Msgs.Activity.ChangeNameAndPic.GetUploadPicActivityInfoMessage",
	[MsgDefines.ReceiveUploadPicActivityReward] = "Net.Msgs.Activity.ChangeNameAndPic.ReceiveUploadPicActivityRewardMessage",

	[MsgDefines.ReceiveWatchAdReward] = "Net.Msgs.WatchAd.ReceiveWatchAdRewardMessage",

	[MsgDefines.GetStoreEvaluateActivityInfo] = "Net.Msgs.Activity.CountryRating.GetStoreEvaluateActivityInfoMessage",
	[MsgDefines.ReceiveStoreEvaluateStageReward] = "Net.Msgs.Activity.CountryRating.ReceiveStoreEvaluateStageRewardMessage",

	[MsgDefines.ResidentSetWork] = "Net.Msgs.Vita.ResidentSetWorkMessage",
	[MsgDefines.ResidentSetWorkBatch] = "Net.Msgs.Vita.ResidentSetWorkBatchMessage",
	[MsgDefines.ResidentSetFood] = "Net.Msgs.Vita.ResidentSetFoodMessage",
	[MsgDefines.ResidentSetFurnace] = "Net.Msgs.Vita.ResidentSetFurnaceMessage",
	[MsgDefines.UserSynResident] = "Net.Msgs.Vita.UserSynResidentMessage",
	[MsgDefines.PushUserResidentSync] = "Net.Msgs.Vita.PushUserResidentSyncMessage",
	[MsgDefines.UserAcceptResident] = "Net.Msgs.Vita.UserAcceptResidentMessage",
	[MsgDefines.StartNewbieResident] = "Net.Msgs.Vita.StartNewbieResidentMessage",
	[MsgDefines.DoctorCureResident] = "Net.Msgs.Vita.DoctorCureResidentMessage",
	[MsgDefines.PushNewResident] = "Net.Msgs.Vita.PushNewResidentMessage",
	[MsgDefines.PushUserResidentParam] = "Net.Msgs.Vita.PushUserResidentParamMessage",
	[MsgDefines.ChangeResidentTime] = "Net.Msgs.Vita.ChangeResidentTimeMessage",
	[MsgDefines.UserLevelUpResident] = "Net.Msgs.Vita.UserLevelUpResidentMessage",
	[MsgDefines.PushResidentEffectChange] = "Net.Msgs.Vita.PushResidentEffectChangeMessage",
	[MsgDefines.ZombieIllResident] = "Net.Msgs.Vita.ZombieIllResidentMessage",
	[MsgDefines.PushResidentTask] = "Net.Msgs.Vita.PushResidentTaskMessage",
	[MsgDefines.PushResidentTaskDel] = "Net.Msgs.Vita.PushResidentTaskDelMessage",
	[MsgDefines.PushResidentTaskUpdate] = "Net.Msgs.Vita.PushResidentTaskUpdateMessage",
	[MsgDefines.FinishResidentTask] = "Net.Msgs.Vita.FinishResidentTaskMessage",
	[MsgDefines.ZombieDestroyWall] = "Net.Msgs.CityWall.ZombieDestroyWallMessage",
	[MsgDefines.FixZombieDestroyWall] = "Net.Msgs.CityWall.FixZombieDestroyWallMessage",
	
	[MsgDefines.ZombieRuinBuild] = "Net.Msgs.ZombieRuinBuildMessage",
	[MsgDefines.FixZombieRuinBuild] = "Net.Msgs.FixZombieRuinBuildMessage",
	
	[MsgDefines.GetSuggestionBoxInfo] = "Net.Msgs.Opinion.GetSuggestionBoxInfoMessage",
	[MsgDefines.GetHistorySatisfactionRecord] = "Net.Msgs.Opinion.GetHistorySatisfactionRecordMessage",
	[MsgDefines.PushSuggestionBoxInfoUpdate] = "Net.Msgs.Opinion.PushSuggestionBoxInfoUpdateMessage",
	[MsgDefines.ResidentMailChoose] = "Net.Msgs.Opinion.ResidentMailChooseMessage",

	[MsgDefines.UserBuildFurniture] = "Net.Msgs.Furniture.UserBuildFurnitureMessage",
	[MsgDefines.UserLevelUpFurniture] = "Net.Msgs.Furniture.UserLevelUpFurnitureMessage",
	[MsgDefines.PushUsrAddFurniture] = "Net.Msgs.Furniture.PushUsrAddFurnitureMessage",

	[MsgDefines.StartNewbieStorm] = "Net.Msgs.Storm.StartNewbieStormMessage",
	[MsgDefines.CollectNewbieStormReward] = "Net.Msgs.Storm.CollectNewbieStormRewardMessage",
	[MsgDefines.GetNewbieStormReward] = "Net.Msgs.Storm.GetNewbieStormRewardMessage",
	[MsgDefines.UserNewbieRobotUnlock] = "Net.Msgs.UserNewbieRobotUnlockMessage",
	
	[MsgDefines.StartLandPve] = "Net.Msgs.Land.StartLandPveMessage",
	[MsgDefines.FinishLandPve] = "Net.Msgs.Land.FinishLandPveMessage",
	[MsgDefines.FinishLandBlock] = "Net.Msgs.Land.FinishLandBlockMessage",
	[MsgDefines.FinishLandZone] = "Net.Msgs.Land.FinishLandZoneMessage",
	[MsgDefines.UnlockLandZone] = "Net.Msgs.Land.UnlockLandZoneMessage",
	[MsgDefines.ReceiveLandRewardNew] = "Net.Msgs.Land.ReceiveLandRewardNewMessage",

	[MsgDefines.PushDailyKillDrakeBossNumber] = "Net.Msgs.Activity.DrakeBoss.PushDailyKillDrakeBossNumberMessage",
	[MsgDefines.GetUserDrakeBoss] = "Net.Msgs.Activity.DrakeBoss.GetUserDrakeBossMessage",
	[MsgDefines.PushUbFurnitureEffect] = "Net.Msgs.Furniture.PushUbFurnitureEffectMessage",
	
	-- LW PVE
	[MsgDefines.StartPveStage] = "Net.Msgs.Battle.StartPveStageMessage",
	-- LW PVE end

	[MsgDefines.PushNowZombieAttack] = "Net.Msgs.CitySiege.PushNowZombieAttackMessage",
	[MsgDefines.UserCallZombieAttack] = "Net.Msgs.CitySiege.UserCallZombieAttackMessage",
	[MsgDefines.UserFinishZombie] = "Net.Msgs.CitySiege.UserFinishZombieMessage",
	[MsgDefines.UserFinishZombieAttack] = "Net.Msgs.CitySiege.UserFinishZombieAttackMessage",

	[MsgDefines.GetDailyPackageInfos] = "Net.Msgs.DailyPackage.GetDailyPackageInfosMessage",
	[MsgDefines.DailyPackageSelectHero] = "Net.Msgs.DailyPackage.DailyPackageSelectHeroMessage",
	[MsgDefines.NewbieResidentDead] = "Net.Msgs.Vita.NewbieResidentDeadMessage",
	[MsgDefines.GetViewLevelWorldInfo] = "Net.Msgs.GetViewLevelWorldInfoMessage",
	[MsgDefines.PushWorldMarchWorldGet] = "Net.Msgs.PushWorldMarchWorldGetMessage",
	[MsgDefines.PushWorldMarchNew] = "Net.Msgs.PushWorldMarchNewMessage",
	[MsgDefines.PushWorldMarchDel] = "Net.Msgs.PushWorldMarchDelMessage",
	[MsgDefines.PushBattleFinish] = "Net.Msgs.PushBattleFinishMessage",
	[MsgDefines.PushWorldDesertUpdate] = "Net.Msgs.PushWorldDesertUpdateMessage",
	[MsgDefines.PushWorldPointUpdate] = "Net.Msgs.PushWorldPointUpdateMessage",
	[MsgDefines.PushBattleRoundInfo] = "Net.Msgs.PushBattleRoundInfoMessage",
	[MsgDefines.HeroStarStory] = "Net.Msgs.HeroAbout.HeroStarStoryMessage",

	--任务派遣协议
	[MsgDefines.DispatchGetTasks] = "Net.Msgs.DispatchTask.DispatchGetTasksMessage",
	[MsgDefines.DispatchGetAllianceTasks] = "Net.Msgs.DispatchTask.DispatchGetAllianceTasksMessage",
	[MsgDefines.DispatchStart] = "Net.Msgs.DispatchTask.DispatchStartMessage",
	[MsgDefines.DispatchReward] = "Net.Msgs.DispatchTask.DispatchRewardMessage",
	[MsgDefines.DispatchSteal] = "Net.Msgs.DispatchTask.DispatchStealMessage",
	[MsgDefines.DispatchAssist] = "Net.Msgs.DispatchTask.DispatchAssistMessage",
	[MsgDefines.PushDispatchGetLog] = "Net.Msgs.DispatchTask.PushDispatchGetLogMessage",
	[MsgDefines.DispatchGetLog] = "Net.Msgs.DispatchTask.DispatchGetLogMessage",
	[MsgDefines.DispatchTaskRefresh] = "Net.Msgs.DispatchTask.DispatchTaskRefreshMessage",
	
	[MsgDefines.HeroEquipInstall] = "Net.Msgs.HeroEquip.HeroEquipInstallMessage",
	[MsgDefines.HeroEquipUninstall] = "Net.Msgs.HeroEquip.HeroEquipUninstallMessage",
	[MsgDefines.HeroEquipUpgrade] = "Net.Msgs.HeroEquip.HeroEquipUpgradeMessage",
	[MsgDefines.HeroEquipPromoteUp] = "Net.Msgs.HeroEquip.HeroEquipPromoteMessage",
	[MsgDefines.HeroEquipDecompose] = "Net.Msgs.HeroEquip.HeroEquipDecomposeMessage",
	[MsgDefines.PushUserHeroEquipAdd] = "Net.Msgs.HeroEquip.HeroEquipAddPushMessage",
	[MsgDefines.StartProductHeroEquip] = "Net.Msgs.HeroEquip.HeroEquipStartProductMessage",
	[MsgDefines.HeroEquipMaterialCompose] = "Net.Msgs.HeroEquip.HeroEquipMaterialComposeMessage",
	[MsgDefines.HeroEquipMaterialDecompose] = "Net.Msgs.HeroEquip.HeroEquipMaterialDecomposeMessage",

	[MsgDefines.DailyMustBuyList] = "Net.Msgs.DailyMustListMessage",
	[MsgDefines.DailyMustBuyReward] = "Net.Msgs.DailyMustRewardMessage",

	[MsgDefines.DetectEventHelpStart] = "Net.Msgs.RadarCenter.DetectEventHelpStartMessage",
	[MsgDefines.DetectEventHelpEnd] = "Net.Msgs.RadarCenter.DetectEventHelpEndMessage",
	[MsgDefines.DetectEventRescueStart] = "Net.Msgs.RadarCenter.DetectEventRescueStartMessage",
	[MsgDefines.DetectEventRescueEnd] = "Net.Msgs.RadarCenter.DetectEventRescueEndMessage",
	[MsgDefines.AutoFinishDetectEvent] = "Net.Msgs.RadarCenter.AutoFinishDetectEventMessage",
	[MsgDefines.ReceiveDetectLevelReward] = "Net.Msgs.RadarCenter.ReceiveDetectLevelRewardMessage",
}

return config