---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2023/6/9 12:23
---
local UIDragonBattleResultView = BaseClass("UIDragonBattleResultView",UIBaseView)
local base = UIBaseView
local Localization = CS.GameEntry.Localization

local return_btn_path = "panel"
local img_path = "Image"
local msg_tip_path = "MsgTips"
local detail_btn_path = "DetailBtn"
local detail_des_path = "DetailBtn/DetailDes"
local function OnCreate(self)
    base.OnCreate(self)
    self.return_btn = self:AddComponent(UIButton, return_btn_path)
    self.return_btn:SetOnClick(function()
        SoundUtil.PlayEffect(SoundAssets.Music_Effect_Button)
        self.ctrl:CloseSelf()
    end)
    self.img = self:AddComponent(UIImage,img_path)
    self.msg = self:AddComponent(UIText,msg_tip_path)
    self.msg:SetLocalText(129074)
    self.anim = self:AddComponent(UISimpleAnimation,"")
    self.btn = self:AddComponent(UIButton,detail_btn_path )
    self.btn:SetOnClick(function()
        SoundUtil.PlayEffect(SoundAssets.Music_Effect_Button)
        self:OnButtonClick()
    end)
    self.detail_des = self:AddComponent(UIText,detail_des_path)
    self.detail_des:SetLocalText(376133)
end

local function OnDestroy(self)
    base.OnDestroy(self)
end


local function OnEnable(self)
    base.OnEnable(self)
    self:RefreshList()
end

local function OnDisable(self)
    base.OnDisable(self)
end


local function OnAddListener(self)
    base.OnAddListener(self)

end

local function OnRemoveListener(self)
    base.OnRemoveListener(self)
end

local function RefreshList(self)
    local result = 0 --0 输 1赢
    local actData = DataCenter.ActDragonManager:GetDragonRecord()
    if actData~=nil then
        if actData[LuaEntry.Player.allianceId]~=nil then
            result = actData[LuaEntry.Player.allianceId].win
        end
    end
    if result ==1 then
        self.anim:Play("win")
        self.img:LoadSprite("Assets/Main/TextureEx/UIActivity/UIbattlefield_win.png")
    else
        self.anim:Play("lost")
        self.img:LoadSprite("Assets/Main/TextureEx/UIActivity/UIbattlefield_defeat.png")
    end
end

local function OnButtonClick(self)
    UIManager:GetInstance():OpenWindow(UIWindowNames.UIDragonBattleScore,false)
end

UIDragonBattleResultView.OnCreate= OnCreate
UIDragonBattleResultView.OnDestroy = OnDestroy
UIDragonBattleResultView.OnEnable = OnEnable
UIDragonBattleResultView.OnDisable = OnDisable
UIDragonBattleResultView.OnAddListener = OnAddListener
UIDragonBattleResultView.OnRemoveListener = OnRemoveListener
UIDragonBattleResultView.RefreshList = RefreshList
UIDragonBattleResultView.OnButtonClick = OnButtonClick
return UIDragonBattleResultView