---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2023/3/1 15:35
---

local UIEquipmentSuitInfoCtrl = BaseClass("UIEquipmentSuitInfoCtrl", UIBaseCtrl)

local function CloseSelf(self)
    UIManager:GetInstance():DestroyWindow(UIWindowNames.UIEquipmentSuitInfo)
end

local function GetPanelData(self, data)
    local suitIntro = EquipmentUtil.GetEquipmentSuitAttr(data.suitId, data.index)
    local result = {}
    result.index = data.index
    result.effect = suitIntro and suitIntro:GetDescription() or ""
    result.unlockStr = suitIntro and suitIntro:GetUnlockTip(data.hasNum) or ""
    result.posX = data.posX
    return result
end

UIEquipmentSuitInfoCtrl.CloseSelf = CloseSelf
UIEquipmentSuitInfoCtrl.GetPanelData = GetPanelData

return UIEquipmentSuitInfoCtrl