---
--- 打点日志
---
local CSPostEventLog = CS.PostEventLog
local PostEventLog = {}

PostEventLog.Defines = {
    -- EXAMPLE_ACTION = "EXAMPLE_ACTION"
      LAUNCH = "LAUNCH" ,
      OBB_FETCH = "OBB_FETCH" ,
      OBB_SUCCESS = "OBB_SUCCESS" ,

      CHECK_VERSION_START = "CHECK_VERSION_START" ,
      CHECK_VERSION_SUCCESS = "CHECK_VERSION_SUCCESS" ,
      CHECK_VERSION_FAILED = "CHECK_VERSION_FAILED" ,
      CHECK_VERSION_TIMEOUT = "CHECK_VERSION_TIMEOUT" ,
      CHECK_VERSION_ONUPDATE = "CHECK_VERSION_ONUPDATE" ,

      DOWNLOAD_MANIFEST_START = "DOWNLOAD_MANIFEST_START" ,
      DOWNLOAD_MANIFEST_SUCCESS = "DOWNLOAD_MANIFEST_SUCCESS" ,
      DOWNLOAD_MANIFEST_FAILED = "DOWNLOAD_MANIFEST_FAILED" ,
      DOWNLOAD_MANIFEST_TIMEOUT = "DOWNLOAD_MANIFEST_TIMEOUT" ,

      DOWNLOAD_START = "DOWNLOAD_START" ,
      DOWNLOAD_FINISH = "DOWNLOAD_FINISH" ,
      DOWNLOAD_FAILED = "DOWNLOAD_FAILED" ,

      START_CONNECT = "START_CONNECT" ,
      CONNECT_TIME_OUT = "CONNECT_TIME_OUT" ,
      GET_SERVERLIST = "GET_SERVERLIST" ,
      SERVERLIST_TIME_OUT = "SERVERLIST_TIME_OUT" ,
      SERVERLIST_FAILED = "SERVERLIST_FAILED" ,
      LONG_TIME_NOT_PUSH_INIT = "LONG_TIME_NOT_PUSH_INIT" ,

      LOGIN_START = "LOGIN_START" ,
      LOGIN_FINISH = "LOGIN_FINISH" ,
      LOGIN_COMPLETE = "LOGIN_COMPLETE" ,
      LOGIN_FAILED = "LOGIN_FAILED" ,
      SERVER_STATUS = "SERVER_STATUS" ,
      PUSH_INIT_RECV = "PUSH_INIT_RECV" ,
      LOGIN_PARSE_ERROR = "LOGIN_PARSE_ERROR" ,
      DISCONNECT_RETRY = "DISCONNECT_RETRY" ,
      SOCKET_ERROR = "SOCKET_ERROR" ,
      DNS_SUCESS = "DNS_SUCESS" ,
      SOCKET_SHUTDOWN = "SOCKET_SHUTDOWN" ,
      APP_QUIT = "APP_QUIT" ,
}

function PostEventLog.Record(action, ...)
    CSPostEventLog.Record(action, ...)
end

return PostEventLog