---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2023/4/13 17:44
---
local UISetScreenResolutionCtrl = BaseClass("UISetScreenResolutionCtrl", UIBaseCtrl)

local function CloseSelf(self)
    UIManager:GetInstance():DestroyWindow(UIWindowNames.UISetScreenResolution)
end

local function Close(self)
    UIManager:GetInstance():DestroyWindowByLayer(UILayer.Normal)
end

local function GetCurIndex(self)
    local curWidth = 0
    local resolutionIndex = 1
    if CS.WindowsTool~=nil and CS.WindowsTool.Instance ~= nil then
        curWidth = CS.WindowsTool.Instance:GetWindowsWidth()
    end
    if curWidth<1900 and curWidth>1500 then
        resolutionIndex = 2
    elseif curWidth>1300 and curWidth<1500 then
        resolutionIndex = 3
    elseif curWidth>1200 and curWidth<1300 then
        resolutionIndex = 4
    elseif curWidth>1000 and curWidth<1200 then
        resolutionIndex = 5
    end
    return resolutionIndex
end

local function OnSetClick(self,index)
    if CS.WindowsTool~=nil and CS.WindowsTool.Instance ~= nil then
        if index ==1 then
            CS.WindowsTool.Instance:SetResolution(1920,1080)
        elseif index ==2 then
            CS.WindowsTool.Instance:SetResolution(1600,900)
        elseif index ==3 then
            CS.WindowsTool.Instance:SetResolution(1366,768)
        elseif index ==4 then
            CS.WindowsTool.Instance:SetResolution(1280,720)
        elseif index ==2 then
            CS.WindowsTool.Instance:SetResolution(1024,576)
        end
        EventManager:GetInstance():Broadcast(EventId.SetScreenResolution)
        self:CloseSelf()
    end 
end

UISetScreenResolutionCtrl.CloseSelf = CloseSelf
UISetScreenResolutionCtrl.Close = Close
UISetScreenResolutionCtrl.OnSetClick =OnSetClick
UISetScreenResolutionCtrl.GetCurIndex = GetCurIndex
return UISetScreenResolutionCtrl