---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2023/11/21 16:08
---
local UIMain = {
    Name = UIWindowNames.UIMain,
    Layer = UILayer.UIResource,
    Ctrl = require "UI.UIMainNew.Controller.UIMainNewCtrl",
    View = require "UI.UIMainNew.View.UIMainNewView",
    PrefabPath = "Assets/Main/Prefab_Dir/UI/UIMain/UIMainNew.prefab",
}

return {
    -- 配置
    UIMain = UIMain,
}