---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 15/4/2024 下午2:44
---
local base = require "UI.UICityHud.Component.UICityHudBase"
local UICityHudFireLock = BaseClass("UICityHudFireLock", base)

local root_path = "Root"
local btn_path = "Root/Btn"
local icon_path = "Root/Btn/List/Icon"
local text_path = "Root/Btn/List/Text"

local function ComponentDefine(self)
    base.ComponentDefine(self)
    self.anim = self:AddComponent(UIAnimator, root_path)
    self.goTextMat = self.transform:Find("Root/Btn/List/Text/goTextMat"):GetComponent(typeof(CS.UnityEngine.MeshRenderer))
    self.btn = self:AddComponent(UIButton, btn_path)
    self.btn:SetOnClick(function()
        self:OnClick()
    end)
    self.icon_image = self:AddComponent(UIImage, icon_path)
    self.text = self:AddComponent(UITextMeshProUGUIEx, text_path)
end

local function DataDefine(self)
    base.DataDefine(self)
    self.clicked = false
end

local function OnAddListener(self)
    base.OnAddListener(self)
end

local function OnRemoveListener(self)
    base.OnRemoveListener(self)
end

local function SetParam(self, param)
    base.SetParam(self, param)
    self.root_go.transform.localPosition = param.offset or Vector3.zero
    self.anim:Play("Idle", 0, 0)
    self.clicked = false
    self:Refresh()
end

local function Refresh(self)
    local config = DataCenter.LandManager:GetConfigByOrder(LandObjectType.Block,self.param.uuid)
    self.resType = 0
    self.count= 0
    self.icon_image:LoadSprite("Assets/Main/Sprites/UI/UIBuildBubble/bubble_icon_ashuoi_award.png")
    self.text:SetText("")
end

local function OnDoAnim(self,order)
end
local function OnClick(self)
    local obj = DataCenter.LandManager:GetObject(LandObjectType.Block, self.param.uuid)
    if obj ~= nil then
        obj:OnClick()
    end
end

UICityHudFireLock.ComponentDefine = ComponentDefine
UICityHudFireLock.DataDefine = DataDefine
UICityHudFireLock.OnAddListener = OnAddListener
UICityHudFireLock.OnRemoveListener = OnRemoveListener
UICityHudFireLock.SetParam = SetParam
UICityHudFireLock.Refresh = Refresh
UICityHudFireLock.OnClick = OnClick
UICityHudFireLock.OnDoAnim = OnDoAnim
return UICityHudFireLock