---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mac.
--- DateTime: 6/24/21 5:21 PM
---
local UIChatSearchUserItem = BaseClass("UIChatSearchUserItem", UIBaseContainer)
local base = UIBaseContainer
local Localization = CS.GameEntry.Localization

local _cp_username = "username"
local _cp_toggle = "toggleBtn"


function UIChatSearchUserItem:ComponentDefine()
    self._txtusername = self:AddComponent(UIText, _cp_username)
    self._toggleBtn = self:AddComponent(UIToggle, _cp_toggle)
end

function UIChatSearchUserItem:DataInit()
    self._freeUserItemList = {}
    self._userItemList = {}
    self._loadingPrefab = {}
    self._prefabNameIndex = 0
end

function UIChatSearchUserItem:OnCreate()
    base.OnCreate(self)
    self:DataInit()
    self:ComponentDefine()
end

-- 打开
function UIChatSearchUserItem:OnEnable()
    base.OnEnable(self)
    self._toggleBtn:SetIsOn(false)
end

function UIChatSearchUserItem:OnAddListener()
    self:AddUIListener(EventId.UPDATE_MSG_USERINFO, self.OnRefresh)
end

function UIChatSearchUserItem:OnRemoveListener()
    self:RemoveUIListener(EventId.UPDATE_MSG_USERINFO,self.OnRefresh)
end

function UIChatSearchUserItem:OnRefresh()
    --local userinfo = self.view.ctrl:GetUserInfoById(self._userInfo["uid"])
	local userinfo = ChatInterface.getUserData(self._userInfo.uid, true)
    self:SetData(userinfo)
end

-- 关闭
function UIChatSearchUserItem:OnDisable()
    base.OnDisable(self)
end

function UIChatSearchUserItem:SetData( userInfo )
    self._userInfo = userInfo
    local username = ""
    -- 这个地方包含 联盟加人+踢人等  联盟部分为{["uid"] = xx, ["name"] = xx}  踢人为chatdata的集合,两个数据结构不一样
    if (userInfo["name"] ~= nil) then
        username = userInfo["name"]
    else
        username = userInfo:GetUserName()
    end
    self._txtusername:SetText(username)
    self.transform:Set_localScale(ResetScale.x, ResetScale.y, ResetScale.z)
end

function UIChatSearchUserItem:GetToggle()
    return self._toggleBtn:GetIsOn()
end

function UIChatSearchUserItem:GetUserData()
    return self._userInfo
end

-- 初始化的时候使用,已经在房间中,设置toggle为显示状态,同时enable不可点击
function UIChatSearchUserItem:SetInChatRoom( value )
    self._toggleBtn:SetIsOn(value)
    self._toggleBtn:SetEnabled(not value)
end

return UIChatSearchUserItem