---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2021/7/30 19:33
---
local BuildFireEffectManager = BaseClass("BuildFireEffectManager", Singleton)
local ResourceManager = CS.GameEntry.Resource
local BuildFireEffect = require "Scene.BuildFireEffect.BuildFireEffect"
local function __init(self)
    self.allEffect = {} --所有建筑特效
    self.OnCreateEffect ={}
    self:AddListener()
end

local function __delete(self)
    for k,v in pairs(self.allEffect) do
        local request = v.request
        v.script:OnDestroy()
        request:Destroy()
    end
    for k,v in pairs(self.OnCreateEffect) do
        if v~=nil then
            v:Destroy()
        end
    end
    self.allEffect = nil
    self.OnCreateEffect = nil
    self:RemoveListener()
end

local function AddListener(self)
    EventManager:GetInstance():AddListener(EventId.ShowIsOnFire, self.ShowIsOnFireSignal)
    EventManager:GetInstance():AddListener(EventId.WORLD_BUILD_OUT_VIEW, self.BuildOutViewSignal)
end

local function RemoveListener(self)
    EventManager:GetInstance():RemoveListener(EventId.ShowIsOnFire, self.ShowIsOnFireSignal)
    EventManager:GetInstance():RemoveListener(EventId.WORLD_BUILD_OUT_VIEW, self.BuildOutViewSignal)
end


local function ShowBuildFireEffect(self,bUuid,posIndex,tile,endTime,buildId)
    local param = {}
    param.tiles = tile
    param.posIndex = posIndex
    param.bUuid = bUuid
    param.endTime = endTime
    param.buildId = buildId
    if self.allEffect[bUuid]==nil and self.OnCreateEffect[bUuid] == nil then
        local modelName = UIAssets.BuildFireEffect
        if buildId == BuildingTypes.FUN_BUILD_MAIN then
            modelName = UIAssets.BuildFireEffectMainBuild
        end
        local request = ResourceManager:InstantiateAsync(modelName)
        local par = {}
        par.request = request
        self.OnCreateEffect[bUuid] = request
        request:completed('+', function()
            self.OnCreateEffect[bUuid] =nil
            if request.isError then
                return
            end
            request.gameObject:SetActive(true)
            request.gameObject.transform:SetParent(CS.SceneManager.World.DynamicObjNode)
            request.gameObject.transform:Set_localScale(ResetScale.x, ResetScale.y, ResetScale.z)

            local effect = BuildFireEffect.New()
            effect:OnCreate(request)
            effect:ReInit(param)
            par.script = effect
            self.allEffect[bUuid] = par
        end)
    else
        if self.allEffect[bUuid]~=nil then
            self.allEffect[bUuid].script:OnUpdateTime(endTime)
        end
    end
    
end


local function RemoveOneEffect(self,bUuid)
    local temp = self.allEffect[bUuid]
    if temp ~= nil then
        local request = temp.request
        temp.script:OnDestroy()
        request:Destroy()
        self.allEffect[bUuid] = nil
    end
    if self.OnCreateEffect[bUuid]~=nil then
        local request = self.OnCreateEffect[bUuid]
        request:Destroy()
        self.OnCreateEffect[bUuid] = nil
    end
end

local function ShowIsOnFireSignal(uuid)
    BuildFireEffectManager:GetInstance():CheckShowEffect(tonumber(uuid))
end

local function BuildOutViewSignal(uuid)
    BuildFireEffectManager:GetInstance():RemoveOneEffect(tonumber(uuid))
end

local function CheckShowEffect(self,bUuid)
    local info = DataCenter.WorldPointManager:GetBuildDataByUuid(bUuid)
    if info~=nil then
        if info.destroyStartTime>0 then
            self:RemoveOneEffect(bUuid)
        else
            local curTime = UITimeManager:GetInstance():GetServerTime()
            local needTime = info.fireEndTime
            if needTime~=nil and curTime < needTime then
                self:ShowBuildFireEffect(bUuid,info.mainIndex,WorldBuildUtil.GetBuildTile(info.mainIndex),needTime,info.itemId)
            else
                self:RemoveOneEffect(bUuid)
            end
        end
    end
end

local function TimeCallBack(bUuid)
    BuildFireEffectManager:GetInstance():RemoveOneEffect(bUuid)
end

BuildFireEffectManager.__init = __init
BuildFireEffectManager.__delete = __delete
BuildFireEffectManager.AddListener = AddListener
BuildFireEffectManager.RemoveListener = RemoveListener
BuildFireEffectManager.ShowIsOnFireSignal = ShowIsOnFireSignal
BuildFireEffectManager.BuildOutViewSignal = BuildOutViewSignal
BuildFireEffectManager.RemoveOneEffect = RemoveOneEffect
BuildFireEffectManager.CheckShowEffect = CheckShowEffect
--BuildFireEffectManager.OnBuildTrainingFinishSignal = OnBuildTrainingFinishSignal
BuildFireEffectManager.ShowBuildFireEffect = ShowBuildFireEffect
BuildFireEffectManager.TimeCallBack = TimeCallBack

return BuildFireEffectManager