---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2023/1/13 17:38
---
local UIDesertForceList = {
    Name = UIWindowNames.UIDesertForceList,
    Layer = UILayer.Normal,
    Ctrl = require "UI.UISeason.UIDesertForceList.Controller.UIDesertForceListCtrl",
    View = require "UI.UISeason.UIDesertForceList.View.UIDesertForceListView",
    PrefabPath = "Assets/Main/Prefabs/UI/UISeason/UIDesertForceList.prefab",
}

return {
    -- 配置
    UIDesertForceList = UIDesertForceList,
}