---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cola.
--- DateTime: 2022/11/4 下午5:50
---

local PlayerLevel = BaseClass("PlayerLevel")

function PlayerLevel:__init(player)
    self.player = player
    self:GetNextLevelExp()
end

function PlayerLevel:Destroy()
    self.player = nil
    self.nextLevelExp = nil
end 

function PlayerLevel:AddExp(message)
    if message["level"] then
        local level = message["level"]
        local curLevel = self.player.info:GetLevel()
        self.player.info:SetLevel(level)
        if (level > curLevel) then
            --todo:升级表现
            self:GetNextLevelExp()
            --SUSoundUtil.PlaySoundById(10001)
            UIUtil.ShowSUUserLevelUp()
            DataCenter.BluePrintTemplateManager:SetNewUnlockIds(level)
            EventManager:GetInstance():Broadcast(EventId.SU_PlayerLevelUp)
            DataCenter.GuideManager:CheckLMPlayerLevelGuide(level)
        end
    end
    local addExp = 0
    if message["addExp"] then
        addExp = message["addExp"]
        self.player.info:SetAddExp(addExp)
    end
    if message["exp"] then
        local exp = message["exp"]
        self.player.info:SetExp(exp)
    end
    EventManager:GetInstance():Broadcast(EventId.SU_PlayerExpChanged)
    self.player.info:SetAddExp(0)
end

function PlayerLevel:GetLevel()
    return self.player.info:GetLevel()
end

function PlayerLevel:GetAddExp()
    return self.player.info:GetAddExp()
end

function PlayerLevel:GetExp()
    return self.player.info:GetExp()
end

function PlayerLevel:GetCurLevelMaxExp()
    return self.nextLevelExp
end

function PlayerLevel:GetNextLevelExp()
    local levelTemplate = LocalController:instance():getLine(TableName.PlayerLevel, 101000 + self.player.info:GetLevel() + 1)
    if levelTemplate then
        self.nextLevelExp = tonumber(levelTemplate:getValue("exp")) or 0
    end
end

return PlayerLevel