---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zzl.
--- DateTime: 
---
local ActSevenLoginInfo = BaseClass("ActSevenLoginInfo")

local function __init(self)
    self.loginReward = {}
    self.lastReceiveTime = 0 --最后一次领取时间
end

local function __delete(self)
    self.loginReward = nil
    self.lastReceiveTime = nil
end

local function ParseLoginActs(self, message)
    if message==nil then
        return
    end
    self.loginReward = {}
    for i = 1 ,table.count(message) do
        local param = {}
        param.reward =  DataCenter.RewardManager:ReturnRewardParamForView(message[i]["reward"]) --奖励
        param.day = message[i]["day"]      --第几天
        param.state = message[i]["state"]  --0未领取 1已领取
        table.insert(self.loginReward,param)
    end
end

local function ParseLastTime(self,time)
    self.lastReceiveTime = time
end

--积分阶段奖励
local function SetDayState(self, day)
    if day==nil then
        return
    end
    if self.loginReward and next(self.loginReward) then
        for i = 1 ,table.count(self.loginReward) do
            if self.loginReward[i].day == day then
                self.loginReward[i].state = 1
            end
        end
    end
end

local function CheckToday(self)
    local curTime = UITimeManager:GetInstance():GetServerTime()
    if self.lastReceiveTime == 0 then
        --还没有领取过
        return 1
    else
        --上次领奖与现在是同一天，不可再领奖
        if UITimeManager:GetInstance():IsSameDayForServer(curTime // 1000, self.lastReceiveTime // 1000) then
            return 0
        else
            --上次领奖与现在不是同一天，查找可领奖的
            if self.loginReward and next(self.loginReward) then
                for i = 1 ,table.count(self.loginReward) do
                    if self.loginReward[i].state == 0 then
                        return self.loginReward[i].day
                    end
                end
            end
            --领完了
            return nil
        end
    end
end


ActSevenLoginInfo.__init = __init
ActSevenLoginInfo.__delete = __delete
ActSevenLoginInfo.ParseLoginActs = ParseLoginActs
ActSevenLoginInfo.ParseLastTime = ParseLastTime
ActSevenLoginInfo.SetDayState = SetDayState
ActSevenLoginInfo.CheckToday = CheckToday
return ActSevenLoginInfo