---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Beef.
--- DateTime: 2023/2/27 17:42
---

local UICommonStarTipCtrl = BaseClass("UICommonStarTipCtrl", UIBaseCtrl)

local function CloseSelf(self)
    UIManager:GetInstance():DestroyWindow(UIWindowNames.UICommonStarTip)
end

UICommonStarTipCtrl.CloseSelf = CloseSelf

return UICommonStarTipCtrl