---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guqu.
--- DateTime: 2020/11/16 19:22
---
local UIAllianceRankTable = {
    Name = UIWindowNames.UIAllianceRankTable,
    Layer = UILayer.Normal,
    Ctrl = require "UI.UIAlliance.UIAllianceRankTable.Controller.UIAllianceRankTableCtrl",
    View = require "UI.UIAlliance.UIAllianceRankTable.View.UIAllianceRankTableView",
    PrefabPath = "Assets/Main/Prefab_Dir/UI/Alliance/UIAllianceRankTable.prefab",
}

return {
    -- 配置
    UIAllianceRankTable = UIAllianceRankTable
}