---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2022/1/20 14:50
---
local MonsterRewardBoxEffect = BaseClass("MonsterRewardBoxEffect")
--创建
local function OnCreate(self,go)
    if go ~= nil then
        self.request = go
        self.gameObject = go.gameObject
        self.transform = go.gameObject.transform
    end
    self:ComponentDefine()
end

-- 销毁
local function OnDestroy(self)
    self:RemoveTimer()
    self:ComponentDestroy()
end

local function ComponentDefine(self)
    self.isDoAnim = false
    self.__update_handle = function() self:Update() end
    UpdateManager:GetInstance():AddUpdate(self.__update_handle)
end

local function ComponentDestroy(self)
end
local function RemoveTimer(self)
    if self.__update_handle~=nil then
        UpdateManager:GetInstance():RemoveUpdate(self.__update_handle)
        self.__update_handle = nil
    end

end

local function ReInit(self,param)
    self.data = param
    self:UpdatePosition(self.data.pointId)
    self.curTime =0
    self.isDoAnim = true
    self:Update()
end


local function Update(self)
    if self.isDoAnim then
        self.curTime = self.curTime+Time.deltaTime
        if self.curTime > 3 then
            self:RemoveTimer()
            MonsterRewardBoxEffectManager:GetInstance():RemoveOneEffect(self.data.pointId)
        end
    end
end

local function UpdatePosition(self,index)
    local worldPos = SceneUtils.TileIndexToWorld(index)
    self.transform.position = worldPos
end


MonsterRewardBoxEffect.OnCreate = OnCreate
MonsterRewardBoxEffect.OnDestroy = OnDestroy
MonsterRewardBoxEffect.ComponentDefine = ComponentDefine
MonsterRewardBoxEffect.ComponentDestroy = ComponentDestroy
MonsterRewardBoxEffect.Update = Update
MonsterRewardBoxEffect.RemoveTimer =RemoveTimer
MonsterRewardBoxEffect.ReInit = ReInit
MonsterRewardBoxEffect.UpdatePosition = UpdatePosition
return MonsterRewardBoxEffect