---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2021/11/8 15:34
---

local ActiveGolloesFuncMessage = BaseClass("ActiveGolloesFuncMessage", SFSBaseMessage)
local base = SFSBaseMessage
local Localization = CS.GameEntry.Localization
local function OnCreate(self,golloesParam,num)
    base.OnCreate(self)
    self.sfsObj:PutInt("type", golloesParam)
    if num then
        self.sfsObj:PutInt("num", num)
    end
end

local function HandleMessage(self, t)
    base.HandleMessage(self, t)
    local errCode =  t["errorCode"]
    if errCode ~= nil then
        --UIUtil.ShowTipsId(errCode) 
    else
        --UIUtil.ShowTipsId(320265) 
        DataCenter.GolloesCampManager:UpdateGolloesInfo(t)
    end
end

ActiveGolloesFuncMessage.OnCreate = OnCreate
ActiveGolloesFuncMessage.HandleMessage = HandleMessage

return ActiveGolloesFuncMessage