---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Beef.
--- DateTime: 2023/1/6 15:17
---

local ChainPayReceiveRewardMessage = BaseClass("ChainPayReceiveRewardMessage", SFSBaseMessage)
local base = SFSBaseMessage

local function OnCreate(self, actId, boxId)
    base.OnCreate(self)
    self.sfsObj:PutInt("activityId", actId)
    self.sfsObj:PutInt("id", boxId)
end

local function HandleMessage(self, t)
    base.HandleMessage(self, t)
    DataCenter.ChainPayManager:HandleReceiveReward(t)
end

ChainPayReceiveRewardMessage.OnCreate = OnCreate
ChainPayReceiveRewardMessage.HandleMessage = HandleMessage

return ChainPayReceiveRewardMessage