---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2022/7/7 15:54
---ClaimGolloesFreeRewardMessage

local ClaimGolloesFreeRewardMessage = BaseClass("ClaimGolloesFreeRewardMessage", SFSBaseMessage)
local base = SFSBaseMessage
local Localization = CS.GameEntry.Localization
local function OnCreate(self)
    base.OnCreate(self)
end

local function HandleMessage(self, t)
    base.HandleMessage(self, t)
    local errCode =  t["errorCode"]
    if errCode ~= nil then
        UIUtil.ShowTipsId(errCode)
    else
        if not t["reward"] then
            t["reward"] = {}
        end
        DataCenter.RewardManager:ShowCommonReward(t, Localization:GetString(320337))
        DataCenter.MonthCardNewManager:UpdateMonthCardData(t)
    end
end

ClaimGolloesFreeRewardMessage.OnCreate = OnCreate
ClaimGolloesFreeRewardMessage.HandleMessage = HandleMessage

return ClaimGolloesFreeRewardMessage