---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2021/11/24 14:40
---

--GiveUpAlCityMessage

local GiveUpAlCityMessage = BaseClass("GiveUpAlCityMessage", SFSBaseMessage)
-- 基类，用来调用基类方法
local base = SFSBaseMessage
local Localization = CS.GameEntry.Localization
local function OnCreate(self, cityId, isCancel)
    base.OnCreate(self)
    self.sfsObj:PutInt("cityId", cityId)
    self.sfsObj:PutBool("isCancel", isCancel)
end

local function HandleMessage(self, t)
    base.HandleMessage(self, t)
    local errCode =  t["errorCode"]
    if errCode ~= nil then
        UIUtil.ShowTipsId(errCode) 
    else
        DataCenter.WorldAllianceCityDataManager:UpdateOneGivingUpCity(t)
    end
end

GiveUpAlCityMessage.OnCreate = OnCreate
GiveUpAlCityMessage.HandleMessage = HandleMessage

return GiveUpAlCityMessage