---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2023/4/17 14:32
---
local MigrateToServerMessage = BaseClass("MigrateToServerMessage", SFSBaseMessage)
local base = SFSBaseMessage
local Localization = CS.GameEntry.Localization
local function OnCreate(self,toServerId,toPointId)
    base.OnCreate(self)
    self.sfsObj:PutInt("toServerId",toServerId)
    self.sfsObj:PutInt("toPointId",toPointId)
end
local function HandleMessage(self, t)
    base.HandleMessage(self, t)
    EventManager:GetInstance():Broadcast(EventId.OnSetMigratingUI,UIMigrateType.Close)
    local errCode =  t["errorCode"]
    if errCode ~= nil then
        UIUtil.ShowTipsId(errCode)
    else
        if t["serverInfo"]~=nil then
            local message = t["serverInfo"]
            Setting:SetString(SettingKeys.SERVER_IP, message["ip"])
            Setting:SetInt(SettingKeys.SERVER_PORT, message["port"])
            Setting:SetString(SettingKeys.SERVER_ZONE, message["zone"])
        end
        CS.ApplicationLaunch.Instance:ReStartGame()
    end
end

MigrateToServerMessage.OnCreate = OnCreate
MigrateToServerMessage.HandleMessage = HandleMessage

return MigrateToServerMessage