---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Beef.
--- DateTime: 2023/3/29 16:22
---

local PushBuildingStatusDelMessage = BaseClass("PushBuildingStatusDelMessage", SFSBaseMessage)
local base = SFSBaseMessage

local function OnCreate(self)
    base.OnCreate(self)
end

local function HandleMessage(self, t)
    base.HandleMessage(self, t)
    DataCenter.BuildStatusManager:HandleDel(t)
end

PushBuildingStatusDelMessage.OnCreate = OnCreate
PushBuildingStatusDelMessage.HandleMessage = HandleMessage

return PushBuildingStatusDelMessage