---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2023/3/3 17:54
---
local PushFoldAlFortressTimeMessage = BaseClass("PushFoldAlFortressTimeMessage", SFSBaseMessage)
-- 基类，用来调用基类方法
local base = SFSBaseMessage
local Localization = CS.GameEntry.Localization
local function OnCreate(self)
    base.OnCreate(self)
end

local function HandleMessage(self, t)
    base.HandleMessage(self, t)
    local errCode =  t["errorCode"]
    if errCode ~= nil then
        UIUtil.ShowTipsId(errCode)
    else
        DataCenter.AllianceMineManager:RefreshAllianceFrontTime(t)
    end
end

PushFoldAlFortressTimeMessage.OnCreate = OnCreate
PushFoldAlFortressTimeMessage.HandleMessage = HandleMessage

return PushFoldAlFortressTimeMessage