---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2023/4/26 14:56
---
local PushDeclareWarExitAllianceRecordMessage = BaseClass("PushDeclareWarExitAllianceRecordMessage", SFSBaseMessage)
local base = SFSBaseMessage
local function OnCreate(self)
    base.OnCreate(self)
end

local function HandleMessage(self, t)
    base.HandleMessage(self, t)
    DataCenter.GloryManager:InitQuitAllianceTime(t)
end

PushDeclareWarExitAllianceRecordMessage.OnCreate = OnCreate
PushDeclareWarExitAllianceRecordMessage.HandleMessage = HandleMessage

return PushDeclareWarExitAllianceRecordMessage