---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2023/1/10 11:46
---

local RefreshDisCountShopMessage = BaseClass("RefreshDisCountShopMessage", SFSBaseMessage)
local base = SFSBaseMessage

local function OnCreate(self, activityId)
    base.OnCreate(self)
    self.sfsObj:PutInt("activityId", activityId)
end

local function HandleMessage(self, t)
    base.HandleMessage(self, t)
    DataCenter.LuckyShopManager:RefreshShopHandler(t)
end

RefreshDisCountShopMessage.OnCreate = OnCreate
RefreshDisCountShopMessage.HandleMessage = HandleMessage

return RefreshDisCountShopMessage