---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2022/9/23 17:32
---
local WorldMarchFormationNewMessage = BaseClass("WorldMarchFormationNewMessage", SFSBaseMessage)
local base = SFSBaseMessage
local Localization = CS.GameEntry.Localization

local function OnCreate(self,formationUuid,target,targetUid,path,worldId,waitTimeIndex,autoBackHome,formationParam,targetServer,destroyTimeIndex,useWormHole,wormUuid)
    base.OnCreate(self)
    self.sfsObj:PutLong("formationUuid", formationUuid)
    self.sfsObj:PutInt("target", target)
    self.sfsObj:PutLong("targetUid",targetUid)
    if path~=nil and path ~="" then
        self.sfsObj:PutUtfString("path", path)
    end
    self.sfsObj:PutInt("worldId",worldId)
    self.sfsObj:PutInt("waitTimeIndex",waitTimeIndex)
    self.sfsObj:PutBool("autoBackHome",autoBackHome)
    if formationParam~=nil then
        self.sfsObj:PutSFSObject("formationParam",formationParam)
    end
    if targetServer>0 then
        self.sfsObj:PutInt("targetServer",targetServer)
    end
    if destroyTimeIndex>0 then
        self.sfsObj:PutInt("destroyTimeIndex",destroyTimeIndex)
    end
    if useWormHole~=nil then
        self.sfsObj:PutBool("useWormHole",useWormHole)
    end
    if wormUuid>0 then
        self.sfsObj:PutLong("wormUuid",wormUuid)
    end
end

local function HandleMessage(self, t)
    base.HandleMessage(self, t)
    local errCode =  t["errorCode"]
    if errCode ~= nil then
        UIUtil.ShowTipsId(errCode)
    else
        DataCenter.WorldMarchDataManager:HandleFormationMarch(t)
    end
end

WorldMarchFormationNewMessage.OnCreate = OnCreate
WorldMarchFormationNewMessage.HandleMessage = HandleMessage

return WorldMarchFormationNewMessage