---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zzl.
--- DateTime:
---
local VsInfoArr = BaseClass("VsInfoArr")

local function __init(self)
    self.allianceId = 0
    self.serverId = 0   --联盟所属服
    self.name = ""
    self.icon = ""
    self.abbr =""
    self.mainNum = 0    --主力人数
    self.battleNum = 0 -- 战场内人数
    self.side = 0        --0红方 1蓝方
    self.strength = 0
    self.score = 0
end

local function __delete(self)
    self.allianceId = 0
    self.serverId = 0
    self.name = ""
    self.icon = ""
    self.abbr =""
    self.mainNum = 0
    self.battleNum = 0
    self.side = 0
    self.strength = 0
    self.score = 0
end

local function ParseData(self, message)
    if message==nil then
        return
    end
    if message["allianceId"]~=nil then
        self.allianceId = message["allianceId"]
    end
    if message["serverId"]~=nil then
        self.serverId = message["serverId"]
    end
    if message["name"]~=nil then
        self.name = message["name"]
    end
    if message["icon"]~=nil then
        self.icon = message["icon"]
    end
    if message["signUp"]~=nil then
        self.signUp = message["signUp"]
    end
    if message["abbr"]~=nil then
        self.abbr = message["abbr"]
    end
    if message["mainNum"]~=nil then
        self.mainNum = message["mainNum"]
    end

    if message["battleNum"]~=nil then
        self.battleNum = message["battleNum"]
    end

    if message["side"]~=nil then
        self.side = message["side"]
    end
    if message["strength"] then
        self.strength = message["strength"]
    end
    if message["score"] then
        self.score = message["score"]
    end
end

VsInfoArr.__init = __init
VsInfoArr.__delete = __delete
VsInfoArr.ParseData = ParseData
return VsInfoArr