---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2022/12/13 15:36
---


local EffectDesc = BaseClass("EffectDesc", UIBaseContainer)
local base = UIBaseContainer

local quality_path = "QualityBg/QualityText"
local name_path = "NameText"
local use_title_path = "UseTitle"
local use_effect_path = "UseEffect"

local own_title_path = "OwnTitle"
local own_effect_path = "OwnEffect"
local quality_bg_path= "QualityBg"
local get_text_path= "QualityBg/GetText"
--创建
local function OnCreate(self)
    base.OnCreate(self)
    self:ComponentDefine()
    self:DataDefine()
end

-- 销毁
local function OnDestroy(self)
    self:ComponentDestroy()
    self:DataDestroy()
    base.OnDestroy(self)
end

local function ComponentDefine(self)
    self.quality = self:AddComponent(UITextMeshProUGUIEx, quality_path)
    self.name = self:AddComponent(UITextMeshProUGUIEx, name_path)
    self.use_title = self:AddComponent(UITextMeshProUGUIEx, use_title_path)
    self.use_title:SetLocalText(320564)

    self.use_effect = self:AddComponent(UITextMeshProUGUIEx, use_effect_path)
    self.own_title = self:AddComponent(UITextMeshProUGUIEx, own_title_path)
    self.own_effect = self:AddComponent(UITextMeshProUGUIEx, own_effect_path)
    self.own_title:SetLocalText(320565)
    
    self.quality_bg = self:AddComponent(UIImage, quality_bg_path)
    self.get_text = self:AddComponent(UITextMeshProUGUIEx, get_text_path)
end

local function ComponentDestroy(self)

end

local function DataDefine(self)

end

local function DataDestroy(self)

end

local function OnEnable(self)
    base.OnEnable(self)
end

local function OnDisable(self)
    base.OnDisable(self)
end

local function ReInit(self, data)
    self.data = data
    self:RefreshView()
end

local function RefreshView(self)
    self.quality:SetText(self.data.quality)
    self.name:SetText(self.data.name)
    self.name:SetColor(self.data.color)
    self.quality_bg:LoadSprite(self.data.qualityBg)
    if string.IsNullOrEmpty(self.data.useEffect) then
        self.use_title:SetActive(false)
        self.use_effect:SetActive(false)
    else
        self.use_title:SetActive(true)
        self.use_effect:SetActive(true)
        self.use_effect:SetText(self.data.useEffect)
    end
    if string.IsNullOrEmpty(self.data.ownEffect) then
        self.own_title:SetActive(false)
        self.own_effect:SetActive(false)
    else
        self.own_title:SetActive(true)
        self.own_effect:SetActive(true)
        self.own_effect:SetText(self.data.ownEffect)
    end
    if self.data.gain_desc ~= nil then
        self.get_text:SetActive(true)
        self.get_text:SetText(self.data.gain_desc)
    else
        self.get_text:SetActive(false)
    end
  
    CS.UnityEngine.UI.LayoutRebuilder.ForceRebuildLayoutImmediate(self.rectTransform)
end

EffectDesc.OnCreate = OnCreate
EffectDesc.OnDestroy = OnDestroy
EffectDesc.OnEnable = OnEnable
EffectDesc.OnDisable = OnDisable
EffectDesc.ComponentDefine = ComponentDefine
EffectDesc.ComponentDestroy = ComponentDestroy
EffectDesc.DataDefine = DataDefine
EffectDesc.DataDestroy = DataDestroy
EffectDesc.ReInit = ReInit
EffectDesc.RefreshView = RefreshView

return EffectDesc