---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Beef.
--- DateTime: 2023/11/3 11:24
---

local ResidentSetFoodMessage = BaseClass("ResidentSetFoodMessage", SFSBaseMessage)
local base = SFSBaseMessage

local function OnCreate(self, foodType)
    base.OnCreate(self)
    
    self.sfsObj:PutInt("foodType", foodType)
end

local function HandleMessage(self, t)
    base.HandleMessage(self, t)
    
    if t["errorCode"] == nil then
        DataCenter.VitaManager:HandleSetFoodType(t)
    end
end

ResidentSetFoodMessage.OnCreate = OnCreate
ResidentSetFoodMessage.HandleMessage = HandleMessage

return ResidentSetFoodMessage