---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Beef.
--- DateTime: 2024/1/3 17:58
---

local ParkourHeroHead = BaseClass("ParkourHeroHead", UIBaseContainer)
local base = UIBaseContainer
local UIGray = CS.UIGray

local this_path = ""
local normal_path = "Normal"
local hero_path = "Normal/Mask/Hero"
local black_path = "Normal/Mask/Black"
local frame_path = "Normal/Frame"
local time_path = "Normal/Time"
local slider_path = "Normal/Slider"
local skill_path = "SkillBg/Skill"

local function OnCreate(self)
    base.OnCreate(self)
    self:DataDefine()
    self:ComponentDefine()
end

local function OnDestroy(self)
    self:ComponentDestroy()
    self:DataDestroy()
    base.OnDestroy(self)
end

local function ComponentDefine(self)
    self.btn = self:AddComponent(UIButton, this_path)
    self.btn:SetOnClick(function()
        self:OnClick()
    end)
    self.anim = self:AddComponent(UIAnimator, this_path)
    self.normal_go = self:AddComponent(UIBaseContainer, normal_path)
    self.hero_image = self:AddComponent(UIImage, hero_path)
    self.black_image = self:AddComponent(UIImage, black_path)
    self.frame_image = self:AddComponent(UIImage, frame_path)
    self.time_text = self:AddComponent(UITextMeshProUGUIEx, time_path)
    self.slider = self:AddComponent(UISlider, slider_path)
    self.skill_image = self:AddComponent(UIImage, skill_path)
end

local function ComponentDestroy(self)
    
end

local function DataDefine(self)
    self.isDead = false
    self.usingSkill = false
    self.cd = 0
    self.maxCd = IntMaxValue
end

local function DataDestroy(self)
    
end

local function OnEnable(self)
    base.OnEnable(self)
end

local function OnDisable(self)
    base.OnDisable(self)
end

local function OnAddListener(self)
    base.OnAddListener(self)
end

local function OnRemoveListener(self)
    base.OnRemoveListener(self)
end

local function SetHeroId(self, heroId)
    self.isDead = false
    self.cd = self.maxCd
    self.heroId = heroId
    self.normal_go:SetActive(true)
    local icon = HeroUtils.GetHeroIconPath(heroId)
    local rarity = GetTableData(HeroUtils.GetHeroXmlName(), heroId, "rarity")
    self.hero_image:LoadSprite(icon)
    self.frame_image:LoadSprite(string.format(LoadPath.UIPve, "pve_fight_frame_" .. rarity))
    self.black_image:SetFillAmount(0)
    self.time_text:SetText("")
    self.slider:SetValue(1)
    UIGray.SetGray(self.hero_image.transform, false)
    self.anim:Play("Eff_UI_Common_Skill_Loop", 0, 0)
end

local function SetHp(self, cur, max)
    local val = Mathf.Clamp(cur / max, 0, 1)
    self.slider:SetValue(val)
    if cur <= 0 then
        self.isDead = true
        self.black_image:SetFillAmount(0)
        self.time_text:SetText("")
        UIGray.SetGray(self.hero_image.transform, true)
    else
        self.isDead = false
    end
end

local function SetCd(self, cd, maxCd)
    self.cd = cd
    if maxCd then
        self.maxCd = maxCd
    end
    self.black_image:SetFillAmount(self.cd / self.maxCd)
    self.time_text:SetText(string.format("%.1f", self.cd))
end

local function UseSkill(self, icon)
    self.skill_image:LoadSprite(icon)
    self.anim:Play("Eff_UI_Common_Skill_Switch", 0, 0)
end

local function OnClick(self, data)
    
end

ParkourHeroHead.OnCreate= OnCreate
ParkourHeroHead.OnDestroy = OnDestroy
ParkourHeroHead.ComponentDefine = ComponentDefine
ParkourHeroHead.ComponentDestroy = ComponentDestroy
ParkourHeroHead.DataDefine = DataDefine
ParkourHeroHead.DataDestroy = DataDestroy
ParkourHeroHead.OnEnable = OnEnable
ParkourHeroHead.OnDisable = OnDisable
ParkourHeroHead.OnAddListener = OnAddListener
ParkourHeroHead.OnRemoveListener = OnRemoveListener

ParkourHeroHead.SetHeroId = SetHeroId
ParkourHeroHead.SetHp = SetHp
ParkourHeroHead.SetCd = SetCd
ParkourHeroHead.UseSkill = UseSkill
ParkourHeroHead.OnClick = OnClick

return ParkourHeroHead