---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2022/11/15 15:27
---

local HeroLackTipsItemBase = require "DataCenter.HeroLackTipManager.HeroLackTipsItemBase"
local HeroLackTipsItemPromotionGiftBag = BaseClass("HeroLackTipsItemPromotionGiftBag", HeroLackTipsItemBase)

local function CheckIsOk(self)
    local eventUuid = self:GetDetectEvent()
    return eventUuid ~= nil
end

local function TodoAction(self)
    local eventUuid = self:GetDetectEvent()
    if eventUuid ~= nil then
        UIManager.Instance:DestroyWindow(UIWindowNames.UIHeroList)
        UIManager.Instance:DestroyWindow(UIWindowNames.UIHeroInfo)
        UIManager.Instance:DestroyWindow(UIWindowNames.UIHeroAdvanceSuccess)

        UIManager:GetInstance():OpenWindow(UIWindowNames.UIDetectEvent, eventUuid)
    end
end

local function GetDetectEvent(self)
    local template = DataCenter.HeroLackTipTemplateManager:GetTemplate(self.configId)
    if template == nil then
        return nil
    end
    local uuids = DataCenter.RadarCenterDataManager:GetDetectEventInfoUuids()
    for _, v in ipairs(uuids) do
        local info = DataCenter.RadarCenterDataManager:GetDetectEventInfo(v)
        if info ~= nil then
            local eventType = DataCenter.DetectEventTemplateManager:GetTableValue(info.eventId,"type")
            if eventType ~= nil and eventType == toInt(template.para1) then
                return v
            end
        end
    end
    return nil
end

HeroLackTipsItemPromotionGiftBag.CheckIsOk = CheckIsOk
HeroLackTipsItemPromotionGiftBag.TodoAction = TodoAction
HeroLackTipsItemPromotionGiftBag.GetDetectEvent = GetDetectEvent

return HeroLackTipsItemPromotionGiftBag