---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zzl.
--- DateTime:
---
local UIDeclareWarListCtrl = BaseClass("UIDeclareWarListCtrl", UIBaseCtrl)

local function CloseSelf(self)
    UIManager.Instance:DestroyWindow(UIWindowNames.UIDeclareWarList)
end

--获取字符串个数
local function GetStringCharCount(self,str)
    local lenInByte = #str
    local i = 1
    local result = 0
    while (i <= lenInByte)
    do
        local curByte = string.byte(str, i)
        local byteCount = 1;
        if curByte > 0 and curByte <= 127 then
            byteCount = 1                                               --1字节字符
        elseif curByte >= 192 and curByte < 223 then
            byteCount = 2                                               --双字节字符
        elseif curByte >= 224 and curByte < 239 then
            byteCount = 3                                               --汉字
        elseif curByte >= 240 and curByte <= 247 then
            byteCount = 4                                               --4字节字符
        end
        i = i + byteCount
        result=result+1						-- 重置下一字节的索引
    end         			               -- 字符的个数（长度）
    return result
end

UIDeclareWarListCtrl.CloseSelf = CloseSelf
UIDeclareWarListCtrl.GetStringCharCount = GetStringCharCount
return UIDeclareWarListCtrl