---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 8/12/21 9:44 PM
---



local UISettingAccount = {
    Name = UIWindowNames.UISettingAccount,
    Layer = UILayer.Normal,
    Ctrl = require "UI.UIAccount2.UISettingAccount.Controller.UISettingAccountCtrl",
    View = require "UI.UIAccount2.UISettingAccount.View.UISettingAccount",
    PrefabPath = "Assets/Main/Prefab_Dir/UI/UIAccount/UISettingAccount.prefab"
}

return {
    -- 配置
    UISettingAccount = UISettingAccount,
}