---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Beef.
--- DateTime: 2023/11/23 10:52
---

local CityResidentStateBase = require "DataCenter.CityResident.CityResidentState.CityResidentStateBase"
local CityResidentStateGoToIdle = BaseClass("CityResidentStateGoToIdle", CityResidentStateBase)

local function OnEnter(self)
    local lastState = self.data:GetLastState()
    self.data.idleFurnitureId = nil
    local ran = math.random(1, 4)
    if ran == 1 and lastState ~= CityResidentDefines.State.PlayPool then
        -- 前往水池
        self.data.idleFurnitureId = FurnitureType.Pool
    elseif ran == 2 and lastState ~= CityResidentDefines.State.PlayDesk then
        -- 前往书桌
        self.data.idleFurnitureId = FurnitureType.Desk
    elseif ran == 3 and lastState ~= CityResidentDefines.State.Shit then
        -- 前往拉屎
        self.data.idleFurnitureId = FurnitureType.Toilet
    else
        -- 闲逛
    end
    if self.data.idleFurnitureId then
        local tf, fUuid = DataCenter.CityResidentManager.occupyMgr:TryOccupyFurnitureTransform(self.data.uuid, self.data.idleFurnitureId)
        if tf then
            local furnitureInfo = DataCenter.FurnitureManager:GetFurnitureByUuid(fUuid)
            if furnitureInfo then
                self.data:SetAutoAnim(true)
                self.data:GoToBuildingPos(furnitureInfo.bUuid, tf.position, true)
                return
            end
        end
    end

    -- 闲逛
    local mask = DataCenter.CityResidentManager:GetCurrentCityMask()
    local pos = WayPointUtil.GetRandomPos(mask, CityResidentDefines.WayPointFlag.Center)
    self.data:SetAutoAnim(true)
    self.data:GoToCityPos(pos)
    self.data:ShowTool("")
    self.data.idleFurnitureId = nil
    
    -- 罢工
    if self.data.residentData:IsStrike() then
        -- 小人说话
        local param = {}
        param.type = CityResidentDefines.TalkTriggerType.Strike
        param.rUuid = self.data.uuid
        DataCenter.CityResidentManager:TryResidentTalk(param)
    end
end

local function OnFinish(self)
    if self.data.idleFurnitureId == FurnitureType.Pool then
        self.data:SetState(CityResidentDefines.State.PlayPool)
    elseif self.data.idleFurnitureId == FurnitureType.Desk then
        self.data:SetState(CityResidentDefines.State.PlayDesk)
    elseif self.data.idleFurnitureId == FurnitureType.Toilet then
        self.data:SetState(CityResidentDefines.State.Shit)
    else
        self.data:SetState(CityResidentDefines.State.Idle)
    end
    self.data.idleFurnitureId = nil
end

CityResidentStateGoToIdle.OnEnter = OnEnter
CityResidentStateGoToIdle.OnFinish = OnFinish

return CityResidentStateGoToIdle