---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 2021/6/17 下午3:08
---


---
--- 英雄预览页面
--[[
-- 模块窗口配置，要使用还需要导出到UI.Config.UIConfig.lua
-- 一个模块可以对应多个窗口，每个窗口对应一个配置项
-- 使用范例：
-- 窗口配置表 ={
--		名字Name
--		UI层级Layer
-- 		控制器类Controller
--		模型类Model
--		视图类View
--		资源加载路径PrefabPath
-- } 
--]]

-- 窗口配置
local UIHeroInfo = {
    Name = UIWindowNames.UIHeroInfo,
    Layer = UILayer.Normal,
    Ctrl = require "UI.UIHero2.UIHeroInfo.Controller.UIHeroInfoCtrl",
    View = require "UI.UIHero2.UIHeroInfo.View.UIHeroInfoView",
    PrefabPath = "Assets/Main/Prefabs/UI/UIHero/New/UIHeroInfo.prefab",
}

return {
    -- 配置
    UIHeroInfo = UIHeroInfo,
}