---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Beef.
--- DateTime: 2022/7/29 12:22
---

local UIHeroOfficialDetailTip = BaseClass("UIHeroOfficialDetailTip", UIBaseContainer)
local base = UIBaseContainer
local Localization = CS.GameEntry.Localization

local close_path = "Close"
local root_path = "Root"
local desc_path = "Root/Bg/Desc"
local arrow_path = "Root/Arrow"

local function OnCreate(self)
    base.OnCreate(self)
    self:DataDefine()
    self:ComponentDefine()
end

local function OnDestroy(self)
    self:ComponentDestroy()
    self:DataDestroy()
    base.OnDestroy(self)
end

local function ComponentDefine(self)
    self.root_anim = self:AddComponent(UIAnimator, root_path)
    self.close_btn = self:AddComponent(UIButton, close_path)
    self.close_btn:SetOnClick(function()
        self:OnCloseClick()
    end)
    self.desc_text = self:AddComponent(UITextMeshProUGUIEx, desc_path)
    self.arrow_go = self:AddComponent(UIBaseContainer, arrow_path)
end

local function ComponentDestroy(self)
    self.root_anim = nil
    self.close_btn = nil
    self.desc_text = nil
    self.arrow_go = nil
end

local function DataDefine(self)
    
end

local function DataDestroy(self)
    
end

local function OnEnable(self)
    base.OnEnable(self)
end

local function OnDisable(self)
    base.OnDisable(self)
end

local function SetData(self, str)
    self.desc_text:SetText(str)

    -- unity problem
    TimerManager:GetInstance():DelayInvoke(function()
        if self.root_anim ~= nil then
            CS.UnityEngine.UI.LayoutRebuilder.ForceRebuildLayoutImmediate(self.root_anim.rectTransform)
        end
    end, 0.05)
end

local function Show(self)
    self:SetActive(true)
    self.root_anim:Play("CommonPopup_movein", 0, 0)
end

local function OnCloseClick(self)
    self:SetActive(false)
end

UIHeroOfficialDetailTip.OnCreate= OnCreate
UIHeroOfficialDetailTip.OnDestroy = OnDestroy
UIHeroOfficialDetailTip.ComponentDefine = ComponentDefine
UIHeroOfficialDetailTip.ComponentDestroy = ComponentDestroy
UIHeroOfficialDetailTip.DataDefine = DataDefine
UIHeroOfficialDetailTip.DataDestroy = DataDestroy
UIHeroOfficialDetailTip.OnEnable = OnEnable
UIHeroOfficialDetailTip.OnDisable = OnDisable

UIHeroOfficialDetailTip.SetData = SetData
UIHeroOfficialDetailTip.Show = Show
UIHeroOfficialDetailTip.OnCloseClick = OnCloseClick

return UIHeroOfficialDetailTip