---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1020.
--- DateTime: 2023/5/23 14:47
---

local ScratchOffLucyRewardItem = BaseClass("ScratchOffLucyRewardItem", UIBaseContainer)
local base = UIBaseContainer
local ScratchOffLucyRewardContentItem = require "UI.UIScratchOffRewardDetailPage.Comp.ScratchOffLucyRewardContentItem"

local titleBg_path = "titleBg"
local titleTxt_path = "titleBg/titleTxt"
local contentItem_path = "contentItem"

local contentItemMaxNum = 5

-- 创建
function ScratchOffLucyRewardItem : OnCreate()
    base.OnCreate(self)
    self:DataDefine()
    self:ComponentDefine()
end

-- 销毁
function ScratchOffLucyRewardItem : OnDestroy()
    self:ComponentDestroy()
    self:DataDestroy()
    base.OnDestroy(self)
end

function ScratchOffLucyRewardItem : DataDefine()
    self.contentItemList = {}
end

function ScratchOffLucyRewardItem : DataDestroy()
    self.contentItemList = nil
end

function ScratchOffLucyRewardItem : ComponentDefine()
    self.titleBg = self:AddComponent(UIImage, titleBg_path)
    self.titleTxt = self:AddComponent(UIText, titleTxt_path)

    for i = 1, contentItemMaxNum do
        local item = self:AddComponent(ScratchOffLucyRewardContentItem, contentItem_path..i)
        table.insert(self.contentItemList, item)
    end
end

function ScratchOffLucyRewardItem : ComponentDestroy()
    
end

function ScratchOffLucyRewardItem : SetData(itemInfo)
    if itemInfo == nil then
        return
    end
    local titleBgPath = self:GetTitleBgPathByLevel(tonumber(itemInfo.level))
    self.titleBg:LoadSprite(titleBgPath)
    self.titleTxt:SetLocalText(itemInfo.levelTxtNum)
    for i = 1, contentItemMaxNum do
        if i <= #itemInfo.luckyIconList then
            self.contentItemList[i]:SetActive(true)
            self.contentItemList[i]:SetData(itemInfo.luckyIconList[i])
        else
            self.contentItemList[i]:SetActive(false)
        end
    end
end

function ScratchOffLucyRewardItem : GetTitleBgPathByLevel(level)
    local path = ""
    if level == 1 then
        path = "Assets/Main/Sprites/UI/CommonBG/UIReward_ranking_bg_title_01"
    elseif level == 2 then
        path = "Assets/Main/Sprites/UI/CommonBG/UIReward_ranking_bg_title_02"
    elseif level == 3 then
        path = "Assets/Main/Sprites/UI/CommonBG/UIReward_ranking_bg_title_03"
    elseif level == 4 then
        path = "Assets/Main/Sprites/UI/CommonBG/UIReward_ranking_bg_title_03"
    elseif level == 5 then
        path = "Assets/Main/Sprites/UI/CommonBG/UIReward_ranking_bg_title_03"
    end
    return path
end

return ScratchOffLucyRewardItem