---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Beef.
--- DateTime: 2023/11/14 21:03
---

local UIVitaMatter =
{
    Name = UIWindowNames.UIVitaMatter,
    Layer = UILayer.UIResource,
    Ctrl = require "UI.UIVita.UIVitaMatter.Controller.UIVitaMatterCtrl",
    View = require "UI.UIVita.UIVitaMatter.View.UIVitaMatterView",
    PrefabPath = "Assets/Main/Prefab_Dir/UI/UIVita/UIVitaMatter.prefab",
}

return
{
    UIVitaMatter = UIVitaMatter,
}