---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2023/3/20 21:42
---
local UIAssistanceThrone = {
    Name = UIWindowNames.UIAssistanceThrone,
    Layer = UILayer.Normal,
    Ctrl = require "UI.UIAssistanceThrone.Controller.UIAssistanceThroneCtrl",
    View = require "UI.UIAssistanceThrone.View.UIAssistanceThroneView",
    PrefabPath = "Assets/Main/Prefab_Dir/UI/Alliance/UIAssistanceThroneMain.prefab",
}

return {
    -- 配置
    UIAssistanceThrone = UIAssistanceThrone,
}