---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Beef.
--- DateTime: 2023/9/1 14:45
---

local PushStoryTimeUpdateMessage = BaseClass("PushStoryTimeUpdateMessage", SFSBaseMessage)
local base = SFSBaseMessage

local function OnCreate(self)
    base.OnCreate(self)
end

local function HandleMessage(self, t)
    base.HandleMessage(self, t)
    DataCenter.StoryManager:HandleUpdateHangupTime(t)
end

PushStoryTimeUpdateMessage.OnCreate = OnCreate
PushStoryTimeUpdateMessage.HandleMessage = HandleMessage

return PushStoryTimeUpdateMessage