---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2022/4/22 19:48
---
local UIWorldBossTroopCell = BaseClass("UIWorldBossTroopCell",UIBaseContainer)
local base = UIBaseContainer
local Localization = CS.GameEntry.Localization
local name_txt_path = "left/NameTxt"
local pos_txt_path = "left/posBg/posTxt"
local img_path = "left/Image"
local slider_path = "sliderBg/Slider"
local slider_des_path = "sliderBg/progressTxt"
local percent_txt_path = "sliderBg/percentTxt"
local distance_txt_path = "left/distanceBg/distanceTxt"
local button_path = "gotoBtn"
local btn_txt_path = "gotoBtn/btnTxt"
local function OnCreate(self)
    base.OnCreate(self)
    self.name_txt = self:AddComponent(UIText,name_txt_path)
    self.pos_txt = self:AddComponent(UIText,pos_txt_path)
    self.slider = self:AddComponent(UISlider,slider_path)
    self.slider_des = self:AddComponent(UIText,slider_des_path)
    self.percent_txt = self:AddComponent(UIText,percent_txt_path)
    self.distance_txt = self:AddComponent(UIText,distance_txt_path)
    self.btn = self:AddComponent(UIButton,button_path)
    self.btn:SetOnClick(function()
        self:OnGotoClick()
    end)
    self.btn_txt = self:AddComponent(UIText,btn_txt_path)
    self.slider_des:SetLocalText(311058)
    self.btn_txt:SetLocalText(110003)
end

local function SetItemShow(self, data)
    self.data = data
    local name  = DataCenter.MonsterTemplateManager:GetTableValue(self.data.monsterId,"name")
    self.name_txt:SetLocalText(name)
    self.distance_txt:SetText(string.GetFormattedSeperatorNum(math.ceil(self.data.distance)).."km")
    local pos = SceneUtils.IndexToTilePos(self.data.startPos)
    self.pos_txt:SetText(Localization:GetString(GameDialogDefine.SHOW_POS,pos.x,pos.y))
    self:SetBloodSlider(self.data.armyHealth,self.data.armyInitHealth)
end

local function OnAddListener(self)
    base.OnAddListener(self)
    self:AddUIListener(EventId.ShowActBossBattleValue, self.UpdateActBossBlood)
end


local function OnRemoveListener(self)
    base.OnRemoveListener(self)
    self:RemoveUIListener(EventId.ShowActBossBattleValue, self.UpdateActBossBlood)
end

local function SetBloodSlider(self,curBlood,maxBlood)
    local tempValue = math.min((curBlood / math.max(maxBlood,1)),1)
    self.slider:SetValue(tempValue)
    self.percent_txt:SetText(string.GetFormattedPercentStr(tempValue))
end
local function OnGotoClick(self)
    local pos = self.data.startPos
    GoToUtil.GotoWorldPos(SceneUtils.TileIndexToWorld(pos),CS.SceneManager.World.InitZoom,LookAtFocusTime)
    GoToUtil.CloseAllWindows()
end

local function UpdateActBossBlood(self,data)
    if data~=nil then
        local strArr = string.split(data,";")
        if #strArr>=4 then
            local uuid = tonumber(strArr[1])
            if uuid~=0 and uuid == self.ctrl.uuid then
                local initBlood = tonumber(strArr[4])
                local curBlood= tonumber(strArr[3])
                self:SetBloodSlider(curBlood,initBlood)
            end
        end
    end
end
UIWorldBossTroopCell.OnCreate = OnCreate
UIWorldBossTroopCell.SetItemShow = SetItemShow
UIWorldBossTroopCell.OnGotoClick = OnGotoClick
UIWorldBossTroopCell.SetBloodSlider = SetBloodSlider
UIWorldBossTroopCell.OnAddListener =OnAddListener
UIWorldBossTroopCell.OnRemoveListener =OnRemoveListener
UIWorldBossTroopCell.UpdateActBossBlood =UpdateActBossBlood

return UIWorldBossTroopCell