---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2021/12/9 16:36
---
local UIWorldSiegeRewardCell = BaseClass("UIWorldSiegeRewardCell", UIBaseContainer)
local RewardItem = require "UI.UIWorldSiegePoint.Component.UIWorldSiegeRewardItem"
local base = UIBaseContainer
local Localization = CS.GameEntry.Localization
local des_txt_path = "desTxt"
local reward_content_path = "rewardContent"
-- 创建
local function OnCreate(self)
    base.OnCreate(self)
    self.des_txt = self:AddComponent(UITextMeshProUGUIEx, des_txt_path)
    self.reward_content = self:AddComponent(UIBaseContainer, reward_content_path)
end

-- 销毁
local function OnDestroy(self)
    self.des_txt = nil
    self.reward_content = nil
    base.OnDestroy(self)
end

-- 显示
local function OnEnable(self)
    base.OnEnable(self)
end

-- 隐藏
local function OnDisable(self)
    base.OnDisable(self)
end

-- 全部刷新
local function RefreshData(self,data,index)
    self.param = data
    self.des_txt:SetText(Localization:GetString("280138",index))
    self:SetRewardCellDestroy()
    local list = self.param
    if list~=nil then
        local num =0
        for i = 1, table.length(list) do
            --复制基础prefab，每次循环创建一次
            num = num+1
            self.rewardModel[i] = self:GameObjectInstantiateAsync(UIAssets.WorldSiegeRewardItem, function(request)
                if request.isError then
                    return
                end
                local go = request.gameObject;
                go.gameObject:SetActive(true)
                go.transform:SetParent(self.reward_content.transform)
                go.transform:Set_localScale(ResetScale.x, ResetScale.y, ResetScale.z)
                local nameStr = tostring(NameCount)
                go.name = nameStr
                NameCount = NameCount + 1
                local cell = self.reward_content:AddComponent(RewardItem,nameStr)
                cell:RefreshData(list[i])
            end)
        end
    end
end

local function SetRewardCellDestroy(self)
    self.reward_content:RemoveComponents(RewardItem)
    if self.rewardModel~=nil then
        for k,v in pairs(self.rewardModel) do
            if v ~= nil then
                self:GameObjectDestroy(v)
            end
        end
    end
    self.rewardModel ={}
end

UIWorldSiegeRewardCell.OnCreate = OnCreate
UIWorldSiegeRewardCell.OnDestroy = OnDestroy
UIWorldSiegeRewardCell.OnEnable = OnEnable
UIWorldSiegeRewardCell.OnDisable = OnDisable
UIWorldSiegeRewardCell.RefreshData = RefreshData
UIWorldSiegeRewardCell.SetRewardCellDestroy= SetRewardCellDestroy
return UIWorldSiegeRewardCell