---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2022/9/26 15:37
---WorldSiegeContributePanel.lua


local WorldSiegeContributePanel = BaseClass("WorldSiegeContributePanel", UIBaseContainer)
local base = UIBaseContainer
local Localization = CS.GameEntry.Localization
local UserCell = require "UI.UIWorldSiegePoint.Component.WorldSiegeUserCell"

local title_path = "Top/NameText"
local rankBackBtn_path = "Top/btn_return"
local rankContent_path = "rank/ScrollView/Viewport/Content"
local rankDesc_path = "rank/Image/rankDesc"

-- 创建
local function OnCreate(self)
    base.OnCreate(self)
    self:DataDefine()
    self:ComponentDefine()
end

-- 销毁
local function OnDestroy(self)
    self:SetRankCellsDestroy()
    self:ComponentDestroy()
    self:DataDestroy()
    base.OnDestroy(self)
end

--控件的定义
local function ComponentDefine(self)
    self.titleN = self:AddComponent(UITextMeshProUGUIEx, title_path)
    self.titleN:SetText(Localization:GetString("302320"))
    self.rankBackBtnN = self:AddComponent(UIButton, rankBackBtn_path)
    self.rankBackBtnN:SetOnClick(function()
        self:OnClickRankBackBtn()
    end)
    self.rankContentN = self:AddComponent(UIBaseContainer, rankContent_path)
    self.rankDescN = self:AddComponent(UITextMeshProUGUIEx, rankDesc_path)
    self.rankDescN:SetText(Localization:GetString("302321"))
end

--控件的销毁
local function ComponentDestroy(self)
    self.titleN = nil
    self.introN = nil
    self.introBackBtnN = nil
    self.introTxtN = nil
    self.rankN = nil
    self.rankBackBtnN = nil
    self.rankContentN = nil
end

--变量的定义
local function DataDefine(self)
    self.serverData = nil
end

--变量的销毁
local function DataDestroy(self)
    self.serverData = nil
end

local function ShowPanel(self, data)
    self.serverData = data
    self:ShowRank()
end

local function ShowRank(self)
    self:RefreshRankList()
end

local function RefreshRankList(self)
    self:SetRankCellsDestroy()
    self.rankModels = {}
    if self.serverData~=nil then
        if #self.serverData.attackList>0 then
            local num =0
            for i = 1, table.length(self.serverData.attackList) do
                --复制基础prefab，每次循环创建一次
                num = num+1
                self.rankModels[i] = self:GameObjectInstantiateAsync(UIAssets.WorldSiegeUserCell, function(request)
                    if request.isError then
                        return
                    end
                    local go = request.gameObject;
                    go.gameObject:SetActive(true)
                    go.transform:SetParent(self.rankContentN.transform)
                    go.transform:Set_localScale(ResetScale.x, ResetScale.y, ResetScale.z)
                    local nameStr = tostring(NameCount)
                    go.name = nameStr
                    NameCount = NameCount + 1
                    local cell = self.rankContentN:AddComponent(UserCell,nameStr)
                    cell:RefreshData(self.serverData.attackList[i], i)
                end)
            end
        end
    end
end

local function SetRankCellsDestroy(self)
    self.rankContentN:RemoveComponents(UserCell)
    if self.rankModels~=nil then
        for k,v in pairs(self.rankModels) do
            if v ~= nil then
                self:GameObjectDestroy(v)
            end
        end
    end
    self.rankModels ={}
end

local function OnClickRankBackBtn(self)
    self.view:OnReturnDesClick()
end

WorldSiegeContributePanel.OnCreate = OnCreate
WorldSiegeContributePanel.OnDestroy = OnDestroy
WorldSiegeContributePanel.ComponentDefine = ComponentDefine
WorldSiegeContributePanel.ComponentDestroy = ComponentDestroy
WorldSiegeContributePanel.DataDefine = DataDefine
WorldSiegeContributePanel.DataDestroy = DataDestroy

WorldSiegeContributePanel.ShowPanel = ShowPanel
WorldSiegeContributePanel.ShowRank = ShowRank
WorldSiegeContributePanel.RefreshRankList = RefreshRankList
WorldSiegeContributePanel.SetRankCellsDestroy = SetRankCellsDestroy
WorldSiegeContributePanel.OnClickRankBackBtn = OnClickRankBackBtn

return WorldSiegeContributePanel