---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2022/7/1 17:03
---

local NationTemplateManager = BaseClass("NationTemplateManager")
local NationTemplate = require "DataCenter.NationTemplateManager.NationTemplate"



local function __init(self)
    self.nationsDic = nil
    self.defaultNation = nil
end

local function __delete(self)
    self.nationsDic = nil
    self.defaultNation = nil
end

local function InitNationDic(self)
    self.nationsDic = {}
    LocalController:instance():visitTable(TableName.NationConf, function(id, lineData)
        local item = NationTemplate.New()
        item:ParseData(lineData)
        self.nationsDic[item.nation] = item
        if not self.defaultNation then
            self.defaultNation = item
        end
    end)
end

local function GetAllNationsList(self)
    if not self.nationsDic then
        self:InitNationDic()
    end
    local result = {}
    for k,v in pairs(self.nationsDic) do
        if not self:IsHideCountryFlag(v.nation) then
            table.insert(result, v)
        end
    end
    return result
end

local function GetNationTemplate(self, nation)
    if not self.nationsDic then
        self:InitNationDic()
    end
    
    nation = string.IsNullOrEmpty(nation) and DefaultNation or nation
    local template = self.nationsDic[nation]
    if not template then
        template = self.defaultNation
    end
    return template
end

--是否属于屏蔽国家
function NationTemplateManager:IsHideCountryFlag(nation)
    for k,v in ipairs(HideCountryFlag) do
        if v == nation then
            return true
        end
    end
    return false
end

NationTemplateManager.__init = __init
NationTemplateManager.__delete = __delete
NationTemplateManager.InitNationDic = InitNationDic
NationTemplateManager.GetAllNationsList = GetAllNationsList
NationTemplateManager.GetNationTemplate = GetNationTemplate

return NationTemplateManager