---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2021/9/27 20:44
---
local WorldPlayerDes = BaseClass("WorldPlayerDes", UIBaseContainer)
local base = UIBaseContainer
local Localization = CS.GameEntry.Localization
local player_obj_path = "info/playerObj"
local build_obj_path = "info/buildObj"
local headBg_path = "info/UIPlayerHead"
local player_head_path = "info/UIPlayerHead/HeadIcon"
local headFg_path = "info/UIPlayerHead/Foreground"
local power_des_path = "info/playerObj/powerDes"
local power_num_path = "info/playerObj/powerDes/powerNum"
local kill_des_path = "info/playerObj/killDes"
local kill_num_path = "info/playerObj/killDes/killNum"
local alliance_des_path = "info/playerObj/AlliDes"
local alliance_num_path = "info/playerObj/AlliDes/AlliName"

local name_txt_path = "info/buildObj/TextName"
local des_txt_path = "info/buildObj/TextDes"
local slider_path = "info/buildObj/Slider"
local num_path = "info/buildObj/Txt_CollectNum"
local time_path = "info/buildObj/Txt_CollectTime"
local scout_mail_btn_path = "info/ScoutMailBtn"

-- 创建
local function OnCreate(self)
    base.OnCreate(self)
    self:ComponentDefine()
    self:DataDefine()
end

-- 销毁
local function OnDestroy(self)
    self:ComponentDestroy()
    self:DataDestroy()
    base.OnDestroy(self)
end

-- 显示
local function OnEnable(self)
    base.OnEnable(self)
end

-- 隐藏
local function OnDisable(self)
    self:DeleteTimer()
    base.OnDisable(self)
end


--控件的定义
local function ComponentDefine(self)
    self.player_obj = self:AddComponent(UIBaseContainer,player_obj_path)
    self.build_obj = self:AddComponent(UIAnimator,build_obj_path)
    self.player_head = self:AddComponent(UIPlayerHead,player_head_path)
    self.playerHeadBg = self:AddComponent(UIButton, headBg_path)
    self.playerHeadBg:SetOnClick(function()
        SoundUtil.PlayEffect(SoundAssets.Music_Effect_Button)
        self:OnClickHead()
    end)
    self.playerHeadFg = self:AddComponent(UIImage, headFg_path)
    self.power_des = self:AddComponent(UITextMeshProUGUIEx,power_des_path)
    self.power_num = self:AddComponent(UITextMeshProUGUIEx,power_num_path)
    self.kill_des = self:AddComponent(UITextMeshProUGUIEx,kill_des_path)
    self.kill_num = self:AddComponent(UITextMeshProUGUIEx,kill_num_path)
    self.alliance_des = self:AddComponent(UITextMeshProUGUIEx,alliance_des_path)
    self.alliance_num = self:AddComponent(UITextMeshProUGUIEx,alliance_num_path)
    self.name_txt = self:AddComponent(UITextMeshProUGUIEx,name_txt_path)
    self.collectNum_txt = self:AddComponent(UITextMeshProUGUIEx,num_path)
    self.collectTime_txt = self:AddComponent(UITextMeshProUGUIEx,time_path)
    self.des_txt =  self:AddComponent(UITextMeshProUGUIEx,des_txt_path)
    self.slider = self:AddComponent(UISlider,slider_path)
    self.power_des:SetLocalText(GameDialogDefine.POWER) 
    self.kill_des:SetLocalText(GameDialogDefine.KILL_NUM) 
    self.alliance_des:SetLocalText(GameDialogDefine.ALLIANCE)
    self.scout_mail_btn = self:AddComponent(UIButton, scout_mail_btn_path)
    self.scout_mail_btn:SetOnClick(function()
        SoundUtil.PlayEffect(SoundAssets.Music_Effect_Button)
        self:OnClickScoutMailBtn()
    end)
end

--控件的销毁
local function ComponentDestroy(self)
    self.btn = nil
    self.btnImage = nil
end

--变量的定义
local function DataDefine(self)
    self.data = nil
    self.isRuins = false
    self.timer_action = function(temp)
        self:RefreshTime()
    end
    self.scoutMailUid = nil--侦查邮件uid
end

--变量的销毁
local function DataDestroy(self)
    self.isRuins = nil
    self.data = nil
    self.scoutMailUid = nil
end

local function RefreshData(self,param)
    self.isRuins =false
    self.recoverSpeed = LuaEntry.DataConfig:TryGetNum("building_attack", "k2")
    if param ~= nil and param.recoverSpeed ~= nil and param.recoverSpeed > 0 then
        self.recoverSpeed = param.recoverSpeed
    end
    self.data = param
    local uid = self.view.ctrl.ownerUid
    local userinfo = ChatInterface.getUserData(uid, true)
    if userinfo~=nil then
        local userPic = userinfo["headPic"] or ""
        local userPicVer = userinfo["headPicVer"] or 0
        self.player_head:SetData(uid, userPic, userPicVer)
        local tempFg = userinfo:GetHeadBgImg()
        if tempFg then
            self.playerHeadFg:SetActive(true)
            self.playerHeadFg:LoadSprite(tempFg)
        else
            self.playerHeadFg:SetActive(false)
        end
    end
    if self.view.ctrl.type == WorldPointUIType.City then
        self.player_obj:SetActive(true)
        self.build_obj:SetActive(false)
    else
        self.player_obj:SetActive(false)
        self.build_obj:SetActive(true)
        if self.view.ctrl.type == WorldPointUIType.CollectArmy then
            self.des_txt:SetText("")
            self.build_obj:Play("txtchangell", 0, 0)
            if self.data~=nil then
                self.name_txt:SetText(self.data.resourceName)
                --if self.data.isSelf~=nil and self.data.isSelf ~= 1 then
                --    self.slider:SetActive(false)
                --    self.collectNum_txt:SetText("")
                --    self.collectTime_txt:SetText("")
                --else
                    self.slider:SetActive(true)
                    --self.collectNum_txt:SetText("")
                    self:AddTimer()
                    self.endTime = self.data.endTime
                    self:RefreshTime()
                --end
            else
                self.name_txt:SetText("")
                self.slider:SetActive(false)
                self.collectNum_txt:SetText("")
            end
        else
            self.collectTime_txt:SetText("")
            if LuaEntry.Player.serverType == ServerType.DRAGON_BATTLE_FIGHT_SERVER then
                self.slider:SetActive(false)
                self.des_txt:SetLocalText(376127)
                self.collectNum_txt:SetText("")
            else
                self.slider:SetActive(true)
            end
            self.build_obj:Play("txtChangeNormal", 0, 0)
        end
    end
    --这个人有侦查邮件 显示按钮
    local mailData = DataCenter.MailDataManager:GetScoutMailByTargetUidAndPoint(uid, self.view.ctrl.pointId)
    if mailData ~= nil then
        self.scoutMailUid = mailData.uid
        self.scout_mail_btn:SetActive(true)
    else
        self.scoutMailUid = nil
        self.scout_mail_btn:SetActive(false)
    end
end

local function DeleteTimer(self)
    if self.timer ~= nil then
        self.timer:Stop()
        self.timer = nil
    end
end

local function AddTimer(self)
    if self.timer == nil then
        self.timer = TimerManager:GetInstance():GetTimer(1, self.timer_action , self, false,false,false)
    end

    self.timer:Start()
end

local function RefreshTime(self)
    local curTime = UITimeManager:GetInstance():GetServerTime()
    if self.view.ctrl.type == WorldPointUIType.CollectArmy then
        if self.data==nil then
            return
        end
        if self.data.gatherMarchUuid==nil then
            return
        end
        local deltaTime = self.endTime - curTime
        local maxTime = self.endTime - self.data.startTime
        if deltaTime>0 then
            self.collectNum_txt:SetText(Localization:GetString("300642")..": "..math.floor((maxTime-deltaTime)*0.001 * self.data.collectSpd).."/"..math.floor(maxTime*0.001 * self.data.collectSpd))
            self.collectTime_txt:SetText(Localization:GetString("300641")..": "..UITimeManager:GetInstance():MilliSecondToFmtString(deltaTime))
            local tempValue = math.min((1 - (deltaTime / math.max(maxTime,1))),1)
            self.slider:SetValue(tempValue)
        else
            self.slider:SetValue(1)
            self.collectNum_txt:SetText("")
            self.collectTime_txt:SetText("")
            self.view.ctrl:CloseSelf(true)
        end
    elseif self.view.ctrl.type == WorldPointUIType.Build then
        if self.serverData==nil then
            return
        end
        if LuaEntry.Player.serverType == ServerType.DRAGON_BATTLE_FIGHT_SERVER then
            self.collectNum_txt:SetText("")
            return
        end
        local deltaTime = curTime/1000 - self.serverData.lastHpTime
        if self.serverData.maxHp>0 then
            if self.isRuins == true then
                self.collectNum_txt:SetText("0/"..string.GetFormattedSeperatorNum(math.floor(self.serverData.maxHp)))
                self.slider:SetValue(0)
            else
                local realBlood  = math.min(deltaTime * self.recoverSpeed + self.serverData.curHp,self.serverData.maxHp)
                local percent = math.min(realBlood/self.serverData.maxHp,1)
                self.collectNum_txt:SetText(string.GetFormattedSeperatorNum(math.floor(realBlood)).."/"..string.GetFormattedSeperatorNum(math.floor(self.serverData.maxHp)))
                self.slider:SetValue(percent)
            end
            
        else
            self.collectNum_txt:SetText("0/0")
            self.slider:SetValue(0)
        end
    end
end

local function UpdateInfo(self,data)
    self.serverData = data
    if self.view.ctrl.type == WorldPointUIType.City then
        if self.serverData.playerData.alAbbr~=nil and self.serverData.playerData.alAbbr~="" then
            self.alliance_num:SetText("["..self.serverData.playerData.alAbbr.."]"..self.serverData.playerData.allianceName)
        else
            self.alliance_num:SetText("-")
        end
        self.power_num:SetText(string.GetFormattedSeperatorNum(math.floor(self.serverData.playerData.power)))
        self.kill_num:SetText(string.GetFormattedSeperatorNum(math.floor(self.serverData.playerData.armyKill)))
    elseif self.view.ctrl.type == WorldPointUIType.Build then
        local info = DataCenter.WorldPointManager:GetBuildDataByUuid(self.view.ctrl.uuid)
        local buildId
        if info then
            buildId = info.itemId
            if info.destroyStartTime > 0 then
                self.isRuins = true
            end
        end
        local name = Localization:GetString(self.serverData.name)
        
        if buildId then
            --local buildTemplate = DataCenter.BuildTemplateManager:GetBuildingDesTemplate(buildId)
            --if buildTemplate then
            --    local buildZoneName = BuildZoneName[buildTemplate.zoneType]
            --    if buildZoneName then
            --        name = name.." ("..Localization:GetString(buildZoneName)..")"
            --    end
            --end
        end
        
        if self.isRuins then
            name = name.." ("..Localization:GetString("104202")..")"
        end
        
        self.name_txt:SetText(name) 
        self:AddTimer()
        self:RefreshTime()
    end
end

local function OnClickHead(self)
    if self.view.ctrl.ownerUid~=nil and self.view.ctrl.ownerUid~="" then
        self.view.ctrl:CloseSelf()
        if self.view.ctrl.ownerUid == LuaEntry.Player.uid then
            UIManager:GetInstance():OpenWindow(UIWindowNames.UIPlayerInfo,{anim = true,UIMainAnim = UIMainAnimType.AllHide},self.view.ctrl.ownerUid)
        else
            UIManager:GetInstance():OpenWindow(UIWindowNames.UIOtherPlayerInfo,{anim = true,UIMainAnim = UIMainAnimType.AllHide},self.view.ctrl.ownerUid)
        end
    end
end

function WorldPlayerDes:OnClickScoutMailBtn()
    if self.view.ctrl.ownerUid ~=nil and self.view.ctrl.ownerUid ~= "" then
        local uid = self.scoutMailUid
        self.view.ctrl:CloseSelf()
        --打开侦查邮件
        local mailData = DataCenter.MailDataManager:GetMailInfoById(uid)
        if mailData ~= nil and mailData.saveFlag == 1 then
            GoToUtil.GotoOpenView(UIWindowNames.UIMailNew, MailInternalGroup.MAIL_IN_favor, uid)
        else
            GoToUtil.GotoOpenView(UIWindowNames.UIMailNew, MailInternalGroup.MAIL_IN_battle, uid)
        end
    end
end

WorldPlayerDes.OnCreate = OnCreate
WorldPlayerDes.OnDestroy = OnDestroy
WorldPlayerDes.OnEnable = OnEnable
WorldPlayerDes.OnDisable = OnDisable
WorldPlayerDes.ComponentDefine = ComponentDefine
WorldPlayerDes.ComponentDestroy = ComponentDestroy
WorldPlayerDes.DataDefine = DataDefine
WorldPlayerDes.DataDestroy = DataDestroy
WorldPlayerDes.AddTimer = AddTimer
WorldPlayerDes.DeleteTimer = DeleteTimer
WorldPlayerDes.RefreshTime = RefreshTime
WorldPlayerDes.RefreshData = RefreshData
WorldPlayerDes.UpdateInfo = UpdateInfo
WorldPlayerDes.OnClickHead = OnClickHead

return WorldPlayerDes