---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 8/12/21 9:44 PM
---



local UIBindSuccess = {
    Name = UIWindowNames.UIBindSuccess,
    Layer = UILayer.Normal,
    Ctrl = require "UI.UIAccount2.UIBindSuccess.Controller.UIBindSuccessCtrl",
    View = require "UI.UIAccount2.UIBindSuccess.View.UIBindSuccess",
    PrefabPath = "Assets/Main/Prefab_Dir/UI/UIAccount/UIBindSuccess.prefab"
}

return {
    -- 配置
    UIBindSuccess = UIBindSuccess,
}