---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2023/2/16 19:51
---
local base = UIBaseView--Variable
local UICrossDesert = BaseClass("UICrossDesert", base)--Variable
local Localization = CS.GameEntry.Localization
local AllianceFlag = require "UI.UIAllianceCompeteNew.Component.AlCompeteCrossServer.AllianceFlag"
local title_path = "startGo/middleGo/titleTxt"
local subTitle_path = "startGo/middleGo/desTxt"
local actTime_path = "startGo/middleGo/timeTxt"
local cdTip_path = "startGo/middleGo/timeTxt/cdTip"
local cdTime_path = "startGo/middleGo/timeTxt/cdTxt"

local attackBtn_path = "startGo/attackBtn"
local attackBtnTxt_path = "startGo/attackBtn/attackTxt"
local allianceFlag_path = "startGo/allianceFlag"

local infoBtn_path = "startGo/middleGo/titleTxt/infoBtn"

local function OnCreate(self)
    base.OnCreate(self)
    self:DataDefine()
    self:ComponentDefine()
end

local function OnDestroy(self)
    self:DelTimer()
    self:ComponentDestroy()
    self:DataDestroy()
    base.OnDestroy(self)
end

local function ComponentDefine(self)
    self.titleN = self:AddComponent(UIText, title_path)
    if SeasonUtil.IsInSeasonDesertMode() then
        self.titleN:SetText(Localization:GetString("110559"))
    else
        self.titleN:SetText(Localization:GetString("110214"))
    end

    self.subTitleN = self:AddComponent(UIText, subTitle_path)
    if SeasonUtil.IsInSeasonDesertMode() then
        self.subTitleN:SetText(Localization:GetString("372990"))
    else
        self.subTitleN:SetText(Localization:GetString("372418"))
    end
    self.actTimeN = self:AddComponent(UIBaseContainer, actTime_path)
    self.cdTipN = self:AddComponent(UIText, cdTip_path)
    self.cdTimeN = self:AddComponent(UIText, cdTime_path)

    self.attackBtnN = self:AddComponent(UIButton, attackBtn_path)
    self.attackBtnN:SetOnClick(function()
        self:OnClickAttackBtn()
    end)
    self.attackBtnTxtN = self:AddComponent(UIText, attackBtnTxt_path)
    self.attackBtnTxtN:SetLocalText(100150)
    self.infoBtnN = self:AddComponent(UIButton, infoBtn_path)
    self.infoBtnN:SetOnClick(function()
        self:OnClickInfoBtn()
    end)
    self.allianceFlagObj = self:AddComponent(AllianceFlag,allianceFlag_path)
end

local function ComponentDestroy(self)
    self.titleN = nil
    self.subTitleN = nil
    self.cdTipN = nil
    self.cdTimeN = nil
    self.alNameRN = nil
    self.attackBtnN = nil
    self.attackBtnTxtN = nil
    self.infoBtnN = nil
end

local function DataDefine(self)
    self.activityInfo = nil
    self.eventInfo = nil
    self.isCrossServerOpen = nil
    self.curStatus = nil
end

local function DataDestroy(self)
    self.activityInfo = nil
    self.eventInfo = nil
    self.isCrossServerOpen = nil
    self.curStatus = nil
end

local function OnAddListener(self)
    base.OnAddListener(self)
    --self:AddUIListener(EventId.UpdateOneCommonShop, self.RefreshAll)
end

local function OnRemoveListener(self)
    --self:RemoveUIListener(EventId.UpdateOneCommonShop, self.RefreshAll)
    base.OnRemoveListener(self)
end

local function ShowPanel(self,activityId)
    self.activityId = activityId
    self.activityInfo = DataCenter.ActivityListDataManager:GetActivityDataById(activityId)
    if not self.activityInfo then
        return
    end
    self:RefreshAll()
end

local function RefreshAll(self)

    if self.activityInfo.servers and self.activityInfo.servers ~= "" then
        self.serverList = string.split(self.activityInfo.servers,";")
    end
    self:SetRemainTime()
    self:AddTimer()
end

local function AddTimer(self)
    self.TimerAction = function()
        self:SetRemainTime()
    end

    if self.timer == nil then
        self.timer = TimerManager:GetInstance():GetTimer(1, self.TimerAction , self, false,false,false)
    end
    self.timer:Start()
end

local function SetRemainTime(self)
    local curTime = UITimeManager:GetInstance():GetServerTime()
    if curTime < self.activityInfo.startTime then
        --即将开启
        self.cdTipN:SetLocalText(372114)
        self.cdTimeN:SetText(UITimeManager:GetInstance():MilliSecondToFmtString(self.activityInfo.startTime - curTime))
        self.attackBtnN:SetActive(false)
    elseif curTime > self.activityInfo.endTime then
        self.cdTimeN:SetText("00:00:00")
        self.cdTipN:SetLocalText(370100)
        self.attackBtnN:SetActive(false)
    else
        self.cdTipN:SetLocalText(373117)
        self.cdTimeN:SetText(UITimeManager:GetInstance():MilliSecondToFmtString(self.activityInfo.endTime - curTime))
        self.attackBtnN:SetActive(true)
    end
end

local function DelTimer(self)
    if self.timer ~= nil then
        self.timer:Stop()
        self.timer = nil
    end
end

local function OnClickAttackBtn(self)
    --检查是否有联盟
    if LuaEntry.Player:IsInAlliance() then
        if self.serverList and next(self.serverList) then
            --检查前哨战是否已经放置
            local flagData = DataCenter.AllianceMineManager:GetAllianceFlagData()
            if flagData~=nil then
                local targetServerId = flagData.curServerId
                local pointId = flagData.pointId
                if pointId>0 then
                    local pos = SceneUtils.TileIndexToWorld(pointId,ForceChangeScene.World)
                    pos.x = pos.x-1
                    pos.y = pos.y
                    pos.z = pos.z-1
                    GoToUtil.GotoWorldPos(pos,nil,nil,nil,targetServerId)
                end
            else
                --没有放置在选择服务器
                UIManager:GetInstance():OpenWindow(UIWindowNames.UICrossDesertServer,self.activityId)
            end
        end
    else
        UIUtil.ShowTipsId(390856)
    end
end

local function OnClickInfoBtn(self)
    UIUtil.ShowIntro(Localization:GetString("110214"), Localization:GetString("110223"), Localization:GetString("372991"))
end

UICrossDesert.OnCreate = OnCreate
UICrossDesert.OnDestroy = OnDestroy
UICrossDesert.OnAddListener = OnAddListener
UICrossDesert.OnRemoveListener = OnRemoveListener
UICrossDesert.ComponentDefine = ComponentDefine
UICrossDesert.ComponentDestroy = ComponentDestroy
UICrossDesert.DataDefine = DataDefine
UICrossDesert.DataDestroy = DataDestroy

UICrossDesert.ShowPanel = ShowPanel
UICrossDesert.RefreshAll = RefreshAll
UICrossDesert.SetTimeTip = SetTimeTip
UICrossDesert.AddTimer = AddTimer
UICrossDesert.SetRemainTime = SetRemainTime
UICrossDesert.DelTimer = DelTimer
UICrossDesert.OnClickAttackBtn = OnClickAttackBtn
UICrossDesert.OnClickInfoBtn = OnClickInfoBtn


return UICrossDesert