---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2023/2/1 20:21
---


local UIHeroSlot = BaseClass("UIHeroSlot", UIBaseContainer)
local base = UIBaseContainer

local UIHeroCell = require "UI.UIHero2.Common.UIHeroCellSmall"
local UIHeroStars = require 'UI.UIHero2.Common.UIHeroStars'

-- 创建
local function OnCreate(self)
    base.OnCreate(self)
    self:ComponentDefine()
end

-- 销毁
local function OnDestroy(self)
    self:ComponentDestroy()

    self.parent = nil
    self.heroUuid = nil
    self.heroData = nil

    base.OnDestroy(self)
end

-- 显示
local function OnEnable(self)
    base.OnEnable(self)
end

-- 隐藏
local function OnDisable(self)
    base.OnDisable(self)
end


--控件的定义
local function ComponentDefine(self)
    self.heroCell = self:AddComponent(UIHeroCell, "UIHeroCellSmall")
    self.empty = self:AddComponent(UIBaseContainer, "Empty")
    self.emptyStar = self:AddComponent(UIHeroStars, "Empty/HeroNeedItem/NodeArrow")
    self.emptyCamp = self:AddComponent(UIImage, "Empty/HeroNeedItem/imgCamp")
    --self.emptyQualityBg = self:AddComponent(UIImage, "Empty/HeroNeedItem/LayerPoster/ImgPosterQualityBg")
    --self.emptyQualityFg = self:AddComponent(UIImage, "Empty/HeroNeedItem/LayerPoster/ImgPosterQualityFg")
end

--控件的销毁
local function ComponentDestroy(self)
    self.heroCell = nil
end

-- 全部刷新
local function SetData(self, param)
    self.data = param
    self:RefreshView()
end

local function RefreshView(self)
    --type.type = HeroAdvanceConsumeType.ConsumeType_Same_Hero
    --type.quality = sameHeroQuality
    self.heroCell:SetActive(false)
    self.empty:SetActive(false)
    if self.data.type == HeroAdvanceConsumeType.ConsumeType_Same_Hero then
        self.heroCell:SetActive(true)
        self.heroCell:InitWithConfigIdByPoster(self.data.heroId, self.data.quality)
    else
        self.empty:SetActive(true)
        local param = {}
        param.showStarNum = self.data.quality
        param.maxStarNum = param.showStarNum
        self.emptyStar:SetData(param)
        self.emptyCamp:LoadSprite(HeroUtils.GetCampIconPath(self.data.camp))
    end
end

UIHeroSlot.OnCreate = OnCreate
UIHeroSlot.OnDestroy = OnDestroy
UIHeroSlot.OnEnable = OnEnable
UIHeroSlot.OnDisable = OnDisable
UIHeroSlot.ComponentDefine = ComponentDefine
UIHeroSlot.ComponentDestroy = ComponentDestroy
UIHeroSlot.SetData = SetData
UIHeroSlot.RefreshView = RefreshView

return UIHeroSlot
