---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Beef.
--- DateTime: 2023/11/13 21:01
---

local CityResidentDefines = {}

CityResidentDefines.UpdateIntervalHigh = 0
CityResidentDefines.UpdateIntervalLow = 0 -- 2024/2/21 先不优化

CityResidentDefines.ResidentLowAttributePercent = 0.2 -- 小人低属性判定百分比
CityResidentDefines.ResidentScareDuration = 4.9 -- 小人惊吓躲避时间
CityResidentDefines.ResidentReadyHidePos = Vector3.New(-1000, 0, -1000) -- 小人幸存者隐藏位置
CityResidentDefines.ResidentReadyQueueInterval = 0.2 -- 小人幸存者排队间隔
CityResidentDefines.ResidentTalkIntervalMin = 10 -- 小人说同一种话话间隔最小值
CityResidentDefines.ResidentTalkIntervalMax = 15 -- 小人说同一种话话间隔最大值
CityResidentDefines.ResidentTalkSingleInterval = 60 -- 同一个小人说话间隔
CityResidentDefines.ResidentTalkCount = 3 -- 小人说话同时存在最大数量
CityResidentDefines.ResidentTalkDuration = 5 -- 小人说话持续时间
CityResidentDefines.ResidentStaminaDuration = 30 -- 小人血条持续时间
CityResidentDefines.ResidentDieMood = -10 -- 小人死亡时，减少心情值
CityResidentDefines.ResidentScareMood = -2 -- 小人惊恐时，减少心情值
CityResidentDefines.ResidentScareHideMood = -1 -- 小人惊恐躲藏时，减少心情值
CityResidentDefines.ResidentScareMoodInterval = 2 -- 小人惊恐时，减少心情值的间隔
CityResidentDefines.ResidentScareHideMoodInterval = 10 -- 小人惊恐躲藏时，减少心情值的间隔
CityResidentDefines.ResidentScareHudDuration = 2 -- 小人惊恐躲藏时，图标显示时长
CityResidentDefines.ResidentAutoBetrayTime = 120 -- 小人自动叛逃时间
CityResidentDefines.ResidentDrunkDuration = 60 -- 小人喝醉持续时间
CityResidentDefines.ZombieRoarCount = 20 -- 每秒判定多少个丧尸的惊吓
CityResidentDefines.ZombieRoarMainLv = 4 -- 丧尸惊吓需要大本等级
CityResidentDefines.ZombieSearchCount = 20 -- 每秒判定多少个丧尸的追击
CityResidentDefines.ZombieAttackMainLv = 4 -- 丧尸追击需要大本等级
CityResidentDefines.ZombieAttackRange = 0.4 -- 丧尸攻击范围
CityResidentDefines.ZombieEscapeDis = 1 -- 丧尸逃离大本距离
CityResidentDefines.ZombieAttackBuildingRate = 1 -- 丧尸攻击建筑概率
CityResidentDefines.ZombieAttackBuildingSpacing = 0.5 -- 丧尸攻击建筑间距
CityResidentDefines.ZombieIgnoreBuildingDuration = 10 -- 丧尸攻击建筑满员后无视该建筑的时间
CityResidentDefines.ZombieHurtDuration = 0.5 -- 丧尸受击持续时间
CityResidentDefines.ZombieFlashDuration = 0.05 -- 丧尸受击闪红时间
CityResidentDefines.HeroAttackRange = 2 -- 英雄攻击范围
CityResidentDefines.BuildingStaminaDuration = 10 -- 建筑受伤显血时间
CityResidentDefines.SiegeCallDelay = 3
CityResidentDefines.AnimalWanderRange = 1.2 -- 动物在路点边游荡范围

-- 速度
CityResidentDefines.SpeedHeroRun = 1
CityResidentDefines.SpeedHeroFire = 0.8

CityResidentDefines.RestaurantFoodWindowCount = 3 -- 餐厅取餐台最大数量

CityResidentDefines.HudPadding = 50

CityResidentDefines.Type =
{
    None = "None",
    Resident = "Resident",
    Zombie = "Zombie",
    Hero = "Hero",
    Special = "Special",
    Animal = "Animal",
}

CityResidentDefines.AnimalType =
{
    Deer = "Deer",
    Rabbit = "Rabbit",
    Wolf = "Wolf",
    Boar = "Boar",
    Bear = "Bear",
}

CityResidentDefines.AnimalPrefabPath =
{
    [CityResidentDefines.AnimalType.Deer] = "Assets/Main/Prefab_Dir/Home/Animal/A_Animal_Deer.prefab",
}

CityResidentDefines.Career =
{
    None = "None",
    Chef = "Chef", -- 厨师
    Sawyer = "Sawyer", -- 锯木人
    Hunter = "Hunter", -- 猎人
    Smith = "Smith", -- 钢铁工人
    Powerman = "Powerman", -- 发电人
    Doctor = "Doctor", -- 医生
    Bartender = "Bartender", -- 酒保
}

CityResidentDefines.FurnitureCareer =
{
    [FurnitureType.CookingBench] = CityResidentDefines.Career.Chef,
    [FurnitureType.SawingTable] = CityResidentDefines.Career.Sawyer,
    [FurnitureType.HuntingTool] = CityResidentDefines.Career.Hunter,
    [FurnitureType.ForgingTable] = CityResidentDefines.Career.Smith,
    [FurnitureType.ElectricGenerator] = CityResidentDefines.Career.Powerman,
    [FurnitureType.ConsultationDesk] = CityResidentDefines.Career.Doctor,
    [FurnitureType.BarCounter] = CityResidentDefines.Career.Bartender,
}

CityResidentDefines.WayPointMask =
{
    City1 = 1,
}

CityResidentDefines.MoveType =
{
    LeaveBuilding = "LeaveBuilding",
    GoToBuilding = "GoToBuilding",
    GoToFurniture = "GoToFurniture",
    GoToCityPos = "GoToCityPos",
    GoToMaskPos = "GoToMaskPos",
    GoToAccuratePos = "GoToAccuratePos",
}

CityResidentDefines.State =
{
    None = "None",
    GoToIdle = "GoToIdle",
    Idle = "Idle",
    PlayPool = "PlayPool",
    PlayDesk = "PlayDesk",
    GoToWork = "GoToWork",
    GoToWorkWayPoint = "GoToWorkWayPoint",
    Work = "Work",
    WorkBack = "WorkBack",
    WorkPut = "WorkPut",
    Overwork = "Overwork",
    GoToSleep = "GoToSleep",
    Sleep = "Sleep",
    SleepNoBed = "SleepNoBed",
    GoRestaurant = "GoRestaurant",
    GoForMeal = "GoForMeal",
    TakeMeal = "TakeMeal",
    GoToEat = "GoToEat",
    Eat = "Eat",
    Scare = "Scare",
    ScareHide = "ScareHide",
    Sick = "Sick",
    SickSleepHouse = "SickSleepHouse",
    SickSleepHospital = "SickSleepHospital",
    ReadyQueue = "ReadyQueue",
    ReadyHide = "ReadyHide",
    Dead = "Dead",
    BeFire = "BeFire",
    Betray = "Betray",
    BetrayLeave = "BetrayLeave",
    Rest = "Rest",
    GoBar = "GoBar",
    Drink = "Drink",
    BartenderMix = "BartenderMix",
    BartenderServe = "BartenderServe",
    BartenderGoSweep = "BartenderGoSweep",
    BartenderSweep = "BartenderSweep",
    HuntAttack = "HuntAttack",
    HuntHarvest = "HuntHarvest",
    Shit = "Shit",
}

CityResidentDefines.ZombieState =
{
    None = "None",
    Invade = "Invade",
    Retreat = "Retreat",
    InvadeWalk = "InvadeWalk",
    InvadeIdle = "InvadeIdle",
    WanderWalk = "WanderWalk",
    WanderIdle = "WanderIdle",
    Dying = "Dying",
    Dead = "Dead",
    BeFire = "BeFire",
    Chase = "Chase",
    Attack = "Attack",
    Escape = "Escape",
    ChaseBuilding = "ChaseBuilding",
    AttackBuilding = "AttackBuilding",
    Siege = "Siege",
    AttackWall = "AttackWall",
    Hurt = "Hurt",
}

CityResidentDefines.HeroState =
{
    None = "None",
    GoToIdle = "GoToIdle",
    Idle = "Idle",
    PreAttack = "PreAttack",
    Attack = "Attack",
    GoToFire = "GoToFire",
    Fire = "Fire",
}

CityResidentDefines.SpecialState =
{
    None = "None",
    SiegeBossInvade = "SiegeBossInvade",
    SiegeBossRetreat = "SiegeBossRetreat",
    SiegeBossIdle = "SiegeBossIdle",
    SiegeBossDead = "SiegeBossDead",
}

CityResidentDefines.AnimalState =
{
    None = "None",
    Idle = "Idle",
    Move = "Move",
    Dead = "Dead",
}

-- 临时配置
CityResidentDefines.HeroConfig =
{
    [1] =
    {
        uuid = 100001,
        prefab = "Assets/Main/Prefab_Dir/Home/Hero/A_Hero_Home_1.prefab",
        firePrefab = "Assets/_Art/Effect/prefab/Eff_Ak_Gunfire.prefab",
        fireDelay = 0,
        fireSound = "Effect_pve_gun",
    },
    [2] =
    {
        uuid = 100002,
        prefab = "Assets/Main/Prefab_Dir/Home/Hero/qbb_lod.prefab",
        firePrefab = "Assets/Main/Prefab_Dir/Home/Effect/Hero/army_qbb_atk_01.prefab",
        fireDelay = 0.23,
        fireSound = "Effect_hero_pistol",
    },
    [3] =
    {
        uuid = 100003,
        prefab = "Assets/Main/Prefab_Dir/Home/Hero/jjs_lod.prefab",
        firePrefab = "Assets/Main/Prefab_Dir/Home/Effect/Hero/army_jjs_atk_01.prefab",
        fireDelay = 0.13,
        fireSound = "Effect_hero_sniper",
    },
}

CityResidentDefines.Movie =
{
    Begin = 1, -- 开场
    ZombieEscape = 2, -- 僵尸逃跑
    ReleaseResident = 3, -- 释放小人控制
    SawyerWork = 4, -- 锯木工工作
    ChefWork = 5, -- 厨师工作
    ResidentEat = 6, -- 开饭
    ResidentHide = 7, -- 小人躲到房子里
    ZombieCome = 8, -- 僵尸到达
    HeroAttack = 9, -- 英雄攻击
    ResidentCome = 10, -- 小人到达
}

CityResidentDefines.AnimName =
{
    Idle = "idle", -- 站
    Idle2 = "idle2", -- 站2
    Idle3 = "idle3", -- 站3
    IdleHold = "idle_hold", -- 站，手举东西
    Walk = "walk", -- 走
    SickWalk = "sickwalk", -- 走，生病
    CarryFoodWalk = "carryfoodwalk", -- 走，拿着餐盘
    CarryWalk = "carrywalk", -- 走，扛着东西
    TorchWalk = "torchwalk", -- 走，举火把
    Take = "take", -- 走，拿东西
    Run = "run", -- 跑
    RunHold = "run_hold", -- 跑，手举东西
    Sleep = "sleeping", -- 躺
    SickSleep = "sicksleep", -- 躺，生病
    Scratch = "scratch", -- 躺，挠痒痒
    Eat = "eattingfood", -- 坐，进食
    EatSnack = "eattingsnack", -- 坐，吃点心
    Write = "writing", -- 坐，书写
    WashHand = "washhand", -- 洗手
    TakeUp = "takeupsth", -- 拿取
    Ignite = "ignite", -- 点燃
    Protest = "protest", -- 抗议
    Throw = "throw", -- 投掷
    Attack01 = "attack01", -- 攻击01
    Cook = "cook", -- 做饭
    CutTree = "cutTree", -- 砍树
    CutTree2 = "cutTree2", -- 砍树 2
    HammerWork = "hammerwork", -- 捶打
    HandRub = "workwood", -- 手搓
    Heal = "heal2", -- 治疗
    Dig = "dig", -- 挖掘
    Die = "die", -- 死亡
    Research = "research", -- 研究
    Sweep = "sweep", -- 打扫
    Javelin = "javelin", -- 标枪
    Shit = "shit", -- 拉屎
    
    Attack1 = "attack1", -- 攻击1
    Attack2 = "attack2", -- 攻击2
    Born = "born", -- 出生
    Dead1 = "dead1", -- 死亡1
    Dead2 = "dead2", -- 死亡2
    Hurt = "hurt", -- 受伤
    Run1 = "run1", -- 跑1
    Run2 = "run2", -- 跑2
    Stun = "stun", -- 晕
    Walk1 = "walk1", -- 走1
    Walk2 = "walk2", -- 走2
    Born1 = "born1", -- 出生
    Idle1 = "idle1", -- 待机
    Die = "die", -- 躺着
    Shiver = "shiver", -- 瑟瑟发抖
    Sway = "sway", -- 摇铃铛
}

CityResidentDefines.AnimNameToSound = 
{
    [CityResidentDefines.AnimName.Ignite]= "Effect_people_ignite", -- 点燃
    --[CityResidentDefines.AnimName.Run] = "Effect_people_run", -- 跑
    --[CityResidentDefines.AnimName.RunHold] = "Effect_people_run_hold", -- 跑，手举东西
    [CityResidentDefines.AnimName.Eat] = "Effect_people_eattingfood", -- 坐，进食
    [CityResidentDefines.AnimName.Cook] = "Effect_people_cook", -- 做饭
    --[CityResidentDefines.AnimName.CutTree] = "Effect_people_cutTree", -- 砍树
    --[CityResidentDefines.AnimName.Attack01] = "Effect_pve_gun", -- 攻击
}

CityResidentDefines.EmoType =
{
    Default = 1,
    Fear = 2,--恐惧
    Alert = 3,
}

CityResidentDefines.EmoPath =
{
    [CityResidentDefines.EmoType.Default] = "Assets/Main/Sprites/UI/UIMain/icon_feeling",
    [CityResidentDefines.EmoType.Fear] = "Assets/Main/Sprites/UI/UIBuildBubble/bubble_icon_energy_kongju",
    [CityResidentDefines.EmoType.Alert] = "Assets/Main/Sprites/UI/UIAnimEmoji/gantanhao",
}

CityResidentDefines.ReadyQueueTimeType =
{
    Leave = 1,
    Come = 2,
}

CityResidentDefines.TalkTriggerType =
{
    EnterHouse = 1,
    EnterBed = 2,
    ExitBed = 3,
    EnterPool = 4,
    EnterDesk = 5,
    EnterSawingTable = 6,
    EnterDiningTable = 7,
    EnterHuntingTool = 8,
    EnterElectricGenerator = 9,
    EnterForgingTable = 10,
    EnterBarSeat = 11,
    EnterCookingBench = 12,
    SetWorkBatch = 13,
    LevelUp = 14,
    ResidentScareHideInside = 15,
    ResidentScare = 16,
    ResidentHurt = 17,
    ResidentDie = 18,
    ZombieRetreat = 19,
    ZombieDie = 20,
    ResidentScareHideOutside = 21,
    ResidentBetray = 22,
    NoFood = 23,
    Strike = 24,
    StrikeEnd = 25,
    Bartender = 26,
    Drink = 27,
    Drunk = 28,
    BarNoSeat = 29,
    BossSiegeDay = 31,
    BossSiegeNight = 32,
    BossSiegeNightInvade = 33,
    BossSiegeEnd = 34,
    SetCareerHunter = 36,
    SetCareerSawyer = 37,
    SetCareerChef = 38,
    SetCareerSmith = 39,
    SetCareerPowerman = 40,
    SetCareerDoctor = 41,
    SetCareerBartender = 42,
}

CityResidentDefines.WayPointFlag =
{
    None = 0,
    City = 1 << 0, -- 城内点
    Digging = 1 << 1, -- 挖铁点
    Entrance = 1 << 2, -- 入口
    Exit = 1 << 3, -- 出口
    Hunting = 1 << 4, -- 打猎点
    Special = 1 << 5, -- 特殊点
    Invade = 1 << 6, -- 入侵点
    Zombie = 1 << 7, -- 丧尸徘徊点
    SafeHide = 1 << 8, -- 安全躲藏点
    ZombieSpawn = 1 << 9, -- 丧尸出生点
    Chopping = 1 << 10, -- 砍树点
    Center = 1 << 11, --中心区域
    Outside = 1 << 12, -- 围栏外
    Inside = 1 << 13, -- 围栏内
    All = 0x7FFFFFFF,
}

CityResidentDefines.ScareHideBuildIds =
{
    BuildingTypes.FUN_BUILD_SOLAR_POWER_STATION,
    BuildingTypes.DS_RESTAURANT,
    BuildingTypes.DS_COAL_YARD,
    BuildingTypes.DS_FACTORY,
    BuildingTypes.DS_FARM,
    BuildingTypes.DS_BAR,
    BuildingTypes.DS_HOSPITAL_1,
    BuildingTypes.DS_HOUSE_1,
    BuildingTypes.DS_HOUSE_2,
    BuildingTypes.DS_HOUSE_3,
    BuildingTypes.DS_HOUSE_4,
    BuildingTypes.DS_HOUSE_5,
    BuildingTypes.DS_HOUSE_6,
    BuildingTypes.DS_HOUSE_7,
    BuildingTypes.DS_HOUSE_8,
}

CityResidentDefines.MoveType =
{
    LeaveBuilding = 1,
    GoToBuilding = 2,
    GoToFurniture = 3,
    GoToMaskPos = 4,
    GoToAccuratePos = 5,
}

CityResidentDefines.WorkWayPointFlag =
{
    [CityResidentDefines.Career.Hunter] = CityResidentDefines.WayPointFlag.Hunting,
    [CityResidentDefines.Career.Sawyer] = CityResidentDefines.WayPointFlag.Chopping,
    [CityResidentDefines.Career.Smith] = CityResidentDefines.WayPointFlag.Digging,
}

CityResidentDefines.BossType =
{
    Normal = 0,
    Big = 1,
}

return CityResidentDefines