---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by w.
--- DateTime: 2022/11/30 12:52
---

local UIParkourBattleMain = {
    Name = UIWindowNames.UIParkourBattleMain,
    Layer = UILayer.Background,
    Ctrl = require "UI.UIParkour.MainUI.Controller.UIParkourBattleMainCtrl",
    View = require "UI.UIParkour.MainUI.View.UIParkourBattleMainView",
    PrefabPath = "Assets/Main/Prefabs/UI/ParkourBattle/UIParkourBattleMain.prefab",
}

return {
    -- 配置
    UIParkourBattleMain = UIParkourBattleMain,
}