---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2022/12/5 10:38
---



local DecorationData = BaseClass("DecorationData")
local Localization = CS.GameEntry.Localization

local function __init(self)
    self.skinId = 0
    self.type = 0
    self.expireTime = 0
    self.wear = 0
    self.uuidArr = {}--穿皮肤的编队id组<long, true>
end

local function __delete(self)
    self.skinId = 0
    self.type = 0
    self.expireTime = 0
    self.wear = 0
    self.uuidArr = {}--穿皮肤的编队id组<long, true>
end

local function ParseData(self, data)
    --"skinId" 		//int
    --"type"   		//int 皮肤类型 1总部装扮 2头像框
    --"expireTime"	//long 皮肤过期时间单位ms。=0表示永久
    --"wear"          //int  当前是否穿戴 1穿戴。0未穿戴
    self.skinId = data["skinId"]
    self.type = data["type"]
    self.expireTime = data["expireTime"]
    self.wear = data["wear"]
    self.uuidArr = {}
    local uuidArr = data["uuidArr"]
    if uuidArr ~= nil then
        for k,v in ipairs(uuidArr) do
            self.uuidArr[v] = true
        end
    end
  
end

local function IsWear(self, formationUuid)
    return self.wear == 1 and self:IsFormation(formationUuid)
end

local function SetIsWear(self, flg, formationUuid)
    if flg == false then
        if formationUuid ~= nil then
            self.uuidArr[formationUuid] = nil
        end
        if table.count(self.uuidArr) == 0 then
            self.wear = 0
        end
    else
        self.wear = 1
        if formationUuid ~= nil then
            self.uuidArr[formationUuid] = true
        end
    end
end

local function IsInExpireTime(self)
    local lastSex = LuaEntry.Player:GetSex()
    local template = DataCenter.DecorationTemplateManager:GetTemplate(self.skinId)
    if template and lastSex ~= SexType.Woman and template.type_gain == DecorationGainType.DecorationGainType_Female then
        return false
    end

    if self.expireTime <= 0 then
        return true
    end

    local now = UITimeManager:GetInstance():GetServerTime()
    return now < self.expireTime
end

--该编队是否穿上皮肤
function DecorationData:IsFormation(formationUuid)
    if formationUuid == nil or formationUuid == 0 then
        return true
    end
    return self.uuidArr[formationUuid] == true
end

DecorationData.__init = __init
DecorationData.__delete = __delete
DecorationData.ParseData = ParseData
DecorationData.IsWear = IsWear
DecorationData.SetIsWear = SetIsWear
DecorationData.IsInExpireTime = IsInExpireTime

return DecorationData