---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2022/3/15 15:21
---
local WorldNewsTips = require "Scene.WorldNewsTip.WorldNewsTips"
local WorldNewsTipsManager = BaseClass("WorldNewsTipsManager", Singleton)
local ResourceManager = CS.GameEntry.Resource
local function __init(self)
    self.allShowEffect = {}
    self.OnCreateShowEffect ={}
    self:AddListener()
end

local function __delete(self)
    for k,v in pairs(self.allShowEffect) do
        local request = v.request
        v:OnDestroy()
        request:Destroy()
    end
    self.allShowEffect = nil
    for k,v in pairs(self.OnCreateShowEffect) do
        v:Destroy()
    end
    self.OnCreateShowEffect = nil
    self:RemoveListener()
end

local function AddListener(self)
    EventManager:GetInstance():AddListener(EventId.PveLevelEnter, self.RemoveAllTips)
    EventManager:GetInstance():AddListener(EventId.UpdateWorldZoneNews, self.ShowZoneNewsIconShow)
    EventManager:GetInstance():AddListener(EventId.ChangeCameraLod, self.ChangeCameraLodSignal)
    EventManager:GetInstance():AddListener(EventId.OnEnterCrossServer, self.RemoveAllTips)
    EventManager:GetInstance():AddListener(EventId.OnBeforeEnterCity, self.RemoveAllTips)
end

local function RemoveListener(self)
    EventManager:GetInstance():RemoveListener(EventId.PveLevelEnter, self.RemoveAllTips)
    EventManager:GetInstance():RemoveListener(EventId.UpdateWorldZoneNews, self.ShowZoneNewsIconShow)
    EventManager:GetInstance():RemoveListener(EventId.ChangeCameraLod, self.ChangeCameraLodSignal)
    EventManager:GetInstance():RemoveListener(EventId.OnEnterCrossServer, self.RemoveAllTips)
    EventManager:GetInstance():RemoveListener(EventId.OnBeforeEnterCity, self.RemoveAllTips)
end

local function ChangeCameraLodSignal(lod)
    WorldNewsTipsManager:GetInstance():UpdateLod(lod)
end
local function RemoveAllTips(data)
    WorldNewsTipsManager:GetInstance():RemoveAllShowIcon()
end
local function UpdateLod(self, lod)
    if self.lodCache ~=lod then
        self.lodCache =lod
        if self.lodCache>=5 then
            if CrossServerUtil:GetIsCrossServer()==false then
                DataCenter.WorldNewsDataManager:SendRequest()
            end
        else
            self:RemoveAllShowIcon()
        end
    end
end

local function RemoveAllShowIcon(self)
    for k,v in pairs(self.allShowEffect) do
        local request = v.request
        v:OnDestroy()
        request:Destroy()
    end
    self.allShowEffect = {}
    for k,v in pairs(self.OnCreateShowEffect) do
        v:Destroy()
    end
    self.OnCreateShowEffect = {}
end
local function RemoveOneShowIcon(self,id)
    if self.allShowEffect~=nil and self.allShowEffect[id]~=nil then
        local tips = self.allShowEffect[id]
        local request = tips.request
        tips:OnDestroy()
        request:Destroy()
        self.allShowEffect[id] = nil
    end
    if self.OnCreateShowEffect[id]~=nil then
        self.OnCreateShowEffect[id]:Destroy()
        self.OnCreateShowEffect[id] = nil
    end
end
local function InitShowList(self)
    if CrossServerUtil:GetIsCrossServer()==true then
        return
    end
    if SceneUtils.GetIsInWorld()==false then
        return
    end
    local infoList = DataCenter.WorldNewsDataManager:GetAreaInfoList()
    local deleteList = {}
    for k,v in pairs(self.OnCreateShowEffect) do
        if infoList[k] ==nil then
            table.insert(deleteList,k)
        end
    end
    for k,v in pairs(self.allShowEffect) do
        if infoList[k] ==nil then
            table.insert(deleteList,k)
        end
    end
    for k, v in pairs(deleteList) do
        self:RemoveOneShowIcon(v)
    end
    for k,v in pairs(infoList) do
        if self.allShowEffect[k]==nil and self.OnCreateShowEffect[k] == nil then
            local request = ResourceManager:InstantiateAsync(UIAssets.WorldNewsTips)
            self.OnCreateShowEffect[k] = request
            request:completed('+', function()
                self.OnCreateShowEffect[k] =nil
                if request.isError then
                    return
                end
                request.gameObject:SetActive(true)
                request.gameObject.transform:SetParent(CS.SceneManager.World.DynamicObjNode)
                request.gameObject.transform:Set_localScale(ResetScale.x, ResetScale.y, ResetScale.z)

                local effect = WorldNewsTips.New()
                effect:OnCreate(request)
                effect:SetData(v)
                self.allShowEffect[k] = effect
            end)
        end
    end
end
local function ShowZoneNewsIconShow(data)
    WorldNewsTipsManager:GetInstance():InitShowList()
end
WorldNewsTipsManager.__init = __init
WorldNewsTipsManager.__delete = __delete
WorldNewsTipsManager.AddListener = AddListener
WorldNewsTipsManager.RemoveListener = RemoveListener
WorldNewsTipsManager.ChangeCameraLodSignal = ChangeCameraLodSignal
WorldNewsTipsManager.UpdateLod =UpdateLod
WorldNewsTipsManager.RemoveAllShowIcon = RemoveAllShowIcon
WorldNewsTipsManager.ShowZoneNewsIconShow= ShowZoneNewsIconShow
WorldNewsTipsManager.RemoveOneShowIcon = RemoveOneShowIcon
WorldNewsTipsManager.InitShowList = InitShowList
WorldNewsTipsManager.RemoveAllTips =RemoveAllTips
return WorldNewsTipsManager