---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guqu.
--- DateTime: 2020/9/30 10:38
---
local AlScienceGoldDonateMessage = BaseClass("AlScienceGoldDonateMessage", SFSBaseMessage)
local base = SFSBaseMessage
local Localization = CS.GameEntry.Localization

local function OnCreate(self, scienceId)
    base.OnCreate(self)
    self.sfsObj:PutInt("scienceId", scienceId)
end

local function HandleMessage(self, t)
    base.HandleMessage(self, t)
    local errCode =  t["errorCode"]
    if errCode ~= nil then
        UIUtil.ShowTipsId(errCode) 
    else
        DataCenter.AllianceScienceDataManager:EndRefreshAllScienceNum(t)
        DataCenter.AllianceScienceDataManager:UpdateOneAllianceScience(t)
        if t["gold"] then
            LuaEntry.Player.gold = t["gold"]
            EventManager:GetInstance():Broadcast(EventId.UpdateGold)
        end
        if t["contributeValue"]~=nil then
            local contributeValue = t["contributeValue"]
            UIUtil.ShowTips(Localization:GetString("390260",contributeValue,contributeValue), nil, nil, nil, true)
        end
        if t["alliancepoint"]~=nil then
            local data =  DataCenter.AllianceBaseDataManager:GetAllianceBaseData()
            if data ~= nil then
                data.alliancePoint = t["alliancepoint"]
            end
        end
        if t["accPoint"]~=nil then
            local data =  DataCenter.AllianceBaseDataManager:GetAllianceBaseData()
            if data ~= nil then
                data.accPoint = t["accPoint"]
            end
        end
        if t["criticalHitRatio"] then
            local ratio = tonumber(t["criticalHitRatio"])
            if ratio > 1 then
                local param = {}
                param.type = 1
                param.ratio = ratio
                EventManager:GetInstance():Broadcast(EventId.ShowAlScienceCriticalHitRatio, param)
            end
        end
        EventManager:GetInstance():Broadcast(EventId.RefreshItems)
        EventManager:GetInstance():Broadcast(EventId.AllianceTechnology)
    end
end
AlScienceGoldDonateMessage.OnCreate = OnCreate
AlScienceGoldDonateMessage.HandleMessage = HandleMessage

return AlScienceGoldDonateMessage