---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2023/10/9 20:49
---
local UIRuinsRankDetailView = BaseClass("UIRuinsRankDetailView", UIBaseView)
local base = UIBaseView
local RuinsRankDetailItem = require "UI.UIRuinsRankDetail.Component.RuinsRankDetailItem"
local Localization = CS.GameEntry.Localization
local return_path = "UICommonPopUpTitle/panel"
local close_path = "UICommonPopUpTitle/bg_mid/CloseBtn"
local title_path = "UICommonPopUpTitle/bg_mid/titleText"
local self_path = "layout/layout2/Self"
local rank_desc_path = "layout/Head/RankDesc"
local name_desc_path = "layout/Head/NameDesc"
local score_desc_path = "layout/Head/ScoreDesc"
local scroll_view_path = "layout/layout2/ScrollView"

local function OnCreate(self)
    base.OnCreate(self)
    self.rankUuid,self.showTip = self:GetUserData()
    self:DataDefine()
    self:ComponentDefine()
end

local function OnDestroy(self)
    self:ComponentDestroy()
    self:DataDestroy()
    base.OnDestroy(self)
end

local function OnEnable(self)
    base.OnEnable(self)
    self:ReInit()
end

local function OnDisable(self)
    base.OnDisable(self)
end

local function ComponentDefine(self)
    self.return_btn = self:AddComponent(UIButton, return_path)
    self.return_btn:SetOnClick(function()
        self.ctrl:CloseSelf()
    end)
    self.close_btn = self:AddComponent(UIButton, close_path)
    self.close_btn:SetOnClick(function()
        self.ctrl:CloseSelf()
    end)
    self.scroll_view = self:AddComponent(UIScrollView, scroll_view_path)
    self.title_text = self:AddComponent(UITextMeshProUGUIEx, title_path)
    self.title_text:SetLocalText(111243)
    self.empty_txt = self:AddComponent(UITextMeshProUGUIEx, "emptyTxt")
    self.empty_txt:SetLocalText(111258)
    self.self_item = self:AddComponent(RuinsRankDetailItem, self_path)
    self.rank_desc_text = self:AddComponent(UITextMeshProUGUIEx, rank_desc_path)
    self.rank_desc_text:SetLocalText(302043)
    self.name_desc_text = self:AddComponent(UITextMeshProUGUIEx, name_desc_path)
    self.name_desc_text:SetLocalText(320763)
    self.score_desc_text = self:AddComponent(UITextMeshProUGUIEx, score_desc_path)
    self.score_desc_text:SetLocalText(375047)
    self.layout = self:AddComponent(UIBaseContainer,"layout")
    self.layout1 = self:AddComponent(UIBaseContainer,"layout/layout1")
    self.des1 = self:AddComponent(UITextMeshProUGUIEx,"layout/layout1/des1")
    self.des2 = self:AddComponent(UITextMeshProUGUIEx,"layout/layout1/des2")
    self.scroll_view:SetOnItemMoveIn(function(itemObj, index)
        self:OnCellMoveIn(itemObj, index)
    end)
    self.scroll_view:SetOnItemMoveOut(function(itemObj, index)
        self:OnCellMoveOut(itemObj, index)
    end)
    self.layout1:SetActive(self.showTip)
    CS.UnityEngine.UI.LayoutRebuilder.ForceRebuildLayoutImmediate(self.layout.rectTransform)
end

local function ComponentDestroy(self)

end

local function DataDefine(self)
    self.dataList = {}
    self.items = {}
end

local function DataDestroy(self)

end

local function OnAddListener(self)
    base.OnAddListener(self)
end

local function OnRemoveListener(self)
    base.OnRemoveListener(self)
end

local function OnCellMoveIn(self, itemObj, index)
    itemObj.name = tostring(index)
    local item = self.scroll_view:AddComponent(RuinsRankDetailItem, itemObj)
    item:SetData(self.dataList[index])
    self.items[index] = item
end

local function OnCellMoveOut(self, itemObj, index)
    self.scroll_view:RemoveComponent(itemObj.name, RuinsRankDetailItem)
    self.items[index] = nil
end



local function ReInit(self)
    local RankData = DataCenter.WorldAllianceCityRecordManager:GetRecordDataByUuid(self.rankUuid)
    if RankData~=nil then
        local selfData = {}
        selfData.uid = LuaEntry.Player.uid
        selfData.serverId = LuaEntry.Player:GetSelfServerId()
        selfData.rank = RankData.selfRank or 0
        selfData.score = RankData.selfScore or 0
        selfData.power = LuaEntry.Player.power
        selfData.name = LuaEntry.Player.name
        selfData.pic = LuaEntry.Player.pic
        selfData.picVer = LuaEntry.Player.picVer
        selfData.headSkinId = LuaEntry.Player.headSkinId
        selfData.headSkinET = LuaEntry.Player.headSkinET
        self.self_item:SetData(selfData)
        local template = DataCenter.AllianceCityTemplateManager:GetTemplate(RankData.cityId)
        if template~=nil then
            local pos = template.pos
            self.pos = pos
            local level = template.level
            local name = template.name
            local str = Localization:GetString("111250",Localization:GetString("310128", level, Localization:GetString(name)),"("..pos.x..","..pos.y..")")
            self.des1:SetText(str)
        end
        self.des2:SetText(Localization:GetString("111251")..": "..UITimeManager:GetInstance():TimeStampToTimeForServer(RankData.recordTime))
        self.dataList = RankData.rankList or {}
        local count = #self.dataList
        if count > 0 then
            self.scroll_view:SetActive(true)
            self.scroll_view:SetTotalCount(count)
            self.scroll_view:RefillCells()
            self.empty_txt:SetActive(false)
        else
            self.scroll_view:SetActive(false)
            self.empty_txt:SetActive(true)
        end
    else
        local selfData = {}
        selfData.uid = LuaEntry.Player.uid
        selfData.serverId = LuaEntry.Player:GetSelfServerId()
        selfData.rank =  0
        selfData.score =  0
        selfData.power = LuaEntry.Player.power
        selfData.name = LuaEntry.Player.name
        selfData.pic = LuaEntry.Player.pic
        selfData.picVer = LuaEntry.Player.picVer
        selfData.headSkinId = LuaEntry.Player.headSkinId
        selfData.headSkinET = LuaEntry.Player.headSkinET
        self.self_item:SetData(selfData)
        self.scroll_view:SetActive(false)
        self.empty_txt:SetActive(true)
    end
end

UIRuinsRankDetailView.OnCreate = OnCreate
UIRuinsRankDetailView.OnDestroy = OnDestroy
UIRuinsRankDetailView.OnEnable = OnEnable
UIRuinsRankDetailView.OnDisable = OnDisable
UIRuinsRankDetailView.ComponentDefine = ComponentDefine
UIRuinsRankDetailView.ComponentDestroy = ComponentDestroy
UIRuinsRankDetailView.DataDefine = DataDefine
UIRuinsRankDetailView.DataDestroy = DataDestroy
UIRuinsRankDetailView.OnAddListener = OnAddListener
UIRuinsRankDetailView.OnRemoveListener = OnRemoveListener

UIRuinsRankDetailView.OnCellMoveIn = OnCellMoveIn
UIRuinsRankDetailView.OnCellMoveOut = OnCellMoveOut

UIRuinsRankDetailView.ReInit = ReInit

return UIRuinsRankDetailView