---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2023/10/31 14:47
---
local UIUseEdenMissileTipCtrl = BaseClass("UIUseEdenMissileTipCtrl", UIBaseCtrl)

local function CloseSelf(self)
    UIManager:GetInstance():DestroyWindow(UIWindowNames.UIUseEdenMissileTip)
end

local function Close(self)
    UIManager:GetInstance():DestroyWindowByLayer(UILayer.Normal)
end

UIUseEdenMissileTipCtrl.CloseSelf = CloseSelf
UIUseEdenMissileTipCtrl.Close = Close

return UIUseEdenMissileTipCtrl