---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2023/9/19 21:52
---
local CharacterBaseState = require("Scene.PVEBattleLevel.Character.State.CharacterBaseState")
local CharacterPickGarbageState = BaseClass("CharacterPickGarbageState",CharacterBaseState)

function CharacterPickGarbageState:OnEnter()
    local aniName = self.m_data
    if string.IsNullOrEmpty(aniName) then
        aniName = "Dig"
    end
    self.m_owner:PlayAnim(aniName)
    if self.m_owner.isPlayer then
        self.m_owner:ShowToolByPath("weapon/chuizi")
    end
end

function CharacterPickGarbageState:OnExit()
    if self.m_owner.isPlayer then
        self.m_owner:ResetWeapon()
    end
end

return CharacterPickGarbageState