---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2023/6/26 10:34
---
local CharacterBaseState = require("Scene.PVEBattleLevel.Character.State.CharacterBaseState")
local CharacterStandUpState = BaseClass("CharacterStandUpState",CharacterBaseState)
local CharacterStateType = require("Scene.PVEBattleLevel.Character.State.CharacterStateType")

function CharacterStandUpState:SetData(data)
    CharacterBaseState.SetData(self,data)
end

function CharacterStandUpState:OnEnter()
    self:PlayAnim()
end

function CharacterStandUpState:PlayAnim()
    local totalTime = 3
    self.delayTimer = TimerManager:GetInstance():DelayInvoke(function()
        self:OnExit()
        self.delayTimer = nil
    end,totalTime)
    self.m_owner:PlayAnim("nvlieshou_low_hug_stand")
end


function CharacterStandUpState:OnExit()
    if self.delayTimer then
        self.delayTimer:Stop()
        self.delayTimer = nil
    end
    self:OnStateComplete()
end

return CharacterStandUpState