---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 19/3/2024 上午11:24
---
local base = WorldPointObject
local WorldResObject = BaseClass("WorldResObject",WorldPointObject)
function WorldResObject:__init()
    base.__init(self)
    self.model= nil
    self.headObj = nil
    self.headBg = nil
    self.headIcon = nil
    self.stateIcon = nil
    self.lodIcon = nil
    self.gatherMarchUuid =0
    self.cityLabels = {}
end

function WorldResObject:__delete()
    self.model= nil
    self.headObj = nil
    self.headBg = nil
    self.headIcon = nil
    self.stateIcon = nil
    self.lodIcon = nil
    self.cityLabels = {}
    self.gatherMarchUuid =0
    base.__delete(self)
end

function WorldResObject:Destroy()
    self:DestroyModel()
    base.Destroy(self)
end
function WorldResObject:CreateGameObject()
    base.CreateGameObject(self)
    local info = DataCenter.WorldPointManager:GetPointInfo(self.pointIndex)
    if info~=nil then
        local bi = info.resourceInfo
        if bi~=nil then
            self:AddOldObject()
            self.instance = CS.GameEntry.Resource:InstantiateAsync(self:GetAssetPath(bi.resourceId))
            self.instance:completed('+',function()
                self:DestroyModel()
                self:ClearOldObject()
                self.gameObject = self.instance.gameObject
                if self.gameObject~=nil then
                    self.gameObject.transform:SetParent(CS.SceneManager.World.DynamicObjNode)
                    self.gameObject.transform.position = SceneUtils.TileIndexToWorld(self.pointIndex,ForceChangeScene.World)
                    self.gameObject:SetActive(self.isVisible)
                    self.lodIcon = self.gameObject.transform:Find("Icon/CollectResourceIconSprite"):GetComponentInChildren(typeof(CS.UnityEngine.SpriteRenderer), true)
                    self.cityLabels = self.gameObject:GetComponentsInChildren(typeof(CS.UIWorldLabel),true)
                    self:SetAutoAdjustLod()
                    local icon =  self.gameObject.transform:Find("Icon/troopIcon")
                    if icon~=nil then
                        self.headObj = icon.gameObject.transform:Find("head")
                        if self.headObj~=nil then
                            self.headBg = self.headObj.gameObject.transform:Find("headbg"):GetComponentInChildren(typeof(CS.UnityEngine.SpriteRenderer), true)
                            self.headIcon = self.headObj.gameObject.transform:Find("headIcon"):GetComponentInChildren(typeof(CS.UnityEngine.SpriteRenderer), true)
                        end
                    end
                    self.stateIcon = self.gameObject.transform:Find("Model/stateIcon"):GetComponentInChildren(typeof(CS.UnityEngine.SpriteRenderer), true)
                    
                    local showIcon = false
                    local headBgImg = ""
                    local headIconImg = ""
                    local UserHeadPath = ""
                    local iconColor = Color.New(1,1,1,1)
                    if bi.gatherUuid~=0 then
                        local marchInfo = DataCenter.WorldMarchDataManager:GetMarch(bi.gatherUuid)
                        if marchInfo ~= nil and marchInfo:IsMine() then
                            UserHeadPath = "Assets/Main/Sprites/UI/Common/New/Common_icon_march_collect"
                            self.gatherMarchUuid = bi.gatherMarchUuid
                            showIcon = true
                            local armyInfo = marchInfo:GetFirstArmyInfo()
                            if armyInfo~=nil and armyInfo.HeroInfos~=nil then
                                local heroData = armyInfo.HeroInfos[1]
                                local rarity = tonumber(GetTableData(HeroUtils.GetHeroXmlName(), heroData.heroId, "rarity"))
                                local isReachMax = heroData:GetIsAllSKillReachMax()
                                if isReachMax~=nil and isReachMax == true then
                                    if rarity ~= HeroUtils.RarityType.S then
                                        isReachMax = false
                                    end
                                else
                                    isReachMax = false
                                end
                                headBgImg = HeroUtils.GetCircleQualityIconPath(rarity,isReachMax)
                                headIconImg = HeroUtils.GetHeroIconRoundPath(heroData.heroId)
                            end
                            iconColor = Color.New(0.68, 0.98, 0.1, 1)
                        elseif marchInfo ~= nil and LuaEntry.Player:IsInAlliance() and marchInfo.allianceUid == LuaEntry.Player.allianceId then
                            iconColor = Color.New(0.06, 0.54, 0.98,1)
                            UserHeadPath = "Assets/Main/Sprites/UI/Common/New/Common_icon_march_collect_alliance"
                        else
                            if marchInfo~=nil then
                                if LuaEntry.Player.serverType == ServerType.EDEN_SERVER and DataCenter.RobotWarsManager:GetSelfCamp()>0 and DataCenter.GloryManager:IsSameCampByAllianceId(marchInfo.allianceUid) then
                                    iconColor = Color.New(0.996, 0.913, 0.007, 1)
                                    UserHeadPath = "Assets/Main/Sprites/UI/Common/New/Common_icon_march_collect_yellow"
                                else
                                    iconColor = Color.New(0.95,0.24,0.24,1)
                                    UserHeadPath = "Assets/Main/Sprites/UI/Common/New/Common_icon_march_collect_other"
                                end   
                            end
                        end
                        if self.stateIcon~=nil then
                            self.stateIcon.gameObject:SetActive(true)
                            self.stateIcon:LoadSprite(UserHeadPath)
                        end
                    else
                        if self.stateIcon~=nil then
                            self.stateIcon.gameObject:SetActive(false)
                        end
                    end
                    if self.headObj~=nil then
                        if showIcon then
                            self.headObj.gameObject:SetActive(true)
                            if self.headBg~=nil then
                                self.headBg:LoadSprite(headBgImg)
                            end
                            if self.headIcon~=nil then
                                self.headIcon:LoadSprite(headIconImg)
                            end
                        else
                            self.headObj.gameObject:SetActive(false)
                        end
                    end
                    
                    local resLevel = GetTableData(TableName.GatherResource,bi.resourceId,"level")
                    if self.cityLabels~=nil then
                        for i = 0, self.cityLabels.Length-1 do
                            local item = self.cityLabels[i]
                            if item~=nil then
                                item.gameObject:SetActive(true)
                                item:SetLevel(toInt(resLevel),iconColor)
                            end
                        end
                    end
                    self:SetClickEvent()
                end
                self:CheckShowTroopDestination()
            end)
        end
    end
end

function WorldResObject:UpdateGameObject()
    self:CreateGameObject()
end

function WorldResObject:GetAssetPath(id)
    local resModel = GetTableData(TableName.GatherResource,id,"model")
    if resModel~=nil and resModel~="" then
        return "Assets/Main/Prefabs/CollectResource/"..resModel..".prefab"
    end
    return "Assets/Main/Prefabs/CollectResource/CollectResourcesGold_world.prefab"
end

function WorldResObject:DestroyModel()
    if self.gatherMarchUuid~=0 then
        EventManager:GetInstance():Broadcast(EventId.CollectPointOut,self.gatherMarchUuid)
        self.gatherMarchUuid = 0
    end
end
return WorldResObject
