---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2021/10/21 16:32
---
local str = [[
syntax = "proto3";  // 指定使用 proto3 语法
package protobuf;
option java_package = "net.im30.aps.model.protobuf";

message BuildInfo {
  string ownerUid = 1;
  int64 uuid = 2;
  int32 buildId = 3;
  int32 level = 4;
  int32 buildState = 5;
  int32 queueState = 6;
  string allianceId = 7;
  int32 updateEndTime = 8;
  int32 updateStartTime = 9;
  int32 lastHpTime = 10; // 上次回血时间
  int32 protectEndTime = 11; // 保护结束时间
  int32 inside = 12; // 是否城内建筑
  int32 currentHp = 13;// 当前血量
  string name = 14; // 玩家名称(仅大本显示)
  string alAbbr = 15; // 联盟简称(仅大本显示)
  int32 lastCollectTime = 16; // 资源站上次采集时间
  int32 unavailableTime = 17; // 资源站不可用时间
  int32 monthCardEndTime = 18; //月卡结束时间 单位s
  int32 queueItemId = 19;// 队列id
  int32 queueStartTime = 20;// 队列开始
  int32 queueUpdateTime = 21; // 队列结束
}

message RoadInfo {
  string ownerUid = 1;
  int64 uuid = 2;
  int32 roadState = 3;
  int32 inside = 4;
  int32 currentHp = 5; // 当前血量
  string allianceId = 6;
}

message CollectResourceInfo {
  int32 resourceType = 1;
  int32 level = 2;
}

message ResourceInfo {
  int32 resourceId = 1;
  int32 state = 2;
  int64 gatherUuid = 3;
}

message ExplorePointInfo{
  string ownerUid = 1;
  int64 uuid = 2;
  string eventId = 3;
}

message SamplePointInfo{
  string ownerUid = 1;
  int64 uuid = 2;
  string eventId = 3;
}

message GarbagePointInfo{
  string ownerUid = 1;
  int64 uuid = 2;
  string eventId = 3;
  int64 endTime = 4;  
}

message AllianceCityPointInfo {
  int32 cityId = 1;
  int32 openTime = 2;
  int32 state = 3;
  int32 protectTime = 4;
  string alAbbr = 5;
  string allianceId = 7;
  int32 durability = 8;
  int32 lastDurabilityTime = 9;
  string alName = 10;
  int32 giveUpTime = 11;
  string cityName = 12;
}

message CollectRewardInfo {
  string ownerUid = 1;
  int64 uuid = 2;
  int64 expireTime = 3;
  int32 contentId = 4;
}

message WorldPointInfo {
  int32 id = 1;
  int32 pointType = 2;
  BuildInfo buildInfo = 3;
  RoadInfo roadInfo = 4;
  CollectResourceInfo collectResourceInfo = 5;
  ResourceInfo resourceInfo = 6;
  ExplorePointInfo explorePointInfo = 7;
  SamplePointInfo samplePointInfo = 8;
  GarbagePointInfo garbagePointInfo = 9;
  
  int64 uuid = 100;
  bytes extraInfo = 101;
}
]]

return str
