---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2023/2/24 17:31
---


local EquipmentTemplateManager = BaseClass("EquipmentTemplateManager")
local EquipmentTemplate = require "DataCenter.EquipmentManager.EquipmentTemplate"

local function __init(self)
    self.allTemplate = {}
    self.equipUpgradeQualityLevel = {}
    self.isInit = false
end

local function __delete(self)
    self.allTemplate = {}
    self.isInit = false
    self.equipUpgradeQualityLevel = {}
end

local function GetTemplate(self, id)
    if not self.isInit then
        self:InitAllTemplate()
    end
    return self.allTemplate[tonumber(id)]
end

local function GetAllTemplate(self)
    if not self.isInit then
        self:InitAllTemplate()
    end
    return self.allTemplate or {}
end

local function InitAllTemplate(self)
    if self.isInit then
        return
    end
    self.isInit = true
    self.allTemplate = {}
    LocalController:instance():visitTable(TableName.Equip, function(_, lineData)
        local item = EquipmentTemplate.New()
        item:InitData(lineData)
        self.allTemplate[tonumber(item.id)] = item
        if table.count(item.qualityUpgradeCost) > 0 then
            local lvId = EquipmentUtil.GetEquipmentLv1Id(tonumber(item.id))
            if self.equipUpgradeQualityLevel[lvId] == nil then
                self.equipUpgradeQualityLevel[lvId] = {}
                table.insert(self.equipUpgradeQualityLevel[lvId], 0)
            end
            table.insert(self.equipUpgradeQualityLevel[lvId], item.level)
        end
    end)
    for _, k in pairs(self.equipUpgradeQualityLevel) do
        table.sort(k, function (a, b)
            return a < b
        end)
    end
end

local function GetQualityUnlockLv(self, equipmentId, color) 
    local lvId = EquipmentUtil.GetEquipmentLv1Id(tonumber(equipmentId))
    if self.equipUpgradeQualityLevel[lvId] == nil then
        return 1
    end
    return self.equipUpgradeQualityLevel[lvId][color] or 1
end

EquipmentTemplateManager.__init = __init
EquipmentTemplateManager.__delete = __delete
EquipmentTemplateManager.GetTemplate = GetTemplate
EquipmentTemplateManager.InitAllTemplate = InitAllTemplate
EquipmentTemplateManager.GetAllTemplate = GetAllTemplate
EquipmentTemplateManager.GetQualityUnlockLv = GetQualityUnlockLv

return EquipmentTemplateManager